include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/api/schema.g.dart
    - build/**
    - android/**
    - ios/**
    - web/**
linter:
  rules:
    prefer_const_constructors: true
