// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE user_addresses
   SET is_default = FALSE
 WHERE user_id = $1
   AND is_default
   AND deleted_at IS NULL
   AND id <> $2
`

type ClearDefaultAddressParams struct {
	UserID int64
	KeepID int64
}

// 清掉这个买家现有的默认地址，除了 keep_id 那一条（新增时传 0）。
//
// 「先清旧、再置新」必须在同一事务里、按这个顺序（数据模型 §9）：反过来的话
// 新的那一行先变成默认，自己撞上 uk_user_addresses_default。
// 排除 keep_id 是为了让「对已是默认的地址再设一次」不经过一个
// 「零个默认」的中间态 —— 那个中间态在同一事务里没人看得见，但它会白写一行。
func (q *Queries) ClearDefaultAddress(ctx context.Context, arg ClearDefaultAddressParams) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, arg.UserID, arg.KeepID)
	return err
}

const findUserAddress = `-- name: FindUserAddress :one
SELECT id, receiver_name, phone, province, city, district, street, detail,
       region_code, postal_code, tag, is_default, lat, lng, created_at, updated_at
  FROM user_addresses
 WHERE id = $1
   AND user_id = $2
   AND deleted_at IS NULL
`

type FindUserAddressParams struct {
	ID     int64
	UserID int64
}

type FindUserAddressRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// 取一条。查不到（含属于别人、已软删）即 ErrNoRows。
func (q *Queries) FindUserAddress(ctx context.Context, arg FindUserAddressParams) (FindUserAddressRow, error) {
	row := q.db.QueryRow(ctx, findUserAddress, arg.ID, arg.UserID)
	var i FindUserAddressRow
	err := row.Scan(
		&i.ID,
		&i.ReceiverName,
		&i.Phone,
		&i.Province,
		&i.City,
		&i.District,
		&i.Street,
		&i.Detail,
		&i.RegionCode,
		&i.PostalCode,
		&i.Tag,
		&i.IsDefault,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserAddress = `-- name: InsertUserAddress :one
INSERT INTO user_addresses (user_id, receiver_name, phone, province, city, district,
                            street, detail, region_code, postal_code, tag, is_default, lat, lng)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, receiver_name, phone, province, city, district, street, detail,
          region_code, postal_code, tag, is_default, lat, lng, created_at, updated_at
`

type InsertUserAddressParams struct {
	UserID       int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
}

type InsertUserAddressRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// 新增一条。租户列不出现在这条语句里：00030 给了它 DEFAULT current_merchant()，
// 调用方手里没有那个参数可以传错。
//
// is_default 为真时，调用方必须已经在同一事务里清掉了旧默认
// （ClearDefaultAddress），否则这里撞 uk_user_addresses_default。
func (q *Queries) InsertUserAddress(ctx context.Context, arg InsertUserAddressParams) (InsertUserAddressRow, error) {
	row := q.db.QueryRow(ctx, insertUserAddress,
		arg.UserID,
		arg.ReceiverName,
		arg.Phone,
		arg.Province,
		arg.City,
		arg.District,
		arg.Street,
		arg.Detail,
		arg.RegionCode,
		arg.PostalCode,
		arg.Tag,
		arg.IsDefault,
		arg.Lat,
		arg.Lng,
	)
	var i InsertUserAddressRow
	err := row.Scan(
		&i.ID,
		&i.ReceiverName,
		&i.Phone,
		&i.Province,
		&i.City,
		&i.District,
		&i.Street,
		&i.Detail,
		&i.RegionCode,
		&i.PostalCode,
		&i.Tag,
		&i.IsDefault,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAddresses = `-- name: ListUserAddresses :many

SELECT id, receiver_name, phone, province, city, district, street, detail,
       region_code, postal_code, tag, is_default, lat, lng, created_at, updated_at
  FROM user_addresses
 WHERE user_id = $1
   AND deleted_at IS NULL
 ORDER BY is_default DESC, updated_at DESC, id DESC
`

type ListUserAddressesRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// 地址簿（/addresses，数据模型 §9 user_addresses）。
//
// 全文没有一处 WHERE 写租户：租户由 RLS 在数据库层过滤，理由见
// db/queries/products.sql 与 scripts/check_query_tenancy.py。
//
// **每一条都带 user_id = 当前买家**。那不是租户过滤，是越权过滤：RLS 只保证
// 这一行属于本店，不保证它属于这个买家。契约约定 4 与数据模型 §1 写明，
// 地址用自增 id 对外，越权防护靠服务端按 user_id 强制过滤，查不到即 404 ——
// 所以「别人的地址」与「不存在的地址」在这一层同形，这是对的：
// 分开报就是一个探测别人地址簿的口子。
//
// 每一条也都带 deleted_at IS NULL：软删的地址对买家不存在（契约：已软删的地址不返回）。
//
// 注释里一个反引号都不许有，理由见 db/queries/inventories.sql 的第三条说明。
// 地址簿。默认地址排在首位，其余按更新时间倒序（契约原话）。id 兜底让顺序确定：
// 同一事务里改过的两行 updated_at 相同（now() 是事务开始时刻）。
func (q *Queries) ListUserAddresses(ctx context.Context, userID int64) ([]ListUserAddressesRow, error) {
	rows, err := q.db.Query(ctx, listUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAddressesRow
	for rows.Next() {
		var i ListUserAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceiverName,
			&i.Phone,
			&i.Province,
			&i.City,
			&i.District,
			&i.Street,
			&i.Detail,
			&i.RegionCode,
			&i.PostalCode,
			&i.Tag,
			&i.IsDefault,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAddressesForStore = `-- name: ListUserAddressesForStore :many
SELECT ua.id, ua.receiver_name, ua.phone, ua.province, ua.city, ua.district, ua.street, ua.detail,
       ua.region_code, ua.postal_code, ua.tag, ua.is_default, ua.lat, ua.lng,
       ua.created_at, ua.updated_at,
       (ua.lat IS NOT NULL AND ua.lng IS NOT NULL)::boolean AS has_point,
       (st.is_default OR st.fence IS NULL
        OR COALESCE(ST_Intersects(st.fence::geometry,
                                  ST_SetSRID(ST_MakePoint(ua.lng, ua.lat), 4326)),
                    FALSE))::boolean AS serves
  FROM user_addresses ua
 CROSS JOIN stores st
 WHERE ua.user_id = $1
   AND ua.deleted_at IS NULL
   AND st.id = $2
   AND st.deleted_at IS NULL
 ORDER BY ua.is_default DESC, ua.updated_at DESC, ua.id DESC
`

type ListUserAddressesForStoreParams struct {
	UserID  int64
	StoreID int64
}

type ListUserAddressesForStoreRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	HasPoint     bool
	Serves       bool
}

// 地址簿 + 每条地址这家门店送不送得到（GET /addresses?store_id=，2026-09-30）。
// 结算页拿它自动挑一条配送范围内的地址；一条查询把全部地址一次算完，不逐条问。
//
// serves 的判据与 stores.sql 的 StoreServesPoint **是同一条**，改一处必须改另一处：
// 默认店与没有围栏的店一律 true，否则看坐标落不落在围栏内（ST_Intersects 平面判定，边界线上算在内；
// 为什么是平面不是球面见 stores.sql 文件头「围栏判定」）。
// 两处写法唯一的差别是这里的坐标可能缺：ST_MakePoint 遇 NULL 得 NULL，ST_Intersects 也得
// NULL，COALESCE 成 false；「没坐标所以判断不了」由 has_point 另报，调用方据此给 null。
// 两处判据一致由 internal/handler/address_service_area_test.go 拿试算结果逐条对照钉住。
//
// 门店不在（不存在、已软删、别家店的被 RLS 滤掉）时 CROSS JOIN 出零行，与「地址簿是空的」
// 同形 —— 所以调用方先用 StoreExists 问过门店，再来这里。顺序与 ListUserAddresses 逐字一致。
func (q *Queries) ListUserAddressesForStore(ctx context.Context, arg ListUserAddressesForStoreParams) ([]ListUserAddressesForStoreRow, error) {
	rows, err := q.db.Query(ctx, listUserAddressesForStore, arg.UserID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAddressesForStoreRow
	for rows.Next() {
		var i ListUserAddressesForStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceiverName,
			&i.Phone,
			&i.Province,
			&i.City,
			&i.District,
			&i.Street,
			&i.Detail,
			&i.RegionCode,
			&i.PostalCode,
			&i.Tag,
			&i.IsDefault,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasPoint,
			&i.Serves,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDefaultAddress = `-- name: MarkDefaultAddress :one
UPDATE user_addresses
   SET is_default = TRUE
 WHERE id = $1
   AND user_id = $2
   AND deleted_at IS NULL
RETURNING id, receiver_name, phone, province, city, district, street, detail,
          region_code, postal_code, tag, is_default, lat, lng, created_at, updated_at
`

type MarkDefaultAddressParams struct {
	ID     int64
	UserID int64
}

type MarkDefaultAddressRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// 把一条设为默认。查不到（含属于别人、已软删）即 ErrNoRows，服务层翻成 404。
func (q *Queries) MarkDefaultAddress(ctx context.Context, arg MarkDefaultAddressParams) (MarkDefaultAddressRow, error) {
	row := q.db.QueryRow(ctx, markDefaultAddress, arg.ID, arg.UserID)
	var i MarkDefaultAddressRow
	err := row.Scan(
		&i.ID,
		&i.ReceiverName,
		&i.Phone,
		&i.Province,
		&i.City,
		&i.District,
		&i.Street,
		&i.Detail,
		&i.RegionCode,
		&i.PostalCode,
		&i.Tag,
		&i.IsDefault,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUserAddress = `-- name: SoftDeleteUserAddress :one
UPDATE user_addresses
   SET deleted_at = now(),
       is_default = FALSE
 WHERE id = $1
   AND user_id = $2
   AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteUserAddressParams struct {
	ID     int64
	UserID int64
}

// 软删（契约：写 deleted_at）。地址与订单是快照关系，删它不影响任何历史订单。
//
// 顺手把 is_default 置回假：部分唯一索引本来就不看已软删的行，这一列留着
// 不会撞任何东西；置假是为了让「这一行曾是默认」不被将来某条忘了写
// deleted_at IS NULL 的查询读成「这是默认地址」。
func (q *Queries) SoftDeleteUserAddress(ctx context.Context, arg SoftDeleteUserAddressParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteUserAddress, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE user_addresses
   SET receiver_name = $1,
       phone         = $2,
       province      = $3,
       city          = $4,
       district      = $5,
       street        = $6,
       detail        = $7,
       region_code   = $8,
       postal_code   = $9,
       tag           = $10,
       lat           = $11,
       lng           = $12
 WHERE id = $13
   AND user_id = $14
   AND deleted_at IS NULL
RETURNING id, receiver_name, phone, province, city, district, street, detail,
          region_code, postal_code, tag, is_default, lat, lng, created_at, updated_at
`

type UpdateUserAddressParams struct {
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	Lat          *float64
	Lng          *float64
	ID           int64
	UserID       int64
}

type UpdateUserAddressRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	Lat          *float64
	Lng          *float64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// 整体替换（PUT）。**is_default 不在 SET 里**：契约说 is_default 只在新增时有效，
// 切换默认走专用接口 —— 让这条语句根本写不了那一列，比在服务层记得不传更硬。
func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UpdateUserAddressRow, error) {
	row := q.db.QueryRow(ctx, updateUserAddress,
		arg.ReceiverName,
		arg.Phone,
		arg.Province,
		arg.City,
		arg.District,
		arg.Street,
		arg.Detail,
		arg.RegionCode,
		arg.PostalCode,
		arg.Tag,
		arg.Lat,
		arg.Lng,
		arg.ID,
		arg.UserID,
	)
	var i UpdateUserAddressRow
	err := row.Scan(
		&i.ID,
		&i.ReceiverName,
		&i.Phone,
		&i.Province,
		&i.City,
		&i.District,
		&i.Street,
		&i.Detail,
		&i.RegionCode,
		&i.PostalCode,
		&i.Tag,
		&i.IsDefault,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
