// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountOrders = `-- name: AdminCountOrders :one
SELECT count(*)
  FROM orders o
 WHERE o.status <> 0
   AND ($1::smallint IS NULL OR o.status = $1::smallint)
   AND ($2::bigint IS NULL OR o.store_id = $2::bigint)
   AND ($3::timestamptz IS NULL OR o.created_at >= $3::timestamptz)
   AND ($4::timestamptz IS NULL OR o.created_at < $4::timestamptz)
   AND ($5::text IS NULL OR o.order_no = $5::text)
   AND ($6::text IS NULL
        OR o.receiver_snapshot->>'phone' = $6::text
        OR o.user_id = (SELECT u.id FROM users u
                         WHERE u.phone = $6::text AND u.deleted_at IS NULL))
   AND ($7::bigint[] IS NULL
        OR o.store_id IN (SELECT st.id FROM stores st
                           WHERE st.region_id = ANY($7::bigint[])))
   AND ($8::bigint[] IS NULL
        OR o.store_id = ANY($8::bigint[]))
`

type AdminCountOrdersParams struct {
	Status        *int16
	StoreID       *int64
	CreatedFrom   pgtype.Timestamptz
	CreatedTo     pgtype.Timestamptz
	OrderNo       *string
	Phone         *string
	OnlyRegionIds []int64
	OnlyStoreIds  []int64
}

// 条件必须与 AdminListOrders 逐字一致。
func (q *Queries) AdminCountOrders(ctx context.Context, arg AdminCountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOrders,
		arg.Status,
		arg.StoreID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.OrderNo,
		arg.Phone,
		arg.OnlyRegionIds,
		arg.OnlyStoreIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountRefunds = `-- name: AdminCountRefunds :one
SELECT count(*)
  FROM refunds r
  JOIN orders o ON o.id = r.order_id
 WHERE ($1::smallint IS NULL OR r.status = $1::smallint)
   AND ($2::bigint IS NULL OR o.store_id = $2::bigint)
   AND ($3::timestamptz IS NULL OR r.created_at >= $3::timestamptz)
   AND ($4::timestamptz IS NULL OR r.created_at < $4::timestamptz)
   AND ($5::bigint[] IS NULL
        OR o.store_id IN (SELECT st.id FROM stores st
                           WHERE st.region_id = ANY($5::bigint[])))
   AND ($6::bigint[] IS NULL
        OR o.store_id = ANY($6::bigint[]))
`

type AdminCountRefundsParams struct {
	Status        *int16
	StoreID       *int64
	CreatedFrom   pgtype.Timestamptz
	CreatedTo     pgtype.Timestamptz
	OnlyRegionIds []int64
	OnlyStoreIds  []int64
}

// 条件必须与 AdminListRefunds 逐字一致。
func (q *Queries) AdminCountRefunds(ctx context.Context, arg AdminCountRefundsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountRefunds,
		arg.Status,
		arg.StoreID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.OnlyRegionIds,
		arg.OnlyStoreIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetOrderByNo = `-- name: AdminGetOrderByNo :one
SELECT o.id, o.order_no, o.user_id, o.store_id, o.region_id, o.status,
       o.goods_amount_cents, o.freight_cents, o.freight_discount_cents,
       o.discount_cents, o.payable_cents,
       o.paid_cents, o.refunded_cents, o.refund_status, o.expire_at, o.paid_at,
       o.shipped_at, o.finished_at, o.created_at, o.user_coupon_id, o.coupon_name,
       o.promotion_discount_cents, o.promotions,
       o.receiver_snapshot, o.store_snapshot,
       EXISTS (SELECT 1 FROM refunds r
                WHERE r.order_id = o.id AND r.status IN (10, 20, 30)) AS has_open_refund
  FROM orders o
 WHERE o.order_no = $1
   AND o.status <> 0
`

type AdminGetOrderByNoRow struct {
	ID                     int64
	OrderNo                string
	UserID                 int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
	ReceiverSnapshot       []byte
	StoreSnapshot          []byte
	HasOpenRefund          bool
}

// 后台按单号取一笔订单（没有买家过滤；租户由 RLS 管，门店范围由 service 判）。
// 列与 AdminListOrders 逐一对齐，行类型可以直接互转。
func (q *Queries) AdminGetOrderByNo(ctx context.Context, orderNo string) (AdminGetOrderByNoRow, error) {
	row := q.db.QueryRow(ctx, adminGetOrderByNo, orderNo)
	var i AdminGetOrderByNoRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UserCouponID,
		&i.CouponName,
		&i.PromotionDiscountCents,
		&i.Promotions,
		&i.ReceiverSnapshot,
		&i.StoreSnapshot,
		&i.HasOpenRefund,
	)
	return i, err
}

const adminGetRefundByNo = `-- name: AdminGetRefundByNo :one
SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, p.payment_no, r.user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at,
       o.status AS order_status, o.shipped_at AS order_shipped_at, o.store_snapshot,
       r.audited_by, sa.name AS audited_by_name,
       r.received_at, r.received_by, sr.name AS received_by_name
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  JOIN payments p ON p.id = r.payment_id
  LEFT JOIN staff sa ON sa.id = r.audited_by
  LEFT JOIN staff sr ON sr.id = r.received_by
 WHERE r.refund_no = $1
`

type AdminGetRefundByNoRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
	OrderStatus       int16
	OrderShippedAt    pgtype.Timestamptz
	StoreSnapshot     []byte
	AuditedBy         *int64
	AuditedByName     *string
	ReceivedAt        pgtype.Timestamptz
	ReceivedBy        *int64
	ReceivedByName    *string
}

// 后台按编号取一张退款单。列与 AdminListRefunds 逐一对齐。
func (q *Queries) AdminGetRefundByNo(ctx context.Context, refundNo string) (AdminGetRefundByNoRow, error) {
	row := q.db.QueryRow(ctx, adminGetRefundByNo, refundNo)
	var i AdminGetRefundByNoRow
	err := row.Scan(
		&i.ID,
		&i.RefundNo,
		&i.OrderID,
		&i.OrderNo,
		&i.StoreID,
		&i.PaymentNo,
		&i.UserID,
		&i.RefundType,
		&i.ReasonCode,
		&i.ReasonText,
		&i.EvidenceUrls,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.AmountCents,
		&i.Status,
		&i.Channel,
		&i.ChannelRefundID,
		&i.RejectReason,
		&i.AuditedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCarrierCode,
		&i.ReturnTrackingNo,
		&i.ReturnSubmittedAt,
		&i.OrderStatus,
		&i.OrderShippedAt,
		&i.StoreSnapshot,
		&i.AuditedBy,
		&i.AuditedByName,
		&i.ReceivedAt,
		&i.ReceivedBy,
		&i.ReceivedByName,
	)
	return i, err
}

const adminListOrderRefunds = `-- name: AdminListOrderRefunds :many
SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, p.payment_no, r.user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at,
       o.status AS order_status, o.shipped_at AS order_shipped_at, o.store_snapshot,
       r.audited_by, sa.name AS audited_by_name,
       r.received_at, r.received_by, sr.name AS received_by_name
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  JOIN payments p ON p.id = r.payment_id
  LEFT JOIN staff sa ON sa.id = r.audited_by
  LEFT JOIN staff sr ON sr.id = r.received_by
 WHERE r.order_id = $1
 ORDER BY r.created_at DESC, r.id DESC
`

type AdminListOrderRefundsRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
	OrderStatus       int16
	OrderShippedAt    pgtype.Timestamptz
	StoreSnapshot     []byte
	AuditedBy         *int64
	AuditedByName     *string
	ReceivedAt        pgtype.Timestamptz
	ReceivedBy        *int64
	ReceivedByName    *string
}

// 一个订单的全部退款单（后台视角，带审核记录），按申请时间倒序。
func (q *Queries) AdminListOrderRefunds(ctx context.Context, orderID int64) ([]AdminListOrderRefundsRow, error) {
	rows, err := q.db.Query(ctx, adminListOrderRefunds, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrderRefundsRow
	for rows.Next() {
		var i AdminListOrderRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.RefundNo,
			&i.OrderID,
			&i.OrderNo,
			&i.StoreID,
			&i.PaymentNo,
			&i.UserID,
			&i.RefundType,
			&i.ReasonCode,
			&i.ReasonText,
			&i.EvidenceUrls,
			&i.GoodsAmountCents,
			&i.FreightCents,
			&i.AmountCents,
			&i.Status,
			&i.Channel,
			&i.ChannelRefundID,
			&i.RejectReason,
			&i.AuditedAt,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCarrierCode,
			&i.ReturnTrackingNo,
			&i.ReturnSubmittedAt,
			&i.OrderStatus,
			&i.OrderShippedAt,
			&i.StoreSnapshot,
			&i.AuditedBy,
			&i.AuditedByName,
			&i.ReceivedAt,
			&i.ReceivedBy,
			&i.ReceivedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrders = `-- name: AdminListOrders :many

SELECT o.id, o.order_no, o.user_id, o.store_id, o.region_id, o.status,
       o.goods_amount_cents, o.freight_cents, o.freight_discount_cents,
       o.discount_cents, o.payable_cents,
       o.paid_cents, o.refunded_cents, o.refund_status, o.expire_at, o.paid_at,
       o.shipped_at, o.finished_at, o.created_at, o.user_coupon_id, o.coupon_name,
       o.promotion_discount_cents, o.promotions,
       o.receiver_snapshot, o.store_snapshot,
       EXISTS (SELECT 1 FROM refunds r
                WHERE r.order_id = o.id AND r.status IN (10, 20, 30)) AS has_open_refund
  FROM orders o
 WHERE o.status <> 0
   AND ($1::smallint IS NULL OR o.status = $1::smallint)
   AND ($2::bigint IS NULL OR o.store_id = $2::bigint)
   AND ($3::timestamptz IS NULL OR o.created_at >= $3::timestamptz)
   AND ($4::timestamptz IS NULL OR o.created_at < $4::timestamptz)
   AND ($5::text IS NULL OR o.order_no = $5::text)
   AND ($6::text IS NULL
        OR o.receiver_snapshot->>'phone' = $6::text
        OR o.user_id = (SELECT u.id FROM users u
                         WHERE u.phone = $6::text AND u.deleted_at IS NULL))
   AND ($7::bigint[] IS NULL
        OR o.store_id IN (SELECT st.id FROM stores st
                           WHERE st.region_id = ANY($7::bigint[])))
   AND ($8::bigint[] IS NULL
        OR o.store_id = ANY($8::bigint[]))
 ORDER BY o.created_at DESC, o.id DESC
 LIMIT $10 OFFSET $9
`

type AdminListOrdersParams struct {
	Status        *int16
	StoreID       *int64
	CreatedFrom   pgtype.Timestamptz
	CreatedTo     pgtype.Timestamptz
	OrderNo       *string
	Phone         *string
	OnlyRegionIds []int64
	OnlyStoreIds  []int64
	PageOffset    int32
	PageLimit     int32
}

type AdminListOrdersRow struct {
	ID                     int64
	OrderNo                string
	UserID                 int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
	ReceiverSnapshot       []byte
	StoreSnapshot          []byte
	HasOpenRefund          bool
}

// 后台订单与退款单的读：GET /admin/orders、GET /admin/orders/{order_no}、
// GET /admin/refunds、GET /admin/refunds/{refund_no}（迁移 00035）。
//
// 租户由 RLS 过滤，这里一处都不写（check_query_tenancy.py）。
// 注释里不许有反引号，理由见 db/queries/inventories.sql 的第三条说明。
//
// ### 同一租户内的范围过滤
//
// only_region_ids / only_store_ids 为 NULL 即不限（管理员、操作员），
// 空数组即一个都不给（范围被清空了的大区管理员拿到空列表，而不是全部）。
// 它们是**同一租户内的权限过滤**，不是租户过滤；值由 service/authz.go 的
// orderListScope 给出，判据与发货、审核用的 authorizeOrderStore 是同一个：
//
//	大区看门店**此刻**所属的大区（stores.region_id），含已软删的门店 ——
//	店关了，它名下没发完的货、没退完的钱仍然要有人处理；
//	不看订单上冗余的 region_id（那是下单时的大区，定价用的）。
//
// ### 列表与计数的谓词必须逐字一致
//
// AdminCountOrders 与 AdminListOrders、AdminCountRefunds 与 AdminListRefunds
// 各自共用同一段 WHERE。两者分叉的症状是「total = 21 但第二页是空的」。
// 后台订单列表，一页。has_open_refund 是现查的（有没有 10 / 20 / 30 的退款单），
// 走 idx_refunds_order。
//
// phone 同时认收货人手机号与买家账号手机号：后者先经 uk_users_phone 换成 user_id
// （标量子查询；那条唯一索引保证本租户内至多一行），再走 idx_orders_user。
func (q *Queries) AdminListOrders(ctx context.Context, arg AdminListOrdersParams) ([]AdminListOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListOrders,
		arg.Status,
		arg.StoreID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.OrderNo,
		arg.Phone,
		arg.OnlyRegionIds,
		arg.OnlyStoreIds,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrdersRow
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.StoreID,
			&i.RegionID,
			&i.Status,
			&i.GoodsAmountCents,
			&i.FreightCents,
			&i.FreightDiscountCents,
			&i.DiscountCents,
			&i.PayableCents,
			&i.PaidCents,
			&i.RefundedCents,
			&i.RefundStatus,
			&i.ExpireAt,
			&i.PaidAt,
			&i.ShippedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UserCouponID,
			&i.CouponName,
			&i.PromotionDiscountCents,
			&i.Promotions,
			&i.ReceiverSnapshot,
			&i.StoreSnapshot,
			&i.HasOpenRefund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRefunds = `-- name: AdminListRefunds :many
SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, p.payment_no, r.user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at,
       o.status AS order_status, o.shipped_at AS order_shipped_at, o.store_snapshot,
       r.audited_by, sa.name AS audited_by_name,
       r.received_at, r.received_by, sr.name AS received_by_name
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  JOIN payments p ON p.id = r.payment_id
  LEFT JOIN staff sa ON sa.id = r.audited_by
  LEFT JOIN staff sr ON sr.id = r.received_by
 WHERE ($1::smallint IS NULL OR r.status = $1::smallint)
   AND ($2::bigint IS NULL OR o.store_id = $2::bigint)
   AND ($3::timestamptz IS NULL OR r.created_at >= $3::timestamptz)
   AND ($4::timestamptz IS NULL OR r.created_at < $4::timestamptz)
   AND ($5::bigint[] IS NULL
        OR o.store_id IN (SELECT st.id FROM stores st
                           WHERE st.region_id = ANY($5::bigint[])))
   AND ($6::bigint[] IS NULL
        OR o.store_id = ANY($6::bigint[]))
 ORDER BY r.created_at DESC, r.id DESC
 LIMIT $8 OFFSET $7
`

type AdminListRefundsParams struct {
	Status        *int16
	StoreID       *int64
	CreatedFrom   pgtype.Timestamptz
	CreatedTo     pgtype.Timestamptz
	OnlyRegionIds []int64
	OnlyStoreIds  []int64
	PageOffset    int32
	PageLimit     int32
}

type AdminListRefundsRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
	OrderStatus       int16
	OrderShippedAt    pgtype.Timestamptz
	StoreSnapshot     []byte
	AuditedBy         *int64
	AuditedByName     *string
	ReceivedAt        pgtype.Timestamptz
	ReceivedBy        *int64
	ReceivedByName    *string
}

// 后台退款单列表，一页。门店、订单状态、门店快照从所属订单带出来；
// 审核人与收货人的名字 LEFT JOIN staff —— 平台级员工在租户作用域里读不到（RLS），
// 那时只剩 id。
func (q *Queries) AdminListRefunds(ctx context.Context, arg AdminListRefundsParams) ([]AdminListRefundsRow, error) {
	rows, err := q.db.Query(ctx, adminListRefunds,
		arg.Status,
		arg.StoreID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.OnlyRegionIds,
		arg.OnlyStoreIds,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListRefundsRow
	for rows.Next() {
		var i AdminListRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.RefundNo,
			&i.OrderID,
			&i.OrderNo,
			&i.StoreID,
			&i.PaymentNo,
			&i.UserID,
			&i.RefundType,
			&i.ReasonCode,
			&i.ReasonText,
			&i.EvidenceUrls,
			&i.GoodsAmountCents,
			&i.FreightCents,
			&i.AmountCents,
			&i.Status,
			&i.Channel,
			&i.ChannelRefundID,
			&i.RejectReason,
			&i.AuditedAt,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCarrierCode,
			&i.ReturnTrackingNo,
			&i.ReturnSubmittedAt,
			&i.OrderStatus,
			&i.OrderShippedAt,
			&i.StoreSnapshot,
			&i.AuditedBy,
			&i.AuditedByName,
			&i.ReceivedAt,
			&i.ReceivedBy,
			&i.ReceivedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeRegionAnyState = `-- name: StoreRegionAnyState :one
SELECT st.region_id FROM stores st WHERE st.id = $1
`

// 这家门店此刻所属的大区，**含已软删的门店**。给订单与售后的判权用
// （authorizeOrderStore）：店关了，它名下的单仍然归那个大区的人处理。
// 与 StoreExists 分开：那一条给「路径里指名一家门店」的接口，软删的就是 404。
func (q *Queries) StoreRegionAnyState(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, storeRegionAnyState, id)
	var region_id int64
	err := row.Scan(&region_id)
	return region_id, err
}
