// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_outcomes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentRecentOutcomes = `-- name: AgentRecentOutcomes :many
SELECT p.id, p.kind, p.title, p.outcome, p.outcome_at
  FROM agent_proposals p
 WHERE p.agent_staff_id = $1 AND p.outcome_at IS NOT NULL AND p.outcome_at >= $2
 ORDER BY p.outcome_at DESC
 LIMIT 50
`

type AgentRecentOutcomesParams struct {
	AgentStaffID int64
	Since        pgtype.Timestamptz
}

type AgentRecentOutcomesRow struct {
	ID        int64
	Kind      string
	Title     string
	Outcome   []byte
	OutcomeAt pgtype.Timestamptz
}

// 成绩单的明细：近 since 以来已经量过效果的提案，新的在前。
func (q *Queries) AgentRecentOutcomes(ctx context.Context, arg AgentRecentOutcomesParams) ([]AgentRecentOutcomesRow, error) {
	rows, err := q.db.Query(ctx, agentRecentOutcomes, arg.AgentStaffID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRecentOutcomesRow
	for rows.Next() {
		var i AgentRecentOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Outcome,
			&i.OutcomeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentScorecardByKind = `-- name: AgentScorecardByKind :many
SELECT p.kind,
       count(*)::bigint                                                  AS proposed,
       count(*) FILTER (WHERE p.status IN (20, 40))::bigint               AS approved,
       count(*) FILTER (WHERE p.status = 20)::bigint                      AS executed,
       count(*) FILTER (WHERE p.status = 40)::bigint                      AS failed,
       count(*) FILTER (WHERE p.status = 30)::bigint                      AS rejected,
       count(*) FILTER (WHERE p.status = 50)::bigint                      AS expired,
       count(*) FILTER (WHERE p.status IN (10, 15))::bigint               AS open,
       count(*) FILTER (WHERE p.outcome->>'verdict' = 'positive')::bigint AS positive,
       count(*) FILTER (WHERE p.outcome->>'verdict' = 'neutral')::bigint  AS neutral,
       count(*) FILTER (WHERE p.outcome->>'verdict' = 'negative')::bigint AS negative
  FROM agent_proposals p
 WHERE p.agent_staff_id = $1 AND p.created_at >= $2
 GROUP BY p.kind
 ORDER BY p.kind
`

type AgentScorecardByKindParams struct {
	AgentStaffID int64
	Since        pgtype.Timestamptz
}

type AgentScorecardByKindRow struct {
	Kind     string
	Proposed int64
	Approved int64
	Executed int64
	Failed   int64
	Rejected int64
	Expired  int64
	Open     int64
	Positive int64
	Neutral  int64
	Negative int64
}

// 成绩单：这名 AI 员工近 since 以来按种类的提案数、各状态数、verdict 分布。
func (q *Queries) AgentScorecardByKind(ctx context.Context, arg AgentScorecardByKindParams) ([]AgentScorecardByKindRow, error) {
	rows, err := q.db.Query(ctx, agentScorecardByKind, arg.AgentStaffID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentScorecardByKindRow
	for rows.Next() {
		var i AgentScorecardByKindRow
		if err := rows.Scan(
			&i.Kind,
			&i.Proposed,
			&i.Approved,
			&i.Executed,
			&i.Failed,
			&i.Rejected,
			&i.Expired,
			&i.Open,
			&i.Positive,
			&i.Neutral,
			&i.Negative,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimAgentProposalAuto = `-- name: ClaimAgentProposalAuto :one
UPDATE agent_proposals
   SET status = 15, decided_at = now(), auto_approved = TRUE
 WHERE id = $1 AND status = 10 AND expires_at > now()
RETURNING id
`

// 按策略自动执行：10 → 15，decided_by 为空、auto_approved = true。
func (q *Queries) ClaimAgentProposalAuto(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, claimAgentProposalAuto, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const countAutoApprovedSince = `-- name: CountAutoApprovedSince :one
SELECT count(*) FROM agent_proposals
 WHERE agent_staff_id = $1 AND kind = $2 AND auto_approved AND decided_at >= $3
`

type CountAutoApprovedSinceParams struct {
	AgentStaffID int64
	Kind         string
	DecidedAt    pgtype.Timestamptz
}

func (q *Queries) CountAutoApprovedSince(ctx context.Context, arg CountAutoApprovedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAutoApprovedSince, arg.AgentStaffID, arg.Kind, arg.DecidedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const couponTemplateUsage = `-- name: CouponTemplateUsage :one
SELECT count(*)::bigint AS claimed,
       count(*) FILTER (WHERE uc.status IN (2, 3))::bigint AS used
  FROM user_coupons uc
 WHERE uc.template_id = $1
`

type CouponTemplateUsageRow struct {
	Claimed int64
	Used    int64
}

// 一张券模板：领了多少、用了多少（status 3 已使用；2 锁定是下单进行中，也算用了；4 过期不算）。
func (q *Queries) CouponTemplateUsage(ctx context.Context, templateID int64) (CouponTemplateUsageRow, error) {
	row := q.db.QueryRow(ctx, couponTemplateUsage, templateID)
	var i CouponTemplateUsageRow
	err := row.Scan(&i.Claimed, &i.Used)
	return i, err
}

const deferAgentProposalOutcome = `-- name: DeferAgentProposalOutcome :exec
UPDATE agent_proposals SET outcome_due_at = $1
 WHERE id = $2 AND status = 20 AND outcome_at IS NULL
`

type DeferAgentProposalOutcomeParams struct {
	DueAt pgtype.Timestamptz
	ID    int64
}

// 到点了但统计窗口还没走完（outcome_due_at 被提前了）：推迟到窗口关闭，不算半截数据。
func (q *Queries) DeferAgentProposalOutcome(ctx context.Context, arg DeferAgentProposalOutcomeParams) error {
	_, err := q.db.Exec(ctx, deferAgentProposalOutcome, arg.DueAt, arg.ID)
	return err
}

const dueAgentProposalOutcomes = `-- name: DueAgentProposalOutcomes :many
SELECT id, kind, store_id, sku_id, payload, executed_at
  FROM agent_proposals
 WHERE status = 20 AND outcome_at IS NULL AND outcome_due_at IS NOT NULL AND outcome_due_at <= now()
 ORDER BY outcome_due_at
 LIMIT 100
`

type DueAgentProposalOutcomesRow struct {
	ID         int64
	Kind       string
	StoreID    *int64
	SkuID      *int64
	Payload    []byte
	ExecutedAt pgtype.Timestamptz
}

func (q *Queries) DueAgentProposalOutcomes(ctx context.Context) ([]DueAgentProposalOutcomesRow, error) {
	rows, err := q.db.Query(ctx, dueAgentProposalOutcomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueAgentProposalOutcomesRow
	for rows.Next() {
		var i DueAgentProposalOutcomesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.StoreID,
			&i.SkuID,
			&i.Payload,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentAutoPolicy = `-- name: GetAgentAutoPolicy :one
SELECT agent_staff_id, kind, enabled, max_units, min_discount_rate, max_discount_cents, daily_limit, updated_by, updated_at
  FROM agent_auto_policies
 WHERE agent_staff_id = $1 AND kind = $2
`

type GetAgentAutoPolicyParams struct {
	AgentStaffID int64
	Kind         string
}

type GetAgentAutoPolicyRow struct {
	AgentStaffID     int64
	Kind             string
	Enabled          bool
	MaxUnits         int32
	MinDiscountRate  int16
	MaxDiscountCents int64
	DailyLimit       int32
	UpdatedBy        *int64
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAgentAutoPolicy(ctx context.Context, arg GetAgentAutoPolicyParams) (GetAgentAutoPolicyRow, error) {
	row := q.db.QueryRow(ctx, getAgentAutoPolicy, arg.AgentStaffID, arg.Kind)
	var i GetAgentAutoPolicyRow
	err := row.Scan(
		&i.AgentStaffID,
		&i.Kind,
		&i.Enabled,
		&i.MaxUnits,
		&i.MinDiscountRate,
		&i.MaxDiscountCents,
		&i.DailyLimit,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicAILog = `-- name: GetPublicAILog :one

SELECT public_ai_log FROM shop_preferences LIMIT 1
`

// ===========================================================================
// 公开的 AI 经营日志（00132）
// ===========================================================================
func (q *Queries) GetPublicAILog(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, getPublicAILog)
	var public_ai_log bool
	err := row.Scan(&public_ai_log)
	return public_ai_log, err
}

const listAgentAutoPolicies = `-- name: ListAgentAutoPolicies :many

SELECT agent_staff_id, kind, enabled, max_units, min_discount_rate, max_discount_cents, daily_limit, updated_by, updated_at
  FROM agent_auto_policies
 WHERE agent_staff_id = $1
 ORDER BY kind
`

type ListAgentAutoPoliciesRow struct {
	AgentStaffID     int64
	Kind             string
	Enabled          bool
	MaxUnits         int32
	MinDiscountRate  int16
	MaxDiscountCents int64
	DailyLimit       int32
	UpdatedBy        *int64
	UpdatedAt        pgtype.Timestamptz
}

// ===========================================================================
// 自动执行策略（00130）
// ===========================================================================
func (q *Queries) ListAgentAutoPolicies(ctx context.Context, agentStaffID int64) ([]ListAgentAutoPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listAgentAutoPolicies, agentStaffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentAutoPoliciesRow
	for rows.Next() {
		var i ListAgentAutoPoliciesRow
		if err := rows.Scan(
			&i.AgentStaffID,
			&i.Kind,
			&i.Enabled,
			&i.MaxUnits,
			&i.MinDiscountRate,
			&i.MaxDiscountCents,
			&i.DailyLimit,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productUnitsSoldBetween = `-- name: ProductUnitsSoldBetween :one
SELECT COALESCE(sum(oi.quantity), 0)::bigint AS qty
  FROM order_items oi
  JOIN orders o ON o.id = oi.order_id
  JOIN skus s ON s.id = oi.sku_id
 WHERE s.product_id = $1
   AND o.status IN (20, 30, 40, 50)
   AND o.paid_at >= $2 AND o.paid_at < $3
`

type ProductUnitsSoldBetweenParams struct {
	ProductID int64
	FromAt    pgtype.Timestamptz
	ToAt      pgtype.Timestamptz
}

func (q *Queries) ProductUnitsSoldBetween(ctx context.Context, arg ProductUnitsSoldBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, productUnitsSoldBetween, arg.ProductID, arg.FromAt, arg.ToAt)
	var qty int64
	err := row.Scan(&qty)
	return qty, err
}

const publicAILogProposals = `-- name: PublicAILogProposals :many
SELECT p.id, p.kind, p.title, p.status, p.auto_approved, COALESCE(p.outcome->>'verdict', '')::text AS verdict, p.created_at, p.decided_at,
       a.name AS agent_name
  FROM agent_proposals p
  JOIN staff a ON a.id = p.agent_staff_id
 ORDER BY p.created_at DESC
 LIMIT 30
`

type PublicAILogProposalsRow struct {
	ID           int64
	Kind         string
	Title        string
	Status       int16
	AutoApproved bool
	Verdict      string
	CreatedAt    pgtype.Timestamptz
	DecidedAt    pgtype.Timestamptz
	AgentName    string
}

// 最近的提案（全部 AI 员工）：公开页只给种类、标题、状态、是否自动执行、复盘结论与时间 —— 不给证据全文与执行参数。
func (q *Queries) PublicAILogProposals(ctx context.Context) ([]PublicAILogProposalsRow, error) {
	rows, err := q.db.Query(ctx, publicAILogProposals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicAILogProposalsRow
	for rows.Next() {
		var i PublicAILogProposalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Status,
			&i.AutoApproved,
			&i.Verdict,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicAILogSummary = `-- name: PublicAILogSummary :one
SELECT count(*)::bigint                                                   AS proposed,
       count(*) FILTER (WHERE status = 20)::bigint                        AS executed,
       count(*) FILTER (WHERE status = 20 AND auto_approved)::bigint      AS auto_executed,
       count(*) FILTER (WHERE status = 30)::bigint                        AS rejected,
       count(*) FILTER (WHERE outcome->>'verdict' = 'positive')::bigint   AS positive,
       count(*) FILTER (WHERE outcome->>'verdict' = 'negative')::bigint   AS negative
  FROM agent_proposals
 WHERE created_at >= now() - interval '30 days'
`

type PublicAILogSummaryRow struct {
	Proposed     int64
	Executed     int64
	AutoExecuted int64
	Rejected     int64
	Positive     int64
	Negative     int64
}

// 近 30 天的总数。
func (q *Queries) PublicAILogSummary(ctx context.Context) (PublicAILogSummaryRow, error) {
	row := q.db.QueryRow(ctx, publicAILogSummary)
	var i PublicAILogSummaryRow
	err := row.Scan(
		&i.Proposed,
		&i.Executed,
		&i.AutoExecuted,
		&i.Rejected,
		&i.Positive,
		&i.Negative,
	)
	return i, err
}

const sKUUnitsSoldBetween = `-- name: SKUUnitsSoldBetween :one
SELECT COALESCE(sum(oi.quantity), 0)::bigint AS qty,
       COALESCE(sum(oi.amount_cents - oi.discount_cents), 0)::bigint AS amount_cents
  FROM order_items oi
  JOIN orders o ON o.id = oi.order_id
 WHERE oi.sku_id = ANY($1::bigint[])
   AND ($2::bigint IS NULL OR o.store_id = $2::bigint)
   AND o.status IN (20, 30, 40, 50)
   AND o.paid_at >= $3 AND o.paid_at < $4
`

type SKUUnitsSoldBetweenParams struct {
	SkuIds  []int64
	StoreID *int64
	FromAt  pgtype.Timestamptz
	ToAt    pgtype.Timestamptz
}

type SKUUnitsSoldBetweenRow struct {
	Qty         int64
	AmountCents int64
}

// 一组 SKU 在 [from, to) 内卖出的件数与金额（分）。store_id 为空 = 全部门店。
func (q *Queries) SKUUnitsSoldBetween(ctx context.Context, arg SKUUnitsSoldBetweenParams) (SKUUnitsSoldBetweenRow, error) {
	row := q.db.QueryRow(ctx, sKUUnitsSoldBetween,
		arg.SkuIds,
		arg.StoreID,
		arg.FromAt,
		arg.ToAt,
	)
	var i SKUUnitsSoldBetweenRow
	err := row.Scan(&i.Qty, &i.AmountCents)
	return i, err
}

const saveAgentProposalOutcome = `-- name: SaveAgentProposalOutcome :exec
UPDATE agent_proposals SET outcome = $1, outcome_at = now()
 WHERE id = $2 AND status = 20 AND outcome_at IS NULL
`

type SaveAgentProposalOutcomeParams struct {
	Outcome []byte
	ID      int64
}

func (q *Queries) SaveAgentProposalOutcome(ctx context.Context, arg SaveAgentProposalOutcomeParams) error {
	_, err := q.db.Exec(ctx, saveAgentProposalOutcome, arg.Outcome, arg.ID)
	return err
}

const setAgentProposalExecuted = `-- name: SetAgentProposalExecuted :exec

UPDATE agent_proposals
   SET executed_at = now(), outcome_due_at = $1, outcome = $2,
       outcome_at = CASE WHEN $2::jsonb IS NULL THEN NULL ELSE now() END
 WHERE id = $3 AND status = 20
`

type SetAgentProposalExecutedParams struct {
	OutcomeDueAt pgtype.Timestamptz
	Outcome      []byte
	ID           int64
}

// 提案复盘（00122，service/agent_proposal_outcome.go）与成绩单。一个 merchant_id 都没有：租户由 RLS 过滤。
// 「卖出」与补货计算同一个口径（restock.sql 的 StoreSKUSales）：已支付 / 已发货 / 已完成 / 售后中的单都算。
func (q *Queries) SetAgentProposalExecuted(ctx context.Context, arg SetAgentProposalExecutedParams) error {
	_, err := q.db.Exec(ctx, setAgentProposalExecuted, arg.OutcomeDueAt, arg.Outcome, arg.ID)
	return err
}

const setPublicAILog = `-- name: SetPublicAILog :exec
INSERT INTO shop_preferences (public_ai_log) VALUES ($1)
ON CONFLICT ON CONSTRAINT shop_preferences_pkey DO UPDATE SET public_ai_log = EXCLUDED.public_ai_log
`

// 没有 shop_preferences 那一行时建一行（其余列取默认值）。
func (q *Queries) SetPublicAILog(ctx context.Context, enabled bool) error {
	_, err := q.db.Exec(ctx, setPublicAILog, enabled)
	return err
}

const upsertAgentAutoPolicy = `-- name: UpsertAgentAutoPolicy :exec
INSERT INTO agent_auto_policies (agent_staff_id, kind, enabled, max_units, min_discount_rate, max_discount_cents,
                                 daily_limit, updated_by)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
ON CONFLICT ON CONSTRAINT agent_auto_policies_pkey DO UPDATE
   SET enabled = EXCLUDED.enabled, max_units = EXCLUDED.max_units, min_discount_rate = EXCLUDED.min_discount_rate,
       max_discount_cents = EXCLUDED.max_discount_cents, daily_limit = EXCLUDED.daily_limit,
       updated_by = EXCLUDED.updated_by
`

type UpsertAgentAutoPolicyParams struct {
	AgentStaffID     int64
	Kind             string
	Enabled          bool
	MaxUnits         int32
	MinDiscountRate  int16
	MaxDiscountCents int64
	DailyLimit       int32
	UpdatedBy        *int64
}

func (q *Queries) UpsertAgentAutoPolicy(ctx context.Context, arg UpsertAgentAutoPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertAgentAutoPolicy,
		arg.AgentStaffID,
		arg.Kind,
		arg.Enabled,
		arg.MaxUnits,
		arg.MinDiscountRate,
		arg.MaxDiscountCents,
		arg.DailyLimit,
		arg.UpdatedBy,
	)
	return err
}
