// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package db

import (
	"context"
)

const addCartLine = `-- name: AddCartLine :one
INSERT INTO cart_items (cart_id, sku_id, product_id, quantity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, sku_id) DO UPDATE
    SET quantity = cart_items.quantity + EXCLUDED.quantity,
        selected = TRUE
  WHERE cart_items.quantity + EXCLUDED.quantity <= 999
RETURNING id, quantity
`

type AddCartLineParams struct {
	CartID    int64
	SkuID     int64
	ProductID int64
	Quantity  int32
}

type AddCartLineRow struct {
	ID       int64
	Quantity int32
}

// 加购。**一条 upsert**，UNIQUE (cart_id, sku_id) 让重复加购必然走合并路径
// （数据模型 §10 原文的那条语句），不先查再判。
//
// DO UPDATE 带一个 WHERE：累加后超过 999 就不更新，于是 RETURNING 不返回任何行，
// 调用方拿到 ErrNoRows 并报 422 cart-quantity-exceeded。上限判在这条语句里而不是
// 服务层先读后比：两个并发的加购各自读到 600、各自加 300，先读后比的写法两个都放行，
// 最后是 1200 —— 而这里第二个会看到第一个已提交的 900，再加 300 就不成立。
// 表上的 CHECK (quantity BETWEEN 1 AND 999) 是这条语句之后的最后一道。
//
// 重复加购把 selected 重新置真：用户刚刚又加了一次，他要的就是买它。
func (q *Queries) AddCartLine(ctx context.Context, arg AddCartLineParams) (AddCartLineRow, error) {
	row := q.db.QueryRow(ctx, addCartLine,
		arg.CartID,
		arg.SkuID,
		arg.ProductID,
		arg.Quantity,
	)
	var i AddCartLineRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

// 清空（DELETE /cart）。车本身留着：它只有 user_id 一列，删了下次加购还得再建。
func (q *Queries) ClearCart(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const countCartLines = `-- name: CountCartLines :one
SELECT count(*) FROM cart_items WHERE cart_id = $1
`

// 车里有几种商品。加购前判「至多 100 种」用。
func (q *Queries) CountCartLines(ctx context.Context, cartID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCartLines, cartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCartLine = `-- name: DeleteCartLine :execrows
DELETE FROM cart_items WHERE id = $1 AND cart_id = $2
`

type DeleteCartLineParams struct {
	ID     int64
	CartID int64
}

// 删一行。返回受影响行数，0 即不在这辆车里（服务层翻成 404）。
func (q *Queries) DeleteCartLine(ctx context.Context, arg DeleteCartLineParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartLine, arg.ID, arg.CartID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCartLines = `-- name: DeleteCartLines :many
DELETE FROM cart_items
 WHERE cart_id = $1
   AND id = ANY($2::bigint[])
RETURNING id
`

type DeleteCartLinesParams struct {
	CartID  int64
	ItemIds []int64
}

// 按 id 批量删除。返回值的用法同 SetCartSelection：少了就整体回滚并报 404。
func (q *Queries) DeleteCartLines(ctx context.Context, arg DeleteCartLinesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, deleteCartLines, arg.CartID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSelectedCartLines = `-- name: DeleteSelectedCartLines :exec
DELETE FROM cart_items WHERE cart_id = $1 AND selected
`

// 删除全部已勾选条目（POST /cart/items/batch-delete 带 selected: true）。
func (q *Queries) DeleteSelectedCartLines(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, deleteSelectedCartLines, cartID)
	return err
}

const ensureCart = `-- name: EnsureCart :one
INSERT INTO carts (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id
`

// 取这个买家的车，没有就建。写路径用。
//
// ON CONFLICT DO UPDATE 而不是 DO NOTHING：后者在冲突时不 RETURNING 任何行，
// 调用方还得再查一次，而两次之间的窗口里什么都可能发生。更新的那一列是它自己，
// 真正变的只有触发器维护的 updated_at（「这辆车最近被动过」，本来就对）。
// 租户列不出现：00031 给了它 DEFAULT current_merchant()。
func (q *Queries) EnsureCart(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, ensureCart, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findCartID = `-- name: FindCartID :one

SELECT id FROM carts WHERE user_id = $1
`

// 购物车（/cart，数据模型 §10）。
//
// 全文没有一处 WHERE 写租户：租户由 RLS 在数据库层过滤（db/queries/products.sql）。
//
// ### 越权过滤只在一处：carts.user_id
//
// 「这是谁的车」只由 FindCartID / EnsureCart 按 user_id 回答一次，之后每一条
// 条目语句都带 cart_id = 那辆车。所以**条目语句上的 cart_id 条件就是越权过滤本身**：
// 删掉它，一个买家就能按自增 id 改到同一家店里别人车里的条目 —— RLS 挡不住，
// 那一行确实属于本店。契约要求那种请求是 404（查不到即 404，不是 403），
// 而 cart_id 条件让「别人的条目」在这一层与「不存在的条目」同形。
//
// ### 这里没有价格
//
// 车里的价在读的时候按门店现算，走的是 db/queries/orders.sql 的
// ListSKUsForPricing —— 与 /orders/preview、POST /orders 同一条查询。
// 这里另写一份 JOIN sku_prices_by_store 的话，「购物车显示的价」与「试算的价」
// 就有了两份实现，而它们迟早只更新一份（那条查询的注释里讲过同一件事）。
// ListCartLines 只给定价查询回答不了的东西：这一行的展示素材、它为什么不可买、
// 这家店还剩几件。
//
// 注释里一个反引号都不许有，理由见 db/queries/inventories.sql 的第三条说明。
// 这个买家的车。没有车（从没加购过）即 ErrNoRows —— 读路径据此回一辆空车，
// 不为一次 GET 建一行。
func (q *Queries) FindCartID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, findCartID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findCartLine = `-- name: FindCartLine :one
SELECT id, sku_id, quantity, selected FROM cart_items WHERE id = $1 AND cart_id = $2
`

type FindCartLineParams struct {
	ID     int64
	CartID int64
}

type FindCartLineRow struct {
	ID       int64
	SkuID    int64
	Quantity int32
	Selected bool
}

// 这辆车里的一行。不在这辆车里（含别人车里的）即 ErrNoRows。
func (q *Queries) FindCartLine(ctx context.Context, arg FindCartLineParams) (FindCartLineRow, error) {
	row := q.db.QueryRow(ctx, findCartLine, arg.ID, arg.CartID)
	var i FindCartLineRow
	err := row.Scan(
		&i.ID,
		&i.SkuID,
		&i.Quantity,
		&i.Selected,
	)
	return i, err
}

const findCartLineBySKU = `-- name: FindCartLineBySKU :one
SELECT id, quantity FROM cart_items WHERE cart_id = $1 AND sku_id = $2
`

type FindCartLineBySKUParams struct {
	CartID int64
	SkuID  int64
}

type FindCartLineBySKURow struct {
	ID       int64
	Quantity int32
}

// 这辆车里某个 SKU 那一行（加购前取当前数量，用于判库存与报 999 上限的 detail）。
func (q *Queries) FindCartLineBySKU(ctx context.Context, arg FindCartLineBySKUParams) (FindCartLineBySKURow, error) {
	row := q.db.QueryRow(ctx, findCartLineBySKU, arg.CartID, arg.SkuID)
	var i FindCartLineBySKURow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const findSKUForCart = `-- name: FindSKUForCart :one
SELECT s.id, s.product_id,
       (s.status = 1 AND s.deleted_at IS NULL
        AND p.status = 1 AND p.deleted_at IS NULL)::boolean AS on_shelf
  FROM skus s
  JOIN products p ON p.id = s.product_id
 WHERE s.id = $1
`

type FindSKUForCartRow struct {
	ID        int64
	ProductID int64
	OnShelf   bool
}

// 加购时取这个 SKU 的状态：属于哪件商品、在不在架。这家店还剩几件由库存服务回答
// （service/cart.go 在事务之前问好）。
// 查不到（不存在，或属于别家店 —— RLS 让两者同形）即 ErrNoRows。
func (q *Queries) FindSKUForCart(ctx context.Context, skuID int64) (FindSKUForCartRow, error) {
	row := q.db.QueryRow(ctx, findSKUForCart, skuID)
	var i FindSKUForCartRow
	err := row.Scan(&i.ID, &i.ProductID, &i.OnShelf)
	return i, err
}

const listCartLines = `-- name: ListCartLines :many
SELECT ci.id, ci.sku_id, ci.product_id, ci.quantity, ci.selected,
       p.title, s.spec_values, s.image_url,
       (s.status = 1 AND s.deleted_at IS NULL
        AND p.status = 1 AND p.deleted_at IS NULL)::boolean AS on_shelf,
       -- SKU 没有自己的图时，购物车行显示商品主图（与订单行快照同一个退路）。
       COALESCE(img.upload_id, 0)::bigint AS main_image_upload_id
  FROM cart_items ci
  JOIN skus s     ON s.id = ci.sku_id
  JOIN products p ON p.id = ci.product_id
  LEFT JOIN LATERAL (
        SELECT pi.upload_id FROM product_images pi
         WHERE pi.product_id = p.id
         ORDER BY pi.sort_order, pi.id
         LIMIT 1
       ) img ON TRUE
 WHERE ci.cart_id = $1
 ORDER BY ci.created_at DESC, ci.id DESC
`

type ListCartLinesRow struct {
	ID                int64
	SkuID             int64
	ProductID         int64
	Quantity          int32
	Selected          bool
	Title             string
	SpecValues        []byte
	ImageUrl          *string
	OnShelf           bool
	MainImageUploadID int64
}

// 整辆车，按加购时间倒序，带上判断「这一行现在能不能买」要用的素材。
//
// 用 JOIN 而不是 LEFT JOIN 连 skus / products：两张表都是软删（00018），
// 被删掉的规格与商品行仍在，所以 JOIN 不会让任何一行从车里消失 ——
// 这正是数据模型 §10 要的「下架、删除的商品不从购物车里清掉，查询时标记为失效」。
//
// on_shelf 与 ListSKUsForPricing 的四个条件逐字对应（s.status、s.deleted_at、
// p.status、p.deleted_at）。服务层用它区分两种「定价查询没返回这一行」：
// on_shelf 为假是失效（off_shelf），为真是这家店或它所在大区不卖（not_sold_in_store）。
// 门店 / 大区那两条排除不在这里再写一遍：它们只在定价查询里有一份。
//
// 库存**不在这里**（微服务拆分阶段 1a）：service/cart.go 在开这个事务之前先向库存服务
// 批量问过这家店的水位（一次调用），合并时把「没问到的 sku_id」记成 0（缺行即可售 0，
// 与 db/queries/products.sql 同一个口径）。
func (q *Queries) ListCartLines(ctx context.Context, cartID int64) ([]ListCartLinesRow, error) {
	rows, err := q.db.Query(ctx, listCartLines, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartLinesRow
	for rows.Next() {
		var i ListCartLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.ProductID,
			&i.Quantity,
			&i.Selected,
			&i.Title,
			&i.SpecValues,
			&i.ImageUrl,
			&i.OnShelf,
			&i.MainImageUploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartSKUIDs = `-- name: ListCartSKUIDs :many
SELECT sku_id FROM cart_items WHERE cart_id = $1
`

// 这辆车里有哪些 SKU。购物车在开主事务之前用它凑出「要向库存服务问哪几个 SKU 的水位」
// （微服务拆分阶段 1a：一次批量调用，不在持有业务连接的事务里等下游）。
func (q *Queries) ListCartSKUIDs(ctx context.Context, cartID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCartSKUIDs, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var sku_id int64
		if err := rows.Scan(&sku_id); err != nil {
			return nil, err
		}
		items = append(items, sku_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAllCartSelection = `-- name: SetAllCartSelection :exec
UPDATE cart_items SET selected = $2 WHERE cart_id = $1 AND selected <> $2
`

type SetAllCartSelectionParams struct {
	CartID   int64
	Selected bool
}

// 全选 / 全不选（PUT /cart/selection 不带 item_ids）。
func (q *Queries) SetAllCartSelection(ctx context.Context, arg SetAllCartSelectionParams) error {
	_, err := q.db.Exec(ctx, setAllCartSelection, arg.CartID, arg.Selected)
	return err
}

const setCartSelection = `-- name: SetCartSelection :many
UPDATE cart_items
   SET selected = $1
 WHERE cart_id = $2
   AND id = ANY($3::bigint[])
RETURNING id
`

type SetCartSelectionParams struct {
	Selected bool
	CartID   int64
	ItemIds  []int64
}

// 按 id 批量勾选。返回这辆车里**确实存在**的那些 id —— 调用方拿它与请求的 id
// 集合比，少了就整体回滚并报 404（契约：item_ids 中存在不属于当前用户购物车的条目）。
//
// 不带 selected <> $3 的条件：那会让「已经是这个状态」的行不出现在 RETURNING 里，
// 与「不存在」混在一起。
func (q *Queries) SetCartSelection(ctx context.Context, arg SetCartSelectionParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, setCartSelection, arg.Selected, arg.CartID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartLine = `-- name: UpdateCartLine :one
UPDATE cart_items
   SET quantity = COALESCE($1, quantity),
       selected = COALESCE($2, selected)
 WHERE id = $3
   AND cart_id = $4
RETURNING id
`

type UpdateCartLineParams struct {
	Quantity *int32
	Selected *bool
	ID       int64
	CartID   int64
}

// 改数量 / 勾选态（PATCH /cart/items/{item_id}）。两个都是「给了才改」。
func (q *Queries) UpdateCartLine(ctx context.Context, arg UpdateCartLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateCartLine,
		arg.Quantity,
		arg.Selected,
		arg.ID,
		arg.CartID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
