// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOutletBindings = `-- name: CountActiveOutletBindings :one
SELECT count(*) FROM channel_bindings WHERE status = 1 AND (roles & 4) <> 0
`

// 这家店启用中的销售渠道 binding 数（roles 位 4）。决定库存服务要不要为它发 stock.changed。
func (q *Queries) CountActiveOutletBindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOutletBindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelBinding = `-- name: CreateChannelBinding :one

INSERT INTO channel_bindings (channel, external_account, name, roles, status, config)
VALUES ($1::text, $2::text, $3::text, $4::smallint, $5::smallint, $6::jsonb)
RETURNING id, channel, external_account, name, roles, status, config, created_at, updated_at
`

type CreateChannelBindingParams struct {
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
}

type CreateChannelBindingRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// 渠道适配层（00301）。编排在 service/channel*.go；表结构与取舍见数据模型文档第十七节。
// secrets 列只有 GetChannelBindingSecrets / SetChannelBindingSecrets 两条碰它：其余读路径一律不选，接口不回显。
func (q *Queries) CreateChannelBinding(ctx context.Context, arg CreateChannelBindingParams) (CreateChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, createChannelBinding,
		arg.Channel,
		arg.ExternalAccount,
		arg.Name,
		arg.Roles,
		arg.Status,
		arg.Config,
	)
	var i CreateChannelBindingRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalAccount,
		&i.Name,
		&i.Roles,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelPriceRule = `-- name: DeleteChannelPriceRule :execrows
DELETE FROM channel_price_rules WHERE binding_id = $1::bigint AND id = $2::bigint
`

type DeleteChannelPriceRuleParams struct {
	BindingID int64
	ID        int64
}

func (q *Queries) DeleteChannelPriceRule(ctx context.Context, arg DeleteChannelPriceRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelPriceRule, arg.BindingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelStockRule = `-- name: DeleteChannelStockRule :execrows
DELETE FROM channel_stock_rules WHERE binding_id = $1::bigint AND id = $2::bigint
`

type DeleteChannelStockRuleParams struct {
	BindingID int64
	ID        int64
}

func (q *Queries) DeleteChannelStockRule(ctx context.Context, arg DeleteChannelStockRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelStockRule, arg.BindingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelStoreLink = `-- name: DeleteChannelStoreLink :execrows
DELETE FROM channel_store_links WHERE binding_id = $1::bigint AND store_id = $2::bigint
`

type DeleteChannelStoreLinkParams struct {
	BindingID int64
	StoreID   int64
}

func (q *Queries) DeleteChannelStoreLink(ctx context.Context, arg DeleteChannelStoreLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelStoreLink, arg.BindingID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelBinding = `-- name: GetChannelBinding :one
SELECT id, channel, external_account, name, roles, status, config, created_at, updated_at
  FROM channel_bindings WHERE id = $1::bigint
`

type GetChannelBindingRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetChannelBinding(ctx context.Context, id int64) (GetChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, getChannelBinding, id)
	var i GetChannelBindingRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalAccount,
		&i.Name,
		&i.Roles,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBindingSecrets = `-- name: GetChannelBindingSecrets :one
SELECT secrets FROM channel_bindings WHERE id = $1::bigint
`

func (q *Queries) GetChannelBindingSecrets(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getChannelBindingSecrets, id)
	var secrets []byte
	err := row.Scan(&secrets)
	return secrets, err
}

const getChannelInboundEvent = `-- name: GetChannelInboundEvent :one
SELECT id, binding_id, external_event_id, topic, payload, status, error, received_at, processed_at
  FROM channel_inbound_events WHERE id = $1::bigint
`

type GetChannelInboundEventRow struct {
	ID              int64
	BindingID       int64
	ExternalEventID string
	Topic           string
	Payload         []byte
	Status          int16
	Error           *string
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
}

func (q *Queries) GetChannelInboundEvent(ctx context.Context, id int64) (GetChannelInboundEventRow, error) {
	row := q.db.QueryRow(ctx, getChannelInboundEvent, id)
	var i GetChannelInboundEventRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.ExternalEventID,
		&i.Topic,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getChannelListings = `-- name: GetChannelListings :many
SELECT binding_id, store_id, sku_id, published_qty, published_cents, version, pushed_at, last_error
  FROM channel_listings
 WHERE binding_id = $1::bigint AND store_id = $2::bigint AND sku_id = ANY($3::bigint[])
`

type GetChannelListingsParams struct {
	BindingID int64
	StoreID   int64
	SkuIds    []int64
}

type GetChannelListingsRow struct {
	BindingID      int64
	StoreID        int64
	SkuID          int64
	PublishedQty   int32
	PublishedCents int64
	Version        int64
	PushedAt       pgtype.Timestamptz
	LastError      *string
}

func (q *Queries) GetChannelListings(ctx context.Context, arg GetChannelListingsParams) ([]GetChannelListingsRow, error) {
	rows, err := q.db.Query(ctx, getChannelListings, arg.BindingID, arg.StoreID, arg.SkuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelListingsRow
	for rows.Next() {
		var i GetChannelListingsRow
		if err := rows.Scan(
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.PublishedQty,
			&i.PublishedCents,
			&i.Version,
			&i.PushedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannelInboundEvent = `-- name: InsertChannelInboundEvent :one
INSERT INTO channel_inbound_events (binding_id, external_event_id, topic, payload, status)
VALUES ($1::bigint, $2::text, $3::text, $4::jsonb, $5::smallint)
ON CONFLICT ON CONSTRAINT uk_channel_inbound_events_external DO NOTHING
RETURNING id
`

type InsertChannelInboundEventParams struct {
	BindingID       int64
	ExternalEventID string
	Topic           string
	Payload         []byte
	Status          int16
}

// 重复投递（同一外部事件 ID）不插、不报错：没有行返回即重复（调用方当 inserted=false）。
func (q *Queries) InsertChannelInboundEvent(ctx context.Context, arg InsertChannelInboundEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChannelInboundEvent,
		arg.BindingID,
		arg.ExternalEventID,
		arg.Topic,
		arg.Payload,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveOutletBindingsForStore = `-- name: ListActiveOutletBindingsForStore :many
SELECT b.id, b.channel, b.external_account, b.name, b.roles, b.status, b.config, b.created_at, b.updated_at,
       l.external_store_id
  FROM channel_bindings b
  JOIN channel_store_links l ON l.binding_id = b.id
 WHERE l.store_id = $1::bigint AND b.status = 1 AND (b.roles & 4) <> 0
 ORDER BY b.id
`

type ListActiveOutletBindingsForStoreRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExternalStoreID string
}

// 这家门店映射过、启用中的销售渠道 binding，连同渠道门店 ID。
func (q *Queries) ListActiveOutletBindingsForStore(ctx context.Context, storeID int64) ([]ListActiveOutletBindingsForStoreRow, error) {
	rows, err := q.db.Query(ctx, listActiveOutletBindingsForStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOutletBindingsForStoreRow
	for rows.Next() {
		var i ListActiveOutletBindingsForStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ExternalAccount,
			&i.Name,
			&i.Roles,
			&i.Status,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalStoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelBindings = `-- name: ListChannelBindings :many
SELECT id, channel, external_account, name, roles, status, config, created_at, updated_at
  FROM channel_bindings ORDER BY id
`

type ListChannelBindingsRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListChannelBindings(ctx context.Context) ([]ListChannelBindingsRow, error) {
	rows, err := q.db.Query(ctx, listChannelBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelBindingsRow
	for rows.Next() {
		var i ListChannelBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ExternalAccount,
			&i.Name,
			&i.Roles,
			&i.Status,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelListingsPage = `-- name: ListChannelListingsPage :many
SELECT binding_id, store_id, sku_id, published_qty, published_cents, version, pushed_at, last_error
  FROM channel_listings
 WHERE binding_id = $1::bigint
   AND ($2::bigint IS NULL OR store_id = $2::bigint)
 ORDER BY store_id, sku_id
 LIMIT $4::int OFFSET $3::int
`

type ListChannelListingsPageParams struct {
	BindingID int64
	StoreID   *int64
	Off       int32
	Lim       int32
}

type ListChannelListingsPageRow struct {
	BindingID      int64
	StoreID        int64
	SkuID          int64
	PublishedQty   int32
	PublishedCents int64
	Version        int64
	PushedAt       pgtype.Timestamptz
	LastError      *string
}

func (q *Queries) ListChannelListingsPage(ctx context.Context, arg ListChannelListingsPageParams) ([]ListChannelListingsPageRow, error) {
	rows, err := q.db.Query(ctx, listChannelListingsPage,
		arg.BindingID,
		arg.StoreID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelListingsPageRow
	for rows.Next() {
		var i ListChannelListingsPageRow
		if err := rows.Scan(
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.PublishedQty,
			&i.PublishedCents,
			&i.Version,
			&i.PushedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelPriceRules = `-- name: ListChannelPriceRules :many
SELECT id, binding_id, sku_id, markup_bp, fixed_cents, updated_at
  FROM channel_price_rules WHERE binding_id = $1::bigint ORDER BY id
`

type ListChannelPriceRulesRow struct {
	ID         int64
	BindingID  int64
	SkuID      *int64
	MarkupBp   int32
	FixedCents *int64
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListChannelPriceRules(ctx context.Context, bindingID int64) ([]ListChannelPriceRulesRow, error) {
	rows, err := q.db.Query(ctx, listChannelPriceRules, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelPriceRulesRow
	for rows.Next() {
		var i ListChannelPriceRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.SkuID,
			&i.MarkupBp,
			&i.FixedCents,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelStockRules = `-- name: ListChannelStockRules :many
SELECT id, binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty, updated_at
  FROM channel_stock_rules WHERE binding_id = $1::bigint ORDER BY id
`

type ListChannelStockRulesRow struct {
	ID        int64
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListChannelStockRules(ctx context.Context, bindingID int64) ([]ListChannelStockRulesRow, error) {
	rows, err := q.db.Query(ctx, listChannelStockRules, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelStockRulesRow
	for rows.Next() {
		var i ListChannelStockRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.RatioBp,
			&i.SafetyQty,
			&i.CapQty,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelStockRulesForStore = `-- name: ListChannelStockRulesForStore :many
SELECT id, binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty, updated_at
  FROM channel_stock_rules
 WHERE binding_id = $1::bigint AND (store_id IS NULL OR store_id = $2::bigint)
`

type ListChannelStockRulesForStoreParams struct {
	BindingID int64
	StoreID   int64
}

type ListChannelStockRulesForStoreRow struct {
	ID        int64
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
	UpdatedAt pgtype.Timestamptz
}

// 算对外可售数用：渠道级 + 这家门店的（门店级与门店 × SKU 级）。
func (q *Queries) ListChannelStockRulesForStore(ctx context.Context, arg ListChannelStockRulesForStoreParams) ([]ListChannelStockRulesForStoreRow, error) {
	rows, err := q.db.Query(ctx, listChannelStockRulesForStore, arg.BindingID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelStockRulesForStoreRow
	for rows.Next() {
		var i ListChannelStockRulesForStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.RatioBp,
			&i.SafetyQty,
			&i.CapQty,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelStoreLinks = `-- name: ListChannelStoreLinks :many
SELECT binding_id, store_id, external_store_id, created_at
  FROM channel_store_links WHERE binding_id = $1::bigint ORDER BY store_id
`

type ListChannelStoreLinksRow struct {
	BindingID       int64
	StoreID         int64
	ExternalStoreID string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListChannelStoreLinks(ctx context.Context, bindingID int64) ([]ListChannelStoreLinksRow, error) {
	rows, err := q.db.Query(ctx, listChannelStoreLinks, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelStoreLinksRow
	for rows.Next() {
		var i ListChannelStoreLinksRow
		if err := rows.Scan(
			&i.BindingID,
			&i.StoreID,
			&i.ExternalStoreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelInboundEvent = `-- name: MarkChannelInboundEvent :exec
UPDATE channel_inbound_events
   SET status = $1::smallint, error = $2::text, processed_at = now()
 WHERE id = $3::bigint
`

type MarkChannelInboundEventParams struct {
	Status int16
	Error  *string
	ID     int64
}

func (q *Queries) MarkChannelInboundEvent(ctx context.Context, arg MarkChannelInboundEventParams) error {
	_, err := q.db.Exec(ctx, markChannelInboundEvent, arg.Status, arg.Error, arg.ID)
	return err
}

const setChannelBindingSecrets = `-- name: SetChannelBindingSecrets :execrows
UPDATE channel_bindings SET secrets = $1::jsonb WHERE id = $2::bigint
`

type SetChannelBindingSecretsParams struct {
	Secrets []byte
	ID      int64
}

func (q *Queries) SetChannelBindingSecrets(ctx context.Context, arg SetChannelBindingSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelBindingSecrets, arg.Secrets, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChannelListingError = `-- name: SetChannelListingError :exec
UPDATE channel_listings SET last_error = $1::text
 WHERE binding_id = $2::bigint AND store_id = $3::bigint AND sku_id = $4::bigint
`

type SetChannelListingErrorParams struct {
	LastError string
	BindingID int64
	StoreID   int64
	SkuID     int64
}

func (q *Queries) SetChannelListingError(ctx context.Context, arg SetChannelListingErrorParams) error {
	_, err := q.db.Exec(ctx, setChannelListingError,
		arg.LastError,
		arg.BindingID,
		arg.StoreID,
		arg.SkuID,
	)
	return err
}

const updateChannelBinding = `-- name: UpdateChannelBinding :one
UPDATE channel_bindings
   SET name   = COALESCE($1::text, name),
       roles  = COALESCE($2::smallint, roles),
       status = COALESCE($3::smallint, status),
       config = COALESCE($4::jsonb, config)
 WHERE id = $5::bigint
RETURNING id, channel, external_account, name, roles, status, config, created_at, updated_at
`

type UpdateChannelBindingParams struct {
	Name   *string
	Roles  *int16
	Status *int16
	Config []byte
	ID     int64
}

type UpdateChannelBindingRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// 只改传了的字段（sqlc.narg 为空即不改）。secrets 不经这里。
func (q *Queries) UpdateChannelBinding(ctx context.Context, arg UpdateChannelBindingParams) (UpdateChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, updateChannelBinding,
		arg.Name,
		arg.Roles,
		arg.Status,
		arg.Config,
		arg.ID,
	)
	var i UpdateChannelBindingRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalAccount,
		&i.Name,
		&i.Roles,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelListing = `-- name: UpsertChannelListing :one
INSERT INTO channel_listings (binding_id, store_id, sku_id, published_qty, published_cents)
VALUES ($1::bigint, $2::bigint, $3::bigint, $4::int, $5::bigint)
ON CONFLICT ON CONSTRAINT channel_listings_pkey
DO UPDATE SET published_qty = EXCLUDED.published_qty, published_cents = EXCLUDED.published_cents,
              version = channel_listings.version + 1, pushed_at = now(), last_error = NULL
RETURNING version
`

type UpsertChannelListingParams struct {
	BindingID      int64
	StoreID        int64
	SkuID          int64
	PublishedQty   int32
	PublishedCents int64
}

// 推送成功后记下推出去的值；version 每次成功加一（幂等键 binding:store:sku:version）。
func (q *Queries) UpsertChannelListing(ctx context.Context, arg UpsertChannelListingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertChannelListing,
		arg.BindingID,
		arg.StoreID,
		arg.SkuID,
		arg.PublishedQty,
		arg.PublishedCents,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const upsertChannelPriceRule = `-- name: UpsertChannelPriceRule :one
INSERT INTO channel_price_rules (binding_id, sku_id, markup_bp, fixed_cents)
VALUES ($1::bigint, $2::bigint, $3::int, $4::bigint)
ON CONFLICT ON CONSTRAINT uk_channel_price_rules_scope
DO UPDATE SET markup_bp = EXCLUDED.markup_bp, fixed_cents = EXCLUDED.fixed_cents
RETURNING id, binding_id, sku_id, markup_bp, fixed_cents, updated_at
`

type UpsertChannelPriceRuleParams struct {
	BindingID  int64
	SkuID      *int64
	MarkupBp   int32
	FixedCents *int64
}

type UpsertChannelPriceRuleRow struct {
	ID         int64
	BindingID  int64
	SkuID      *int64
	MarkupBp   int32
	FixedCents *int64
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertChannelPriceRule(ctx context.Context, arg UpsertChannelPriceRuleParams) (UpsertChannelPriceRuleRow, error) {
	row := q.db.QueryRow(ctx, upsertChannelPriceRule,
		arg.BindingID,
		arg.SkuID,
		arg.MarkupBp,
		arg.FixedCents,
	)
	var i UpsertChannelPriceRuleRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.SkuID,
		&i.MarkupBp,
		&i.FixedCents,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelStockRule = `-- name: UpsertChannelStockRule :one
INSERT INTO channel_stock_rules (binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty)
VALUES ($1::bigint, $2::bigint, $3::bigint,
        $4::int, $5::int, $6::int)
ON CONFLICT ON CONSTRAINT uk_channel_stock_rules_scope
DO UPDATE SET ratio_bp = EXCLUDED.ratio_bp, safety_qty = EXCLUDED.safety_qty, cap_qty = EXCLUDED.cap_qty
RETURNING id, binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty, updated_at
`

type UpsertChannelStockRuleParams struct {
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
}

type UpsertChannelStockRuleRow struct {
	ID        int64
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertChannelStockRule(ctx context.Context, arg UpsertChannelStockRuleParams) (UpsertChannelStockRuleRow, error) {
	row := q.db.QueryRow(ctx, upsertChannelStockRule,
		arg.BindingID,
		arg.StoreID,
		arg.SkuID,
		arg.RatioBp,
		arg.SafetyQty,
		arg.CapQty,
	)
	var i UpsertChannelStockRuleRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.StoreID,
		&i.SkuID,
		&i.RatioBp,
		&i.SafetyQty,
		&i.CapQty,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelStoreLink = `-- name: UpsertChannelStoreLink :exec
INSERT INTO channel_store_links (binding_id, store_id, external_store_id)
VALUES ($1::bigint, $2::bigint, $3::text)
ON CONFLICT ON CONSTRAINT channel_store_links_pkey DO UPDATE SET external_store_id = EXCLUDED.external_store_id
`

type UpsertChannelStoreLinkParams struct {
	BindingID       int64
	StoreID         int64
	ExternalStoreID string
}

func (q *Queries) UpsertChannelStoreLink(ctx context.Context, arg UpsertChannelStoreLinkParams) error {
	_, err := q.db.Exec(ctx, upsertChannelStoreLink, arg.BindingID, arg.StoreID, arg.ExternalStoreID)
	return err
}
