// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelSKUExists = `-- name: ChannelSKUExists :one
SELECT EXISTS (SELECT 1 FROM skus WHERE id = $1::bigint AND deleted_at IS NULL)
`

func (q *Queries) ChannelSKUExists(ctx context.Context, skuID int64) (bool, error) {
	row := q.db.QueryRow(ctx, channelSKUExists, skuID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelSKUOffers = `-- name: ChannelSKUOffers :many
SELECT v.sku_id, v.price_cents,
       (s.status = 1 AND s.deleted_at IS NULL)::boolean AS sku_active,
       (p.deleted_at IS NULL)::boolean                  AS product_live,
       (p.status = 1)::boolean                          AS product_published
  FROM sku_prices_by_store v
  JOIN skus s     ON s.id = v.sku_id
  JOIN products p ON p.id = s.product_id
 WHERE v.store_id = $1::bigint AND v.sku_id = ANY($2::bigint[])
`

type ChannelSKUOffersParams struct {
	StoreID int64
	SkuIds  []int64
}

type ChannelSKUOffersRow struct {
	SkuID            int64
	PriceCents       int64
	SkuActive        bool
	ProductLive      bool
	ProductPublished bool
}

// 推给渠道的基准价（门店就近生效价，sku_prices_by_store 是唯一实现）与「能不能卖」的三个因素：
// SKU 启用且没删、商品没删、商品已上架。不能卖的 SKU 对外可售按 0 推；「上架」这一条对商品源 binding
// 不看（上下架归商品源管，见 repository.SKUOffer.Sellable）。
func (q *Queries) ChannelSKUOffers(ctx context.Context, arg ChannelSKUOffersParams) ([]ChannelSKUOffersRow, error) {
	rows, err := q.db.Query(ctx, channelSKUOffers, arg.StoreID, arg.SkuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSKUOffersRow
	for rows.Next() {
		var i ChannelSKUOffersRow
		if err := rows.Scan(
			&i.SkuID,
			&i.PriceCents,
			&i.SkuActive,
			&i.ProductLive,
			&i.ProductPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelSKUsByCodes = `-- name: ChannelSKUsByCodes :many
SELECT id, product_id, sku_code, (deleted_at IS NOT NULL)::boolean AS deleted
  FROM skus
 WHERE sku_code = ANY($1::text[])
`

type ChannelSKUsByCodesRow struct {
	ID        int64
	ProductID int64
	SkuCode   string
	Deleted   bool
}

// 按货号找 keel 的 SKU（商品源拉商品时认领同货号的已有 SKU）。删了的也列出来：uk_skus_code 不分删没删，
// 撞上一个删了的货号也建不出新的。
func (q *Queries) ChannelSKUsByCodes(ctx context.Context, codes []string) ([]ChannelSKUsByCodesRow, error) {
	rows, err := q.db.Query(ctx, channelSKUsByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSKUsByCodesRow
	for rows.Next() {
		var i ChannelSKUsByCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelSyncRev = `-- name: ChannelSyncRev :one
SELECT (extract(epoch FROM clock_timestamp()) * 1000000)::bigint AS rev
`

// 「开关渠道」消息的版本：数据库时钟的微秒数。只用一台数据库的时钟，多个 core 实例之间没有时钟偏差。
func (q *Queries) ChannelSyncRev(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, channelSyncRev)
	var rev int64
	err := row.Scan(&rev)
	return rev, err
}

const countActiveOutletBindings = `-- name: CountActiveOutletBindings :one
SELECT count(*) FROM channel_bindings WHERE status = 1 AND (roles & 4) <> 0
`

// 这家店启用中的销售渠道 binding 数（roles 位 4）。决定库存服务要不要为它发 stock.changed。
func (q *Queries) CountActiveOutletBindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOutletBindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelBinding = `-- name: CreateChannelBinding :one

INSERT INTO channel_bindings (channel, external_account, name, roles, status, config)
VALUES ($1::text, $2::text, $3::text, $4::smallint, $5::smallint, $6::jsonb)
RETURNING id, channel, external_account, name, roles, status, config, (secrets <> '{}'::jsonb)::boolean AS has_secrets, created_at, updated_at
`

type CreateChannelBindingParams struct {
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
}

type CreateChannelBindingRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	HasSecrets      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// 渠道适配层（00301）。编排在 service/channel*.go；表结构与取舍见数据模型文档第十七节。
// secrets 列的值只有 GetChannelBindingSecrets / SetChannelBindingSecrets 两条碰它：其余读路径只选「配过没有」
// （has_secrets = secrets <> '{}'，后台显示「已配置 / 未配置」），接口不回显值。
func (q *Queries) CreateChannelBinding(ctx context.Context, arg CreateChannelBindingParams) (CreateChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, createChannelBinding,
		arg.Channel,
		arg.ExternalAccount,
		arg.Name,
		arg.Roles,
		arg.Status,
		arg.Config,
	)
	var i CreateChannelBindingRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalAccount,
		&i.Name,
		&i.Roles,
		&i.Status,
		&i.Config,
		&i.HasSecrets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelItemLink = `-- name: DeleteChannelItemLink :execrows
DELETE FROM channel_item_links
 WHERE binding_id = $1::bigint AND kind = $2::smallint AND keel_id = $3::bigint
`

type DeleteChannelItemLinkParams struct {
	BindingID int64
	Kind      int16
	KeelID    int64
}

func (q *Queries) DeleteChannelItemLink(ctx context.Context, arg DeleteChannelItemLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelItemLink, arg.BindingID, arg.Kind, arg.KeelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelPriceRule = `-- name: DeleteChannelPriceRule :execrows
DELETE FROM channel_price_rules WHERE binding_id = $1::bigint AND id = $2::bigint
`

type DeleteChannelPriceRuleParams struct {
	BindingID int64
	ID        int64
}

func (q *Queries) DeleteChannelPriceRule(ctx context.Context, arg DeleteChannelPriceRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelPriceRule, arg.BindingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelStockRule = `-- name: DeleteChannelStockRule :execrows
DELETE FROM channel_stock_rules WHERE binding_id = $1::bigint AND id = $2::bigint
`

type DeleteChannelStockRuleParams struct {
	BindingID int64
	ID        int64
}

func (q *Queries) DeleteChannelStockRule(ctx context.Context, arg DeleteChannelStockRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelStockRule, arg.BindingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannelStoreLink = `-- name: DeleteChannelStoreLink :execrows
DELETE FROM channel_store_links WHERE binding_id = $1::bigint AND store_id = $2::bigint
`

type DeleteChannelStoreLinkParams struct {
	BindingID int64
	StoreID   int64
}

func (q *Queries) DeleteChannelStoreLink(ctx context.Context, arg DeleteChannelStoreLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelStoreLink, arg.BindingID, arg.StoreID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelBinding = `-- name: GetChannelBinding :one
SELECT id, channel, external_account, name, roles, status, config, (secrets <> '{}'::jsonb)::boolean AS has_secrets, created_at, updated_at
  FROM channel_bindings WHERE id = $1::bigint
`

type GetChannelBindingRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	HasSecrets      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetChannelBinding(ctx context.Context, id int64) (GetChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, getChannelBinding, id)
	var i GetChannelBindingRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalAccount,
		&i.Name,
		&i.Roles,
		&i.Status,
		&i.Config,
		&i.HasSecrets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBindingSecrets = `-- name: GetChannelBindingSecrets :one
SELECT secrets FROM channel_bindings WHERE id = $1::bigint
`

func (q *Queries) GetChannelBindingSecrets(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getChannelBindingSecrets, id)
	var secrets []byte
	err := row.Scan(&secrets)
	return secrets, err
}

const getChannelInboundEvent = `-- name: GetChannelInboundEvent :one
SELECT id, binding_id, external_event_id, topic, payload, status, error, received_at, processed_at
  FROM channel_inbound_events WHERE id = $1::bigint
`

type GetChannelInboundEventRow struct {
	ID              int64
	BindingID       int64
	ExternalEventID string
	Topic           string
	Payload         []byte
	Status          int16
	Error           *string
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
}

func (q *Queries) GetChannelInboundEvent(ctx context.Context, id int64) (GetChannelInboundEventRow, error) {
	row := q.db.QueryRow(ctx, getChannelInboundEvent, id)
	var i GetChannelInboundEventRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.ExternalEventID,
		&i.Topic,
		&i.Payload,
		&i.Status,
		&i.Error,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getChannelItemLinkByExternal = `-- name: GetChannelItemLinkByExternal :one
SELECT binding_id, kind, keel_id, external_id, extra, synced_at
  FROM channel_item_links
 WHERE binding_id = $1::bigint AND kind = $2::smallint AND external_id = $3::text
`

type GetChannelItemLinkByExternalParams struct {
	BindingID  int64
	Kind       int16
	ExternalID string
}

type GetChannelItemLinkByExternalRow struct {
	BindingID  int64
	Kind       int16
	KeelID     int64
	ExternalID string
	Extra      []byte
	SyncedAt   pgtype.Timestamptz
}

// 按外部 ID 反查映射（商品源拉进来的商品 / 规格，找它在 keel 里是哪一个）。
func (q *Queries) GetChannelItemLinkByExternal(ctx context.Context, arg GetChannelItemLinkByExternalParams) (GetChannelItemLinkByExternalRow, error) {
	row := q.db.QueryRow(ctx, getChannelItemLinkByExternal, arg.BindingID, arg.Kind, arg.ExternalID)
	var i GetChannelItemLinkByExternalRow
	err := row.Scan(
		&i.BindingID,
		&i.Kind,
		&i.KeelID,
		&i.ExternalID,
		&i.Extra,
		&i.SyncedAt,
	)
	return i, err
}

const getChannelListings = `-- name: GetChannelListings :many
SELECT binding_id, store_id, sku_id, published_qty, published_cents, version, pushed_at, last_error
  FROM channel_listings
 WHERE binding_id = $1::bigint AND store_id = $2::bigint AND sku_id = ANY($3::bigint[])
`

type GetChannelListingsParams struct {
	BindingID int64
	StoreID   int64
	SkuIds    []int64
}

type GetChannelListingsRow struct {
	BindingID      int64
	StoreID        int64
	SkuID          int64
	PublishedQty   int32
	PublishedCents int64
	Version        int64
	PushedAt       pgtype.Timestamptz
	LastError      *string
}

func (q *Queries) GetChannelListings(ctx context.Context, arg GetChannelListingsParams) ([]GetChannelListingsRow, error) {
	rows, err := q.db.Query(ctx, getChannelListings, arg.BindingID, arg.StoreID, arg.SkuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelListingsRow
	for rows.Next() {
		var i GetChannelListingsRow
		if err := rows.Scan(
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.PublishedQty,
			&i.PublishedCents,
			&i.Version,
			&i.PushedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannelInboundEvent = `-- name: InsertChannelInboundEvent :one
INSERT INTO channel_inbound_events (binding_id, external_event_id, topic, payload, status)
VALUES ($1::bigint, $2::text, $3::text, $4::jsonb, $5::smallint)
ON CONFLICT ON CONSTRAINT uk_channel_inbound_events_external DO NOTHING
RETURNING id
`

type InsertChannelInboundEventParams struct {
	BindingID       int64
	ExternalEventID string
	Topic           string
	Payload         []byte
	Status          int16
}

// 重复投递（同一外部事件 ID）不插、不报错：没有行返回即重复（调用方当 inserted=false）。
func (q *Queries) InsertChannelInboundEvent(ctx context.Context, arg InsertChannelInboundEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChannelInboundEvent,
		arg.BindingID,
		arg.ExternalEventID,
		arg.Topic,
		arg.Payload,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveOutletBindingsForStore = `-- name: ListActiveOutletBindingsForStore :many
SELECT b.id, b.channel, b.external_account, b.name, b.roles, b.status, b.config,
       (b.secrets <> '{}'::jsonb)::boolean AS has_secrets, b.created_at, b.updated_at,
       l.external_store_id
  FROM channel_bindings b
  JOIN channel_store_links l ON l.binding_id = b.id
 WHERE l.store_id = $1::bigint AND b.status = 1 AND (b.roles & 4) <> 0
 ORDER BY b.id
`

type ListActiveOutletBindingsForStoreRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	HasSecrets      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ExternalStoreID string
}

// 这家门店映射过、启用中的销售渠道 binding，连同渠道门店 ID。
func (q *Queries) ListActiveOutletBindingsForStore(ctx context.Context, storeID int64) ([]ListActiveOutletBindingsForStoreRow, error) {
	rows, err := q.db.Query(ctx, listActiveOutletBindingsForStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOutletBindingsForStoreRow
	for rows.Next() {
		var i ListActiveOutletBindingsForStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ExternalAccount,
			&i.Name,
			&i.Roles,
			&i.Status,
			&i.Config,
			&i.HasSecrets,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalStoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelBindings = `-- name: ListChannelBindings :many
SELECT id, channel, external_account, name, roles, status, config, (secrets <> '{}'::jsonb)::boolean AS has_secrets, created_at, updated_at
  FROM channel_bindings ORDER BY id
`

type ListChannelBindingsRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	HasSecrets      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListChannelBindings(ctx context.Context) ([]ListChannelBindingsRow, error) {
	rows, err := q.db.Query(ctx, listChannelBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelBindingsRow
	for rows.Next() {
		var i ListChannelBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ExternalAccount,
			&i.Name,
			&i.Roles,
			&i.Status,
			&i.Config,
			&i.HasSecrets,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelItemLinks = `-- name: ListChannelItemLinks :many
SELECT binding_id, kind, keel_id, external_id, extra, synced_at
  FROM channel_item_links
 WHERE binding_id = $1::bigint AND kind = $2::smallint AND keel_id = ANY($3::bigint[])
`

type ListChannelItemLinksParams struct {
	BindingID int64
	Kind      int16
	KeelIds   []int64
}

type ListChannelItemLinksRow struct {
	BindingID  int64
	Kind       int16
	KeelID     int64
	ExternalID string
	Extra      []byte
	SyncedAt   pgtype.Timestamptz
}

func (q *Queries) ListChannelItemLinks(ctx context.Context, arg ListChannelItemLinksParams) ([]ListChannelItemLinksRow, error) {
	rows, err := q.db.Query(ctx, listChannelItemLinks, arg.BindingID, arg.Kind, arg.KeelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelItemLinksRow
	for rows.Next() {
		var i ListChannelItemLinksRow
		if err := rows.Scan(
			&i.BindingID,
			&i.Kind,
			&i.KeelID,
			&i.ExternalID,
			&i.Extra,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelListingsPage = `-- name: ListChannelListingsPage :many
SELECT l.binding_id, l.store_id, l.sku_id, l.published_qty, l.published_cents, l.version, l.pushed_at, l.last_error,
       s.sku_code, p.title AS product_title
  FROM channel_listings l
  JOIN skus s     ON s.id = l.sku_id
  JOIN products p ON p.id = s.product_id
 WHERE l.binding_id = $1::bigint
   AND ($2::bigint IS NULL OR l.store_id = $2::bigint)
   AND (NOT $3::boolean OR l.last_error IS NOT NULL)
 ORDER BY l.store_id, l.sku_id
 LIMIT $5::int OFFSET $4::int
`

type ListChannelListingsPageParams struct {
	BindingID  int64
	StoreID    *int64
	ErrorsOnly bool
	Off        int32
	Lim        int32
}

type ListChannelListingsPageRow struct {
	BindingID      int64
	StoreID        int64
	SkuID          int64
	PublishedQty   int32
	PublishedCents int64
	Version        int64
	PushedAt       pgtype.Timestamptz
	LastError      *string
	SkuCode        string
	ProductTitle   string
}

// 后台的推送状态：带 SKU 货号与商品名（删了的 SKU 也照列，行还在就说明推过）；errors_only 只看出错的。
func (q *Queries) ListChannelListingsPage(ctx context.Context, arg ListChannelListingsPageParams) ([]ListChannelListingsPageRow, error) {
	rows, err := q.db.Query(ctx, listChannelListingsPage,
		arg.BindingID,
		arg.StoreID,
		arg.ErrorsOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelListingsPageRow
	for rows.Next() {
		var i ListChannelListingsPageRow
		if err := rows.Scan(
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.PublishedQty,
			&i.PublishedCents,
			&i.Version,
			&i.PushedAt,
			&i.LastError,
			&i.SkuCode,
			&i.ProductTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelPriceRules = `-- name: ListChannelPriceRules :many
SELECT id, binding_id, sku_id, markup_bp, fixed_cents, updated_at
  FROM channel_price_rules WHERE binding_id = $1::bigint ORDER BY id
`

type ListChannelPriceRulesRow struct {
	ID         int64
	BindingID  int64
	SkuID      *int64
	MarkupBp   int32
	FixedCents *int64
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListChannelPriceRules(ctx context.Context, bindingID int64) ([]ListChannelPriceRulesRow, error) {
	rows, err := q.db.Query(ctx, listChannelPriceRules, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelPriceRulesRow
	for rows.Next() {
		var i ListChannelPriceRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.SkuID,
			&i.MarkupBp,
			&i.FixedCents,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelStockRules = `-- name: ListChannelStockRules :many
SELECT id, binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty, updated_at
  FROM channel_stock_rules WHERE binding_id = $1::bigint ORDER BY id
`

type ListChannelStockRulesRow struct {
	ID        int64
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListChannelStockRules(ctx context.Context, bindingID int64) ([]ListChannelStockRulesRow, error) {
	rows, err := q.db.Query(ctx, listChannelStockRules, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelStockRulesRow
	for rows.Next() {
		var i ListChannelStockRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.RatioBp,
			&i.SafetyQty,
			&i.CapQty,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelStockRulesForStore = `-- name: ListChannelStockRulesForStore :many
SELECT id, binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty, updated_at
  FROM channel_stock_rules
 WHERE binding_id = $1::bigint AND (store_id IS NULL OR store_id = $2::bigint)
`

type ListChannelStockRulesForStoreParams struct {
	BindingID int64
	StoreID   int64
}

type ListChannelStockRulesForStoreRow struct {
	ID        int64
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
	UpdatedAt pgtype.Timestamptz
}

// 算对外可售数用：渠道级 + 这家门店的（门店级与门店 × SKU 级）。
func (q *Queries) ListChannelStockRulesForStore(ctx context.Context, arg ListChannelStockRulesForStoreParams) ([]ListChannelStockRulesForStoreRow, error) {
	rows, err := q.db.Query(ctx, listChannelStockRulesForStore, arg.BindingID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelStockRulesForStoreRow
	for rows.Next() {
		var i ListChannelStockRulesForStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.StoreID,
			&i.SkuID,
			&i.RatioBp,
			&i.SafetyQty,
			&i.CapQty,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelStoreLinks = `-- name: ListChannelStoreLinks :many
SELECT binding_id, store_id, external_store_id, created_at
  FROM channel_store_links WHERE binding_id = $1::bigint ORDER BY store_id
`

type ListChannelStoreLinksRow struct {
	BindingID       int64
	StoreID         int64
	ExternalStoreID string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListChannelStoreLinks(ctx context.Context, bindingID int64) ([]ListChannelStoreLinksRow, error) {
	rows, err := q.db.Query(ctx, listChannelStoreLinks, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelStoreLinksRow
	for rows.Next() {
		var i ListChannelStoreLinksRow
		if err := rows.Scan(
			&i.BindingID,
			&i.StoreID,
			&i.ExternalStoreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkedSKUIDsPage = `-- name: ListLinkedSKUIDsPage :many
SELECT keel_id FROM channel_item_links
 WHERE binding_id = $1::bigint AND kind = 2 AND keel_id > $2::bigint
 ORDER BY keel_id LIMIT $3::int
`

type ListLinkedSKUIDsPageParams struct {
	BindingID int64
	After     int64
	Lim       int32
}

// 这个 binding 映射过的 SKU，按 id 键集分页（整店重算用）。
func (q *Queries) ListLinkedSKUIDsPage(ctx context.Context, arg ListLinkedSKUIDsPageParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listLinkedSKUIDsPage, arg.BindingID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var keel_id int64
		if err := rows.Scan(&keel_id); err != nil {
			return nil, err
		}
		items = append(items, keel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannelMerchant = `-- name: LockChannelMerchant :exec
SELECT pg_advisory_xact_lock(7340301, current_merchant()::int)
`

// 这家店的渠道启停串行化（事务级 advisory lock，提交 / 回滚即释放）。拿着它再数启用中的销售渠道、取版本，
// 版本的先后就等于提交的先后（并发启停 A、停用 B 时不会停在错误的「关」）。第一段键见 service.ChannelMerchantLockKey。
func (q *Queries) LockChannelMerchant(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockChannelMerchant)
	return err
}

const markChannelInboundEvent = `-- name: MarkChannelInboundEvent :exec
UPDATE channel_inbound_events
   SET status = $1::smallint, error = $2::text, processed_at = now()
 WHERE id = $3::bigint
`

type MarkChannelInboundEventParams struct {
	Status int16
	Error  *string
	ID     int64
}

func (q *Queries) MarkChannelInboundEvent(ctx context.Context, arg MarkChannelInboundEventParams) error {
	_, err := q.db.Exec(ctx, markChannelInboundEvent, arg.Status, arg.Error, arg.ID)
	return err
}

const setChannelBindingSecrets = `-- name: SetChannelBindingSecrets :execrows
UPDATE channel_bindings SET secrets = $1::jsonb WHERE id = $2::bigint
`

type SetChannelBindingSecretsParams struct {
	Secrets []byte
	ID      int64
}

func (q *Queries) SetChannelBindingSecrets(ctx context.Context, arg SetChannelBindingSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setChannelBindingSecrets, arg.Secrets, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setChannelListingError = `-- name: SetChannelListingError :exec
UPDATE channel_listings SET last_error = $1::text
 WHERE binding_id = $2::bigint AND store_id = $3::bigint AND sku_id = $4::bigint
`

type SetChannelListingErrorParams struct {
	LastError string
	BindingID int64
	StoreID   int64
	SkuID     int64
}

func (q *Queries) SetChannelListingError(ctx context.Context, arg SetChannelListingErrorParams) error {
	_, err := q.db.Exec(ctx, setChannelListingError,
		arg.LastError,
		arg.BindingID,
		arg.StoreID,
		arg.SkuID,
	)
	return err
}

const updateChannelBinding = `-- name: UpdateChannelBinding :one
UPDATE channel_bindings
   SET name   = COALESCE($1::text, name),
       roles  = COALESCE($2::smallint, roles),
       status = COALESCE($3::smallint, status),
       config = COALESCE($4::jsonb, config)
 WHERE id = $5::bigint
RETURNING id, channel, external_account, name, roles, status, config, (secrets <> '{}'::jsonb)::boolean AS has_secrets, created_at, updated_at
`

type UpdateChannelBindingParams struct {
	Name   *string
	Roles  *int16
	Status *int16
	Config []byte
	ID     int64
}

type UpdateChannelBindingRow struct {
	ID              int64
	Channel         string
	ExternalAccount string
	Name            string
	Roles           int16
	Status          int16
	Config          []byte
	HasSecrets      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// 只改传了的字段（sqlc.narg 为空即不改）。secrets 不经这里。
func (q *Queries) UpdateChannelBinding(ctx context.Context, arg UpdateChannelBindingParams) (UpdateChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, updateChannelBinding,
		arg.Name,
		arg.Roles,
		arg.Status,
		arg.Config,
		arg.ID,
	)
	var i UpdateChannelBindingRow
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ExternalAccount,
		&i.Name,
		&i.Roles,
		&i.Status,
		&i.Config,
		&i.HasSecrets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelItemLink = `-- name: UpsertChannelItemLink :exec
INSERT INTO channel_item_links (binding_id, kind, keel_id, external_id, extra)
VALUES ($1::bigint, $2::smallint, $3::bigint, $4::text, $5::jsonb)
ON CONFLICT ON CONSTRAINT channel_item_links_pkey
DO UPDATE SET external_id = EXCLUDED.external_id, extra = EXCLUDED.extra, synced_at = now()
`

type UpsertChannelItemLinkParams struct {
	BindingID  int64
	Kind       int16
	KeelID     int64
	ExternalID string
	Extra      []byte
}

func (q *Queries) UpsertChannelItemLink(ctx context.Context, arg UpsertChannelItemLinkParams) error {
	_, err := q.db.Exec(ctx, upsertChannelItemLink,
		arg.BindingID,
		arg.Kind,
		arg.KeelID,
		arg.ExternalID,
		arg.Extra,
	)
	return err
}

const upsertChannelListing = `-- name: UpsertChannelListing :one
INSERT INTO channel_listings (binding_id, store_id, sku_id, published_qty, published_cents)
VALUES ($1::bigint, $2::bigint, $3::bigint, $4::int, $5::bigint)
ON CONFLICT ON CONSTRAINT channel_listings_pkey
DO UPDATE SET published_qty = EXCLUDED.published_qty, published_cents = EXCLUDED.published_cents,
              version = channel_listings.version + 1, pushed_at = now(), last_error = NULL
RETURNING version
`

type UpsertChannelListingParams struct {
	BindingID      int64
	StoreID        int64
	SkuID          int64
	PublishedQty   int32
	PublishedCents int64
}

// 推送成功后记下推出去的值；version 每次成功加一（幂等键 binding:store:sku:version）。
func (q *Queries) UpsertChannelListing(ctx context.Context, arg UpsertChannelListingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertChannelListing,
		arg.BindingID,
		arg.StoreID,
		arg.SkuID,
		arg.PublishedQty,
		arg.PublishedCents,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const upsertChannelPriceRule = `-- name: UpsertChannelPriceRule :one
INSERT INTO channel_price_rules (binding_id, sku_id, markup_bp, fixed_cents)
VALUES ($1::bigint, $2::bigint, $3::int, $4::bigint)
ON CONFLICT ON CONSTRAINT uk_channel_price_rules_scope
DO UPDATE SET markup_bp = EXCLUDED.markup_bp, fixed_cents = EXCLUDED.fixed_cents
RETURNING id, binding_id, sku_id, markup_bp, fixed_cents, updated_at
`

type UpsertChannelPriceRuleParams struct {
	BindingID  int64
	SkuID      *int64
	MarkupBp   int32
	FixedCents *int64
}

type UpsertChannelPriceRuleRow struct {
	ID         int64
	BindingID  int64
	SkuID      *int64
	MarkupBp   int32
	FixedCents *int64
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertChannelPriceRule(ctx context.Context, arg UpsertChannelPriceRuleParams) (UpsertChannelPriceRuleRow, error) {
	row := q.db.QueryRow(ctx, upsertChannelPriceRule,
		arg.BindingID,
		arg.SkuID,
		arg.MarkupBp,
		arg.FixedCents,
	)
	var i UpsertChannelPriceRuleRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.SkuID,
		&i.MarkupBp,
		&i.FixedCents,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelStockRule = `-- name: UpsertChannelStockRule :one
INSERT INTO channel_stock_rules (binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty)
VALUES ($1::bigint, $2::bigint, $3::bigint,
        $4::int, $5::int, $6::int)
ON CONFLICT ON CONSTRAINT uk_channel_stock_rules_scope
DO UPDATE SET ratio_bp = EXCLUDED.ratio_bp, safety_qty = EXCLUDED.safety_qty, cap_qty = EXCLUDED.cap_qty
RETURNING id, binding_id, store_id, sku_id, ratio_bp, safety_qty, cap_qty, updated_at
`

type UpsertChannelStockRuleParams struct {
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
}

type UpsertChannelStockRuleRow struct {
	ID        int64
	BindingID int64
	StoreID   *int64
	SkuID     *int64
	RatioBp   int32
	SafetyQty int32
	CapQty    *int32
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertChannelStockRule(ctx context.Context, arg UpsertChannelStockRuleParams) (UpsertChannelStockRuleRow, error) {
	row := q.db.QueryRow(ctx, upsertChannelStockRule,
		arg.BindingID,
		arg.StoreID,
		arg.SkuID,
		arg.RatioBp,
		arg.SafetyQty,
		arg.CapQty,
	)
	var i UpsertChannelStockRuleRow
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.StoreID,
		&i.SkuID,
		&i.RatioBp,
		&i.SafetyQty,
		&i.CapQty,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChannelStoreLink = `-- name: UpsertChannelStoreLink :exec
INSERT INTO channel_store_links (binding_id, store_id, external_store_id)
VALUES ($1::bigint, $2::bigint, $3::text)
ON CONFLICT ON CONSTRAINT channel_store_links_pkey DO UPDATE SET external_store_id = EXCLUDED.external_store_id
`

type UpsertChannelStoreLinkParams struct {
	BindingID       int64
	StoreID         int64
	ExternalStoreID string
}

func (q *Queries) UpsertChannelStoreLink(ctx context.Context, arg UpsertChannelStoreLinkParams) error {
	_, err := q.db.Exec(ctx, upsertChannelStoreLink, arg.BindingID, arg.StoreID, arg.ExternalStoreID)
	return err
}
