// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: freight.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountFreightTemplates = `-- name: AdminCountFreightTemplates :one
SELECT count(*)
  FROM freight_templates
 WHERE deleted_at IS NULL
   AND ($1::bigint IS NULL OR store_id = $1::bigint)
`

func (q *Queries) AdminCountFreightTemplates(ctx context.Context, storeID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountFreightTemplates, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetFreightTemplate = `-- name: AdminGetFreightTemplate :one
SELECT t.id, t.name, t.store_id, t.charge_mode, t.is_default, t.undeliverable_region_codes,
       t.created_at, t.updated_at,
       (SELECT count(*) FROM products p
         WHERE p.freight_template_id = t.id AND p.deleted_at IS NULL)::int AS product_count
  FROM freight_templates t
 WHERE t.id = $1
   AND t.deleted_at IS NULL
`

type AdminGetFreightTemplateRow struct {
	ID                       int64
	Name                     string
	StoreID                  *int64
	ChargeMode               int16
	IsDefault                bool
	UndeliverableRegionCodes []string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	ProductCount             int32
}

// 列与 AdminListFreightTemplates 逐一对齐，行类型可以直接互转。
func (q *Queries) AdminGetFreightTemplate(ctx context.Context, id int64) (AdminGetFreightTemplateRow, error) {
	row := q.db.QueryRow(ctx, adminGetFreightTemplate, id)
	var i AdminGetFreightTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StoreID,
		&i.ChargeMode,
		&i.IsDefault,
		&i.UndeliverableRegionCodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductCount,
	)
	return i, err
}

const adminListFreightTemplates = `-- name: AdminListFreightTemplates :many

SELECT t.id, t.name, t.store_id, t.charge_mode, t.is_default, t.undeliverable_region_codes,
       t.created_at, t.updated_at,
       (SELECT count(*) FROM products p
         WHERE p.freight_template_id = t.id AND p.deleted_at IS NULL)::int AS product_count
  FROM freight_templates t
 WHERE t.deleted_at IS NULL
   AND ($1::bigint IS NULL OR t.store_id = $1::bigint)
 ORDER BY t.id DESC
 LIMIT $3 OFFSET $2
`

type AdminListFreightTemplatesParams struct {
	StoreID   *int64
	RowOffset int32
	RowLimit  int32
}

type AdminListFreightTemplatesRow struct {
	ID                       int64
	Name                     string
	StoreID                  *int64
	ChargeMode               int16
	IsDefault                bool
	UndeliverableRegionCodes []string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	ProductCount             int32
}

// ---------------------------------------------------------------------------
// 后台
// ---------------------------------------------------------------------------
// 后台模板列表，一页。product_count 是挂着它的未删除商品数（走 idx_products_freight_template）。
func (q *Queries) AdminListFreightTemplates(ctx context.Context, arg AdminListFreightTemplatesParams) ([]AdminListFreightTemplatesRow, error) {
	rows, err := q.db.Query(ctx, adminListFreightTemplates, arg.StoreID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListFreightTemplatesRow
	for rows.Next() {
		var i AdminListFreightTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StoreID,
			&i.ChargeMode,
			&i.IsDefault,
			&i.UndeliverableRegionCodes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearDefaultFreightTemplate = `-- name: ClearDefaultFreightTemplate :execrows
UPDATE freight_templates
   SET is_default = FALSE
 WHERE is_default
   AND deleted_at IS NULL
   AND id <> $1
`

// 设新的全店默认之前先取消旧的（uk_freight_templates_default 是部分唯一索引，
// 反过来会自己撞自己 —— 与 uk_stores_default 同一个顺序）。except_id 是要设成默认的那一个。
func (q *Queries) ClearDefaultFreightTemplate(ctx context.Context, exceptID int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearDefaultFreightTemplate, exceptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countProductsOnFreightTemplate = `-- name: CountProductsOnFreightTemplate :one
SELECT count(*)
  FROM products
 WHERE freight_template_id = $1
   AND deleted_at IS NULL
`

func (q *Queries) CountProductsOnFreightTemplate(ctx context.Context, freightTemplateID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsOnFreightTemplate, freightTemplateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFreightRules = `-- name: DeleteFreightRules :execrows
DELETE FROM freight_template_rules WHERE template_id = $1
`

func (q *Queries) DeleteFreightRules(ctx context.Context, templateID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFreightRules, templateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFreightRule = `-- name: InsertFreightRule :exec
INSERT INTO freight_template_rules (template_id, sort_order, region_codes, first_unit,
                                    first_fee_cents, additional_unit, additional_fee_cents,
                                    free_threshold_cents, free_quantity)
VALUES ($1, $2, $3::text[],
        $4, $5, $6,
        $7, $8, $9)
`

type InsertFreightRuleParams struct {
	TemplateID         int64
	SortOrder          int32
	RegionCodes        []string
	FirstUnit          int32
	FirstFeeCents      int64
	AdditionalUnit     int32
	AdditionalFeeCents int64
	FreeThresholdCents int64
	FreeQuantity       int32
}

func (q *Queries) InsertFreightRule(ctx context.Context, arg InsertFreightRuleParams) error {
	_, err := q.db.Exec(ctx, insertFreightRule,
		arg.TemplateID,
		arg.SortOrder,
		arg.RegionCodes,
		arg.FirstUnit,
		arg.FirstFeeCents,
		arg.AdditionalUnit,
		arg.AdditionalFeeCents,
		arg.FreeThresholdCents,
		arg.FreeQuantity,
	)
	return err
}

const insertFreightTemplate = `-- name: InsertFreightTemplate :one
INSERT INTO freight_templates (name, store_id, charge_mode, is_default, undeliverable_region_codes)
VALUES ($1, $2, $3, $4,
        $5::text[])
RETURNING id
`

type InsertFreightTemplateParams struct {
	Name                     string
	StoreID                  *int64
	ChargeMode               int16
	IsDefault                bool
	UndeliverableRegionCodes []string
}

func (q *Queries) InsertFreightTemplate(ctx context.Context, arg InsertFreightTemplateParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFreightTemplate,
		arg.Name,
		arg.StoreID,
		arg.ChargeMode,
		arg.IsDefault,
		arg.UndeliverableRegionCodes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listFreightRules = `-- name: ListFreightRules :many
SELECT template_id, sort_order, region_codes, first_unit, first_fee_cents,
       additional_unit, additional_fee_cents, free_threshold_cents, free_quantity
  FROM freight_template_rules
 WHERE template_id = ANY($1::bigint[])
 ORDER BY template_id, (region_codes = '{}'), sort_order, id
`

type ListFreightRulesRow struct {
	TemplateID         int64
	SortOrder          int32
	RegionCodes        []string
	FirstUnit          int32
	FirstFeeCents      int64
	AdditionalUnit     int32
	AdditionalFeeCents int64
	FreeThresholdCents int64
	FreeQuantity       int32
}

// 一批模板的全部规则。默认规则（region_codes 为空）排在最后，其余按录入顺序 ——
// 后台编辑页与计价都按这个顺序读。
func (q *Queries) ListFreightRules(ctx context.Context, templateIds []int64) ([]ListFreightRulesRow, error) {
	rows, err := q.db.Query(ctx, listFreightRules, templateIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFreightRulesRow
	for rows.Next() {
		var i ListFreightRulesRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.SortOrder,
			&i.RegionCodes,
			&i.FirstUnit,
			&i.FirstFeeCents,
			&i.AdditionalUnit,
			&i.AdditionalFeeCents,
			&i.FreeThresholdCents,
			&i.FreeQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreightTemplatesForPricing = `-- name: ListFreightTemplatesForPricing :many
SELECT id, name, store_id, charge_mode, is_default, undeliverable_region_codes
  FROM freight_templates
 WHERE deleted_at IS NULL
   AND (id = ANY($1::bigint[])
        OR store_id = $2
        OR (store_id IS NULL AND is_default))
`

type ListFreightTemplatesForPricingParams struct {
	TemplateIds []int64
	StoreID     *int64
}

type ListFreightTemplatesForPricingRow struct {
	ID                       int64
	Name                     string
	StoreID                  *int64
	ChargeMode               int16
	IsDefault                bool
	UndeliverableRegionCodes []string
}

// 计价要用到的模板：商品单独挂的那几个、履约门店的门店模板、全店默认模板。
// 一条查询取齐，由 service/freight.go 按「商品挂的 → 门店模板 → 全店默认」挑。
//
// 商品挂的模板若已软删（删除接口会拒绝还有商品挂着的模板，所以正常不会发生），
// 这里取不到它，那一行就按门店模板、全店默认往下落 —— 与「不单独挂」同一个结果。
func (q *Queries) ListFreightTemplatesForPricing(ctx context.Context, arg ListFreightTemplatesForPricingParams) ([]ListFreightTemplatesForPricingRow, error) {
	rows, err := q.db.Query(ctx, listFreightTemplatesForPricing, arg.TemplateIds, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFreightTemplatesForPricingRow
	for rows.Next() {
		var i ListFreightTemplatesForPricingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StoreID,
			&i.ChargeMode,
			&i.IsDefault,
			&i.UndeliverableRegionCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUFreightInfo = `-- name: ListSKUFreightInfo :many


SELECT s.id, s.weight_gram, p.freight_template_id
  FROM skus s
  JOIN products p ON p.id = s.product_id
 WHERE s.id = ANY($1::bigint[])
`

type ListSKUFreightInfoRow struct {
	ID                int64
	WeightGram        int32
	FreightTemplateID *int64
}

// 运费模板的查询：后台的增删改查、计价时取模板与规则、每一行商品的重量与挂的模板。
// 数据模型 §7「运费模板」「运费怎么算」。
//
// 全文没有一处 WHERE 写租户，也没有一处 INSERT 写 merchant_id：租户由 RLS 过滤，
// 写入那一列由 DEFAULT current_merchant() 补（00041）。理由见 db/queries/products.sql
// 与 scripts/check_query_tenancy.py 的文件头。
//
// 注释里一个反引号都不许有，理由见 db/queries/inventories.sql 的第三条说明。
// ---------------------------------------------------------------------------
// 计价
// ---------------------------------------------------------------------------
// 一批 SKU 的重量与所属商品单独挂的运费模板。试算、下单、购物车共用。
//
// 与 ListSKUsForPricing 分成两条，而不是往那条里再加两列：那一条决定「可不可售、
// 多少钱」，是营销活动与券共用的输入；运费只在它之后才用得上（计价顺序的最后一段），
// 而且只要这两列。调用方只拿**已经定过价**的那些 sku_id 来问，
// 所以这里不再重复可售性的四个条件。
func (q *Queries) ListSKUFreightInfo(ctx context.Context, skuIds []int64) ([]ListSKUFreightInfoRow, error) {
	rows, err := q.db.Query(ctx, listSKUFreightInfo, skuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSKUFreightInfoRow
	for rows.Next() {
		var i ListSKUFreightInfoRow
		if err := rows.Scan(&i.ID, &i.WeightGram, &i.FreightTemplateID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFreightTemplate = `-- name: LockFreightTemplate :one
SELECT id, store_id
  FROM freight_templates
 WHERE id = $1
   AND deleted_at IS NULL
   FOR UPDATE
`

type LockFreightTemplateRow struct {
	ID      int64
	StoreID *int64
}

// 改、删之前锁住模板行，拿到它此刻的归属。与 LockFreightTemplateForLink 的 FOR SHARE 互斥：
// 「数挂着它的商品」与「给商品挂上它」在这一行锁上串行（00041 文件头第一节）。
func (q *Queries) LockFreightTemplate(ctx context.Context, id int64) (LockFreightTemplateRow, error) {
	row := q.db.QueryRow(ctx, lockFreightTemplate, id)
	var i LockFreightTemplateRow
	err := row.Scan(&i.ID, &i.StoreID)
	return i, err
}

const lockFreightTemplateForLink = `-- name: LockFreightTemplateForLink :one
SELECT id
  FROM freight_templates
 WHERE id = $1
   AND deleted_at IS NULL
   AND store_id IS NULL
   FOR SHARE
`

// 商品挂模板之前确认它是一个**未删除的全店模板**，并以共享锁钉住它直到事务结束 ——
// 否则并发的一次「改成门店模板」或「删除」会在数完商品之后、这件商品挂上之前溜过去。
func (q *Queries) LockFreightTemplateForLink(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockFreightTemplateForLink, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const softDeleteFreightTemplate = `-- name: SoftDeleteFreightTemplate :execrows
UPDATE freight_templates
   SET deleted_at = now(), is_default = FALSE
 WHERE id = $1
   AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFreightTemplate(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFreightTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFreightTemplate = `-- name: UpdateFreightTemplate :execrows
UPDATE freight_templates
   SET name = $1,
       store_id = $2,
       charge_mode = $3,
       is_default = $4,
       undeliverable_region_codes = $5::text[]
 WHERE id = $6
   AND deleted_at IS NULL
`

type UpdateFreightTemplateParams struct {
	Name                     string
	StoreID                  *int64
	ChargeMode               int16
	IsDefault                bool
	UndeliverableRegionCodes []string
	ID                       int64
}

func (q *Queries) UpdateFreightTemplate(ctx context.Context, arg UpdateFreightTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFreightTemplate,
		arg.Name,
		arg.StoreID,
		arg.ChargeMode,
		arg.IsDefault,
		arg.UndeliverableRegionCodes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
