// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventories.sql

package db

import (
	"context"
)

const deductInventory = `-- name: DeductInventory :one
WITH visible AS (
    SELECT inv.sku_id FROM inventories inv WHERE inv.sku_id = $1
), deducted AS (
    UPDATE inventories upd
       SET available_qty = upd.available_qty - $2,
           updated_at    = now()
     WHERE upd.sku_id = $1 AND upd.available_qty >= $2
    RETURNING upd.available_qty AS left_qty
)
SELECT (SELECT count(*) FROM visible)  AS visible_rows,
       (SELECT count(*) FROM deducted) AS deducted_rows,
       d.left_qty                      AS after_available
  FROM (SELECT 1) a
  LEFT JOIN deducted d ON true
`

type DeductInventoryParams struct {
	SkuID        int64
	AvailableQty int32
}

type DeductInventoryRow struct {
	VisibleRows    int64
	DeductedRows   int64
	AfterAvailable *int32
}

// 扣减库存。**一条语句同时回答两个问题**：这一行在本租户可见吗？扣成功了吗？
//
// 数据模型 §4 与 M2 计划第三条写下的那件事：「rows_affected = 0」 有两种成因，
// 不能混为一谈。
//
//	① 库存不足（「available_qty >= $2」 不满足）→ 业务分支，触发 SAGA 全局补偿；
//	② 这个 SKU 根本不属于本租户（RLS 的 USING 谓词把行整个挡在视野外）
//	   → 是 bug 或攻击，不是业务分支。
//
// 只看 「UPDATE ... WHERE sku_id = $1 AND available_qty >= $2」 的 rows_affected，
// 这两种情形的信号**完全一样**，都是 0。混为一谈的后果很具体：一次攥着别家
// sku_id 的越权尝试会被当成一次正常的缺货去补偿——补偿是幂等的、日志是正常的，
// 于是它在监控上表现为库存波动，而不是一次安全事件。反过来，哪天调用方把租户
// 传错了，症状会是「所有商品都缺货」，排查方向从第一步就是错的。
//
// 所以这里不是「先加一次预检查」，而是把两个问题压进同一条语句、同一个快照：
// visible 与 deducted 两个 CTE 看到的是同一个 MVCC 快照，中间没有别的事务能把
// 行删掉或改掉租户归属，于是「可见但没扣成」与「根本不可见」不会因为竞态互换。
// 拆成「先 SELECT 确认可见、再 UPDATE」是两次快照，那个窗口是真的。
//
// **第三种**失败不在这三个返回值里：完全没设 「app.merchant_id」 时
// current_merchant() 直接 RAISE，整条语句以 42501 失败，根本走不到返回值
// （数据模型 §4 按实测改正过这一条）。它是异常，不是这里的任何一支。
//
// 刻意不带 WHERE merchant_id —— 租户由 RLS 在数据库层过滤，理由见
// db/queries/products.sql。本表尤其如此：这条语句要区分的正是「RLS 挡住了」，
// 应用层再加一遍同样的条件，被挡住的那一行就再也分不清是谁挡的。
//
// ### 两处写法上的将就，都是 sqlc 逼出来的，不是本来想这么写
//
// 一、两个 CTE 里的 inventories 各带一个别名（inv / upd）。sqlc 的作用域解析
//
//	把整条语句的关系拍平成一张表，同一张表出现两次就让每个裸列名都报
//	"column reference ... is ambiguous"，生成直接失败。PostgreSQL 自己没有
//	这个问题（两个 CTE 是各自独立的作用域）。
//
// 二、末尾那个 「FROM (SELECT 1) a LEFT JOIN deducted d ON true」，换成更直白的
//
//	「(SELECT left_qty FROM deducted) AS after_available」 语义完全一样，但
//	sqlc 会把这个标量子查询推断成**非空** int32；而它在「库存不足」那一支
//	恰恰是 NULL，于是 row.Scan 会在最该被区分开的那条路径上直接报错。
//	LEFT JOIN 让可空性显式地写在 SQL 里，产物才是 *int32。
//	「(SELECT 1) a」 保证外层恒有且只有一行，所以这条查询永远不会返回 0 行。
//
// 三、注释里一个反引号都不许有。sqlc 会把这些注释原样抄进产物的 Go 文档注释，
//
//	而 scripts/check_query_tenancy.py 扫产物时用的是「一对反引号之间是 SQL
//	字面量」这条规则——注释里的反引号会被配对成一段假的字面量，于是
//	「完全没设 app.merchant_id 时」这句话被当成一句应用层租户过滤报出来。
//	多报一次是安全的失败方向，所以不改那个脚本，改这里：用「」代替反引号。
func (q *Queries) DeductInventory(ctx context.Context, arg DeductInventoryParams) (DeductInventoryRow, error) {
	row := q.db.QueryRow(ctx, deductInventory, arg.SkuID, arg.AvailableQty)
	var i DeductInventoryRow
	err := row.Scan(&i.VisibleRows, &i.DeductedRows, &i.AfterAvailable)
	return i, err
}

const restoreInventory = `-- name: RestoreInventory :one
UPDATE inventories
   SET available_qty = available_qty + $2,
       updated_at    = now()
 WHERE sku_id = $1
RETURNING available_qty
`

type RestoreInventoryParams struct {
	SkuID        int64
	AvailableQty int32
}

// 补偿：回补库存。没有「数量不够」这一支，所以不需要上面那个双 CTE ——
// 零行就只可能是「这一行在本租户不可见」，而那同样是 bug 或攻击，不是业务分支。
//
// :one 让零行变成 pgx.ErrNoRows，调用方拿不到一个能被当成「正常」的返回值。
// 写成 :exec 的话 rows_affected = 0 会被静默吞掉，而补偿路径恰恰是最容易
// 直接攥着 sku_id 回滚的地方（数据模型 §4 点名说了这一条）。
func (q *Queries) RestoreInventory(ctx context.Context, arg RestoreInventoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, restoreInventory, arg.SkuID, arg.AvailableQty)
	var available_qty int32
	err := row.Scan(&available_qty)
	return available_qty, err
}
