// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID         int64
	MerchantID int64
	ParentID   *int64
	Name       string
	Path       string
	Level      int16
	SortOrder  int32
	Status     int16
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Merchant struct {
	ID        int64
	Code      string
	Name      string
	Status    int16
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Product struct {
	ID            int64
	MerchantID    int64
	CategoryID    int64
	BrandID       *int64
	Title         string
	Subtitle      *string
	Description   *string
	MinPriceCents int64
	MaxPriceCents int64
	TotalStock    int32
	SalesCount    int32
	Status        int16
	PublishedAt   pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ShopSetting struct {
	MerchantID      int64
	Domain          *string
	LogoUrl         *string
	Currency        string
	Timezone        string
	AutoConfirmDays int16
	Extra           []byte
	UpdatedAt       pgtype.Timestamptz
}

type Sku struct {
	ID         int64
	MerchantID int64
	ProductID  int64
	SkuCode    string
	SpecValues []byte
	PriceCents int64
	CostCents  int64
	WeightGram int32
	ImageUrl   *string
	Status     int16
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
