// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// 活动配额与已售（库存服务独有，微服务拆分阶段 1b，00075）。不带外键，理由见 00075 文件头。
type ActivityStock struct {
	MerchantID  int64
	PromotionID int64
	SkuID       int64
	Quota       int32
	Sold        int32
	UpdatedAt   pgtype.Timestamptz
}

// AI 员工按提案种类的自动执行策略（00130，AI 经营 M11）。
type AgentAutoPolicy struct {
	MerchantID       int64
	AgentStaffID     int64
	Kind             string
	Enabled          bool
	MaxUnits         int32
	MinDiscountRate  int16
	MaxDiscountCents int64
	DailyLimit       int32
	UpdatedBy        *int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

// AI 员工写的经营简报（00092，AI 经营 M9）。
type AgentBrief struct {
	ID           int64
	MerchantID   int64
	AgentStaffID int64
	Title        string
	Body         string
	PeriodStart  pgtype.Date
	PeriodEnd    pgtype.Date
	CreatedAt    pgtype.Timestamptz
	CorrectsID   *int64
}

// AI 员工的事件：库存预警、售后申请、无结果词突增、提案结果（00121，AI 经营 M10）。
type AgentEvent struct {
	ID         int64
	MerchantID int64
	Type       string
	StoreID    *int64
	Payload    []byte
	DedupeKey  string
	CreatedAt  pgtype.Timestamptz
}

// AI 员工拉取事件的游标：确认到哪一条（00121）。
type AgentEventCursor struct {
	MerchantID   int64
	AgentStaffID int64
	LastAckedID  int64
	UpdatedAt    pgtype.Timestamptz
}

// AI 员工的接入密钥（00090，AI 经营 M9）。只存 sha256；明文只在创建响应里出现一次。
type AgentKey struct {
	ID         int64
	MerchantID int64
	StaffID    int64
	Name       string
	Prefix     string
	SecretHash string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	CreatedBy  int64
	CreatedAt  pgtype.Timestamptz
}

// AI 员工的提案（00091，AI 经营 M9）：人批准后以 AI 员工的身份执行。
type AgentProposal struct {
	ID             int64
	MerchantID     int64
	AgentStaffID   int64
	Kind           string
	StoreID        *int64
	SkuID          *int64
	Payload        []byte
	Title          string
	Evidence       string
	ExpectedImpact string
	Status         int16
	DecidedBy      *int64
	DecidedAt      pgtype.Timestamptz
	RejectReason   *string
	Result         []byte
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TargetKey      string
	ExecutedAt     pgtype.Timestamptz
	OutcomeDueAt   pgtype.Timestamptz
	Outcome        []byte
	OutcomeAt      pgtype.Timestamptz
	AutoApproved   bool
}

type AgentRoCategory struct {
	ID       int64
	ParentID *int64
	Name     string
	Path     string
	Level    int16
	Status   int16
}

type AgentRoCouponTemplate struct {
	ID               int64
	Name             string
	CouponType       int16
	ThresholdCents   int64
	DiscountCents    int64
	DiscountRate     int16
	MaxDiscountCents int64
	ValidMode        int16
	ValidStartAt     pgtype.Timestamptz
	ValidEndAt       pgtype.Timestamptz
	ValidDays        int32
	TotalCount       int32
	IssuedCount      int32
	PerUserLimit     int32
	Claimable        bool
	Status           int16
	CreatedAt        pgtype.Timestamptz
}

type AgentRoOrder struct {
	ID                     int64
	OrderNo                string
	UserID                 int64
	Status                 int16
	RefundStatus           int16
	StoreID                int64
	RegionID               int64
	GoodsAmountCents       int64
	FreightCents           int64
	DiscountCents          int64
	PromotionDiscountCents int64
	FreightDiscountCents   int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	CouponName             *string
	CreatedAt              pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
}

type AgentRoOrderItem struct {
	ID                     int64
	OrderID                int64
	SkuID                  int64
	ProductID              int64
	TitleSnapshot          string
	SpecSnapshot           []byte
	ListPriceCents         int64
	PriceCents             int64
	Quantity               int32
	AmountCents            int64
	DiscountCents          int64
	PromotionDiscountCents int64
	PricePromotionID       *int64
	RefundedQty            int32
	RefundedCents          int64
}

type AgentRoProduct struct {
	ID          int64
	CategoryID  int64
	BrandID     *int64
	Title       string
	Subtitle    *string
	TotalStock  int32
	SalesCount  int32
	Status      int16
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AgentRoPromotion struct {
	ID              int64
	Name            string
	PromoType       int16
	ThresholdUnit   int16
	StackWithCoupon bool
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          int16
	CreatedAt       pgtype.Timestamptz
}

type AgentRoPromotionSku struct {
	ID              int64
	PromotionID     int64
	SkuID           int64
	PromoPriceCents int64
	DiscountRate    int16
	PerUserLimit    int32
	StockQty        int32
	SoldQty         int32
}

type AgentRoRefund struct {
	ID               int64
	RefundNo         string
	OrderID          int64
	RefundType       int16
	ReasonCode       int16
	GoodsAmountCents int64
	FreightCents     int64
	AmountCents      int64
	Status           int16
	AuditedAt        pgtype.Timestamptz
	RefundedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type AgentRoRegion struct {
	ID     int64
	Code   string
	Name   string
	Status int16
}

type AgentRoSearchLog struct {
	ID          int64
	Query       string
	Strategy    string
	ResultCount int32
	ClickedID   *int64
	CartedID    *int64
	OrderedID   *int64
	LatencyMs   *int32
	CreatedAt   pgtype.Timestamptz
	Fallback    bool
}

type AgentRoSku struct {
	ID         int64
	ProductID  int64
	SkuCode    string
	SpecValues []byte
	PriceCents int64
	CostCents  int64
	WeightGram int32
	Status     int16
	CreatedAt  pgtype.Timestamptz
}

type AgentRoStore struct {
	ID        int64
	RegionID  int64
	Code      string
	Name      string
	Province  string
	City      string
	District  string
	IsDefault bool
	Status    int16
	Lat       interface{}
	Lng       interface{}
	CreatedAt pgtype.Timestamptz
}

type AgentRoUserCoupon struct {
	ID         int64
	TemplateID int64
	UserID     int64
	Source     int16
	Status     int16
	OrderID    *int64
	CreatedAt  pgtype.Timestamptz
	UsedAt     pgtype.Timestamptz
}

// AI 员工的 MCP 工具调用审计（00093，AI 经营 M9）。
type AgentToolCall struct {
	ID           int64
	MerchantID   int64
	AgentStaffID int64
	KeyID        int64
	Tool         string
	Args         []byte
	Ok           bool
	ErrorType    string
	DurationMs   int32
	CreatedAt    pgtype.Timestamptz
}

// AI 员工的事件 webhook：每名 AI 员工至多一个（00121）。
type AgentWebhook struct {
	ID           int64
	MerchantID   int64
	AgentStaffID int64
	Url          string
	Secret       string
	Enabled      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// AI 员工事件 webhook 的投递记录：每次尝试一行（00121）。
type AgentWebhookDelivery struct {
	ID          int64
	MerchantID  int64
	EventID     int64
	WebhookID   int64
	Attempt     int32
	StatusCode  *int32
	Error       string
	DeliveredAt pgtype.Timestamptz
}

// 子事务屏障（数据模型 §6）。形状照抄 dtmrs-barrier v0.11.0，别加列。
type Barrier struct {
	TransType  string
	Gid        string
	BranchID   string
	Op         string
	BarrierID  string
	Reason     string
	CreateTime int64
}

type Cart struct {
	ID         int64
	MerchantID int64
	UserID     int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CartItem struct {
	ID         int64
	MerchantID int64
	CartID     int64
	SkuID      int64
	ProductID  int64
	Quantity   int32
	Selected   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Category struct {
	ID         int64
	MerchantID int64
	ParentID   *int64
	Name       string
	Path       string
	Level      int16
	SortOrder  int32
	Status     int16
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CouponScope struct {
	ID         int64
	MerchantID int64
	TemplateID int64
	ScopeType  int16
	TargetID   *int64
	Include    bool
}

type CouponTemplate struct {
	ID               int64
	MerchantID       int64
	Name             string
	CouponType       int16
	ThresholdCents   int64
	DiscountCents    int64
	DiscountRate     int16
	MaxDiscountCents int64
	ValidMode        int16
	ValidStartAt     pgtype.Timestamptz
	ValidEndAt       pgtype.Timestamptz
	ValidDays        int32
	TotalCount       int32
	IssuedCount      int32
	PerUserLimit     int32
	Claimable        bool
	Stackable        bool
	Priority         int16
	ExtraRules       []byte
	Status           int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FreightTemplate struct {
	ID                       int64
	MerchantID               int64
	Name                     string
	StoreID                  *int64
	ChargeMode               int16
	IsDefault                bool
	UndeliverableRegionCodes []string
	DeletedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type FreightTemplateRule struct {
	ID                 int64
	MerchantID         int64
	TemplateID         int64
	SortOrder          int32
	RegionCodes        []string
	FirstUnit          int32
	FirstFeeCents      int64
	AdditionalUnit     int32
	AdditionalFeeCents int64
	FreeThresholdCents int64
	FreeQuantity       int32
}

type IdempotencyKey struct {
	Scope        string
	MerchantID   *int64
	SubjectID    int64
	IdemKey      string
	RequestHash  string
	Status       int16
	ResponseCode *int32
	ResponseBody []byte
	ExpireAt     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SubjectKind  int16
}

type Inventory struct {
	SkuID        int64
	AvailableQty int32
	WarningQty   int32
	UpdatedAt    pgtype.Timestamptz
	MerchantID   int64
	StoreID      int64
}

type InventoryLog struct {
	ID              int64
	MerchantID      int64
	SkuID           int64
	ChangeQty       int32
	BizType         int16
	BizID           string
	BeforeAvailable int32
	AfterAvailable  int32
	CreatedAt       pgtype.Timestamptz
	StoreID         int64
	Reason          *string
}

type Job struct {
	ID          int64
	MerchantID  int64
	Queue       string
	JobKey      string
	Payload     []byte
	Priority    int16
	Status      int16
	Attempts    int32
	MaxAttempts int32
	RunAfter    pgtype.Timestamptz
	LockedBy    *string
	LockedAt    pgtype.Timestamptz
	LastError   *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// 同城配送模板：门店引用，没配的围栏店用默认模板（00111）。
type LocalDeliveryTemplate struct {
	ID            int64
	MerchantID    int64
	Name          string
	IsDefault     bool
	MinOrderCents int64
	FreeOverCents int64
	FeeTiers      []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type LoginFailure struct {
	MerchantID  int64
	Phone       string
	FailCount   int32
	WindowStart pgtype.Timestamptz
	LockedUntil pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Merchant struct {
	ID        int64
	Code      string
	Name      string
	Status    int16
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MerchantRevision struct {
	ID         int64
	MerchantID int64
	Name       string
	Status     int16
	ChangedBy  int64
	CreatedAt  pgtype.Timestamptz
}

type Notification struct {
	ID         int64
	MerchantID int64
	Audience   int16
	UserID     *int64
	StoreID    *int64
	Kind       string
	Title      string
	Body       string
	TargetType string
	OrderNo    *string
	RefundNo   *string
	SkuID      *int64
	DedupeKey  string
	ReadAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type NotificationDelivery struct {
	ID             int64
	MerchantID     int64
	NotificationID int64
	Channel        string
	Status         int16
	Attempt        int32
	Detail         *string
	CreatedAt      pgtype.Timestamptz
}

type NotificationRead struct {
	ID             int64
	MerchantID     int64
	NotificationID int64
	StaffID        int64
	ReadAt         pgtype.Timestamptz
}

type Order struct {
	ID                     int64
	MerchantID             int64
	OrderNo                string
	UserID                 int64
	Status                 int16
	RefundStatus           int16
	GoodsAmountCents       int64
	FreightCents           int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	ReceiverSnapshot       []byte
	Remark                 *string
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	StoreID                int64
	RegionID               int64
	StoreSnapshot          []byte
	UserCouponID           *int64
	CouponName             *string
	FreightDiscountCents   int64
	FreightSnapshot        []byte
	PromotionDiscountCents int64
	Promotions             []byte
	PlacedAt               pgtype.Timestamptz
}

type OrderItem struct {
	ID                     int64
	MerchantID             int64
	OrderID                int64
	SkuID                  int64
	ProductID              int64
	TitleSnapshot          string
	SpecSnapshot           []byte
	ImageSnapshot          *string
	PriceCents             int64
	Quantity               int32
	AmountCents            int64
	DiscountCents          int64
	RefundedQty            int32
	RefundedCents          int64
	ListPriceCents         int64
	PricePromotionID       *int64
	PromotionDiscountCents int64
}

type OrderStatusTransition struct {
	FromStatus int16
	ToStatus   int16
}

type Payment struct {
	ID            int64
	MerchantID    int64
	PaymentNo     string
	OrderID       int64
	Channel       int16
	AmountCents   int64
	Status        int16
	ChannelTxnID  *string
	NotifyPayload []byte
	PaidAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Product struct {
	ID                int64
	MerchantID        int64
	CategoryID        int64
	BrandID           *int64
	Title             string
	Subtitle          *string
	Description       *string
	TotalStock        int32
	SalesCount        int32
	Status            int16
	PublishedAt       pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	SearchText        *string
	SearchVector      interface{}
	FreightTemplateID *int64
}

type ProductCluster struct {
	ProductID  int64
	MerchantID int64
	ClusterID  int64
	Confidence float32
	Method     int16
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ProductImage struct {
	ID         int64
	MerchantID int64
	ProductID  int64
	UploadID   int64
	SortOrder  int32
	CreatedAt  pgtype.Timestamptz
}

type ProductImageVector struct {
	ProductID    int64
	MerchantID   int64
	ImageUrl     string
	Embedding    string
	ModelName    string
	ModelVersion string
	UpdatedAt    pgtype.Timestamptz
}

type ProductImportBatch struct {
	ID              int64
	MerchantID      int64
	FileSha256      string
	FileName        string
	FileFormat      string
	StaffID         int64
	TotalRows       int32
	CreatedProducts int32
	CreatedSkus     int32
	FailedRows      int32
	Result          []byte
	CreatedAt       pgtype.Timestamptz
}

// 门店 × 商品有没有货的冗余标记，只给商品列表排序用（00087）；显示仍现问库存服务。刷新见 service/stock_flags.go。
type ProductStoreStock struct {
	StoreID    int64
	ProductID  int64
	MerchantID int64
	InStock    bool
	UpdatedAt  pgtype.Timestamptz
}

type ProductTextVector struct {
	ProductID    int64
	MerchantID   int64
	Content      string
	Embedding    string
	ModelName    string
	ModelVersion string
	UpdatedAt    pgtype.Timestamptz
}

type ProductUnderstanding struct {
	ProductID       int64
	MerchantID      int64
	Status          int16
	InputHashes     []byte
	Results         []byte
	PipelineVersion string
	LastError       *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Promotion struct {
	ID              int64
	MerchantID      int64
	Name            string
	PromoType       int16
	ThresholdUnit   int16
	StackWithCoupon bool
	GiftTemplateID  *int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          int16
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PromotionGiftGrant struct {
	MerchantID   int64
	PromotionID  int64
	UserID       int64
	UserCouponID int64
	CreatedAt    pgtype.Timestamptz
}

type PromotionPurchase struct {
	MerchantID  int64
	PromotionID int64
	SkuID       int64
	UserID      int64
	Qty         int32
}

type PromotionScope struct {
	ID          int64
	MerchantID  int64
	PromotionID int64
	ScopeType   int16
	TargetID    *int64
	Include     bool
}

type PromotionSku struct {
	ID              int64
	MerchantID      int64
	PromotionID     int64
	SkuID           int64
	PromoPriceCents int64
	DiscountRate    int16
	PerUserLimit    int32
	// 已停用（00075）：配额搬到 activity_stocks.quota，代码不再读写；下一版删列。
	StockQty int32
	// 已停用（00075）：已售搬到 activity_stocks.sold，代码不再读写；下一版删列。
	SoldQty int32
}

type PromotionTier struct {
	ID            int64
	MerchantID    int64
	PromotionID   int64
	Threshold     int64
	DiscountCents int64
	DiscountRate  int16
}

type Refund struct {
	ID                int64
	MerchantID        int64
	RefundNo          string
	OrderID           int64
	PaymentID         int64
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	NotifyPayload     []byte
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AuditedBy         *int64
	ReceivedAt        pgtype.Timestamptz
	ReceivedBy        *int64
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
}

type RefundItem struct {
	ID          int64
	MerchantID  int64
	RefundID    int64
	OrderItemID int64
	Quantity    int32
	AmountCents int64
}

type RefundStatusTransition struct {
	FromStatus int16
	ToStatus   int16
}

type Region struct {
	ID         int64
	MerchantID int64
	Code       string
	Name       string
	Status     int16
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type RegionProductOverride struct {
	RegionID   int64
	ProductID  int64
	MerchantID int64
	Status     int16
	UpdatedBy  *int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type RegionSkuPrice struct {
	RegionID   int64
	SkuID      int64
	MerchantID int64
	PriceCents int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SearchLog struct {
	ID           int64
	MerchantID   int64
	UserID       *int64
	SessionID    *string
	Query        string
	ParsedIntent []byte
	RecallIds    []int64
	RankedIds    []int64
	ClickedID    *int64
	CartedID     *int64
	OrderedID    *int64
	LatencyMs    *int32
	TraceID      string
	Strategy     string
	Stages       []string
	ModelName    *string
	ModelVersion *string
	CreatedAt    pgtype.Timestamptz
	Fallback     bool
}

type Shipment struct {
	ID          int64
	MerchantID  int64
	OrderID     int64
	CarrierCode string
	TrackingNo  string
	Status      int16
	ShippedAt   pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
	CreatedBy   *int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShopPreference struct {
	MerchantID      int64
	ServicePhone    *string
	Timezone        string
	AutoConfirmDays int16
	ReturnShipDays  int16
	UpdatedAt       pgtype.Timestamptz
	PublicAiLog     bool
}

type ShopSetting struct {
	MerchantID int64
	Domain     *string
	LogoUrl    *string
	Currency   string
	Extra      []byte
	UpdatedAt  pgtype.Timestamptz
}

type Sku struct {
	ID         int64
	MerchantID int64
	ProductID  int64
	SkuCode    string
	SpecValues []byte
	PriceCents int64
	CostCents  int64
	WeightGram int32
	ImageUrl   *string
	Status     int16
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type SkuPricesByRegion struct {
	RegionID    int64
	SkuID       int64
	ProductID   int64
	PriceCents  int64
	PriceSource int32
}

type SkuPricesByStore struct {
	StoreID     int64
	RegionID    int64
	SkuID       int64
	ProductID   int64
	PriceCents  int64
	PriceSource int32
}

type Staff struct {
	ID          int64
	MerchantID  *int64
	Email       string
	Name        string
	Role        int16
	Status      int16
	CreatedBy   *int64
	LastLoginAt pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Kind        int16
}

type StaffScope struct {
	ID         int64
	MerchantID int64
	StaffID    int64
	RegionID   *int64
	StoreID    *int64
	CreatedAt  pgtype.Timestamptz
}

type StaffToken struct {
	ID         int64
	StaffID    int64
	TokenHash  string
	Kind       int16
	ExpireAt   pgtype.Timestamptz
	UsedAt     pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedIp  *netip.Addr
	CreatedAt  pgtype.Timestamptz
}

type Store struct {
	ID         int64
	MerchantID int64
	RegionID   int64
	Code       string
	Name       string
	Phone      string
	Province   string
	City       string
	District   string
	Address    string
	Location   interface{}
	Fence      interface{}
	IsDefault  bool
	Status     int16
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// 有围栏门店的同城配送：起送价、按距离分档的配送费、满额免配送费（00110）。
type StoreLocalDelivery struct {
	MerchantID    int64
	StoreID       int64
	MinOrderCents int64
	FreeOverCents int64
	FeeTiers      []byte
	UpdatedAt     pgtype.Timestamptz
	TemplateID    *int64
}

type StoreProductOverride struct {
	StoreID    int64
	ProductID  int64
	MerchantID int64
	Status     int16
	UpdatedBy  *int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type StoreSkuPrice struct {
	StoreID    int64
	SkuID      int64
	MerchantID int64
	PriceCents int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Upload struct {
	ID          int64
	MerchantID  int64
	UserID      *int64
	StaffID     *int64
	Purpose     int16
	Driver      int16
	StorageKey  string
	ContentType string
	SizeBytes   int64
	Sha256      string
	Referenced  bool
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int64
	MerchantID   int64
	Phone        *string
	Email        *string
	PasswordHash *string
	Nickname     string
	AvatarUrl    *string
	Gender       int16
	Status       int16
	LastLoginAt  pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserAddress struct {
	ID           int64
	MerchantID   int64
	UserID       int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Tag          int16
	IsDefault    bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Lat          *float64
	Lng          *float64
}

type UserCoupon struct {
	ID           int64
	MerchantID   int64
	CouponCode   string
	TemplateID   int64
	UserID       int64
	Source       int16
	Status       int16
	OrderID      *int64
	ValidStartAt pgtype.Timestamptz
	ValidEndAt   pgtype.Timestamptz
	LockedAt     pgtype.Timestamptz
	UsedAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type UserIdentity struct {
	ID         int64
	MerchantID int64
	UserID     int64
	Provider   int16
	ExternalID string
	UnionID    *string
	Credential []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type UserToken struct {
	ID         int64
	MerchantID int64
	UserID     int64
	TokenHash  []byte
	ExpireAt   pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
