// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimExpiredPendingOrder = `-- name: ClaimExpiredPendingOrder :execrows
UPDATE orders SET status = 90
 WHERE order_no = $1 AND status = 10 AND expire_at < now()
`

// 原子占位：把一笔超时未支付的订单关到 90。**返回 1 才算这一单归我。**
//
// 谓词里 status = 10 与 expire_at < now() 两个条件缺一不可：
//
//	· status = 10  —— 支付回调刚把它推到 20 时，这里必须落空。少了它，
//	  一笔已付款的订单会被关掉，而库存还会被「回补」一次 —— 超卖。
//	· expire_at    —— 不是冗余：扫描与处置之间订单的 expire_at 理论上可被延长
//	  （续期），而一条无条件的关单会把续期后的订单照关不误。
//
// 回补库存与这条 UPDATE 在**同一个事务**里，所以「关了单却没回补」与
// 「回补了却没关单」两种半成品都不存在。
func (q *Queries) ClaimExpiredPendingOrder(ctx context.Context, orderNo string) (int64, error) {
	result, err := q.db.Exec(ctx, claimExpiredPendingOrder, orderNo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO idempotency_keys (scope, subject_kind, subject_id, idem_key, request_hash, expire_at)
VALUES ($1, $2, $3, $4, $5, now() + interval '24 hours')
ON CONFLICT (scope, subject_kind, subject_id, idem_key) DO UPDATE
   SET request_hash = EXCLUDED.request_hash,
       expire_at    = EXCLUDED.expire_at,
       updated_at   = now()
 WHERE idempotency_keys.status = 0
   AND idempotency_keys.expire_at < now()
`

type ClaimIdempotencyKeyParams struct {
	Scope       string
	SubjectKind int16
	SubjectID   int64
	IdemKey     string
	RequestHash string
}

// 抢占式插入（数据模型 §12）。**主键就是那把锁。**
//
// 返回 1 = 抢到了，执行业务；返回 0 = 已存在，调用方读出那一行按三态处理。
//
// 这里**要**写冲突目标，和 barrier 那条相反（00008：keel_app 在 barrier 上只有
// INSERT，带冲突目标要额外的 SELECT 权，会当场 42501）。这张表四权齐全，
// 而且必须带：不带的话，任何别的约束冲突也会被静默吞掉，
// 而抢占插入唯一想沉默跳过的是主键撞车。
//
// 24 小时足够覆盖客户端的重试窗口（§12）。
//
// **ON CONFLICT 上那个 DO UPDATE WHERE 只在一种情况下动手**（2026-10-08 破坏性测试）：
// 已存在、仍处理中、且已过期（expire_at < now()）。那种行是 SAGA 等待超时后
// 再没人回填的遗留 —— 留着它就是把一把钥匙锁死，而幂等协议恰恰要求客户端
// 拿同一把钥匙重试。其余情况（成功 / 失败存档 / 未过期的处理中）一律 DO NOTHING，
// 原样落回三态判定。
//
// 只回收**过期**的那一种，不回收未过期的：未过期的处理中是真的有人在跑
// （同一笔 SAGA 还活着），换一把钥匙建第二单才是重复下单。
// expire_at 由这里自己推进到 now()+24h，与首次插入一致。
//
// 主体是 (subject_kind, subject_id)，不是 user_id：1 买家 users.id /
// 2 后台 staff.id。两张表的 id 来自同一种自增序列，共用一列的话
// staff_id = 7 与 user_id = 7 会撞在同一行上（00023 的文件头）。
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.Scope,
		arg.SubjectKind,
		arg.SubjectID,
		arg.IdemKey,
		arg.RequestHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeExpiredDraftOrder = `-- name: CloseExpiredDraftOrder :execrows
UPDATE orders SET status = 90
 WHERE order_no = $1 AND status = 0 AND expire_at < now()
`

// 孤儿草稿的处置：0 → 90。**不回补库存**，理由见 sweep.go。
//
// 同样带条件：一笔草稿在扫描与处置之间可能被 SAGA 的建单分支推到 10
// （一个跑了很久才回来的重放），那时它不再是孤儿，这里必须落空。
func (q *Queries) CloseExpiredDraftOrder(ctx context.Context, orderNo string) (int64, error) {
	result, err := q.db.Exec(ctx, closeExpiredDraftOrder, orderNo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeOrder = `-- name: CloseOrder :execrows
UPDATE orders SET status = 90 WHERE order_no = $1 AND status IN (0, 10)
`

// 建单分支的补偿：把订单关掉。
//
// 允许从 0 和 10 两个状态进来。10 是正常的补偿路径（正向已经把它推到待支付），
// 0 是正向分支本身失败时的路径。已经是 90 的行不再动 —— 关单是幂等的，
// 而重放一次补偿不该把行数变成 0 之外的任何东西去误导调用方。
func (q *Queries) CloseOrder(ctx context.Context, orderNo string) (int64, error) {
	result, err := q.db.Exec(ctx, closeOrder, orderNo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUserOrders = `-- name: CountUserOrders :one
SELECT count(*)
  FROM orders
 WHERE user_id = $1
   AND status <> 0
   AND ($2::smallint IS NULL OR status = $2::smallint)
   AND ($3::smallint IS NULL
        OR refund_status = $3::smallint)
`

type CountUserOrdersParams struct {
	UserID       *int64
	Status       *int16
	RefundStatus *int16
}

// 契约里 PageMeta.total 是必填字段，而它是**全部条数**，不是本页条数。
//
// 谓词必须与 ListUserOrders 逐字一致（user_id、status <> 0、两个可空筛选），
// 理由与 CountProducts 那条一样，只是后果更重：这里少一个 user_id，
// total 数的就是全店的订单数，于是「我的订单」页脚会告诉每个买家这家店一共
// 有多少单 —— 一次不需要读到任何一行别人的数据就完成的信息泄露。
func (q *Queries) CountUserOrders(ctx context.Context, arg CountUserOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserOrders, arg.UserID, arg.Status, arg.RefundStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelOrderDraft = `-- name: CreateChannelOrderDraft :one
INSERT INTO orders (order_no, user_id, source, channel_order_id, store_id, region_id, store_snapshot,
                    status, goods_amount_cents, freight_cents, freight_discount_cents,
                    discount_cents, payable_cents, receiver_snapshot, remark, expire_at,
                    promotion_discount_cents)
SELECT $1, NULL, 1, $2::bigint, st.id, st.region_id,
       jsonb_build_object('store_name', st.name, 'region_name', r.name,
                          'address', st.address, 'phone', st.phone),
       0, $3, $4, $5,
       $6, $7,
       $8, $9, $10,
       $6
  FROM stores st
  JOIN regions r ON r.id = st.region_id
 WHERE st.id = $11 AND st.deleted_at IS NULL
RETURNING id, order_no, store_id, region_id, status, goods_amount_cents, freight_cents,
          freight_discount_cents, discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
          expire_at, created_at, promotion_discount_cents
`

type CreateChannelOrderDraftParams struct {
	OrderNo              string
	ChannelOrderID       int64
	GoodsAmountCents     int64
	FreightCents         int64
	FreightDiscountCents int64
	DiscountCents        int64
	PayableCents         int64
	ReceiverSnapshot     []byte
	Remark               *string
	ExpireAt             pgtype.Timestamptz
	StoreID              int64
}

type CreateChannelOrderDraftRow struct {
	ID                     int64
	OrderNo                string
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	PromotionDiscountCents int64
}

// 渠道单（00320）的 keel 订单草稿（status 0，渠道单 SAGA 的第一步把它推到 10）。与 CreateOrderDraft 同一个写法
// （门店快照与外键取自同一行 stores），差别：source = 1、user_id 为空、channel_order_id 指回渠道单；
// 金额全是平台快照（discount = promotion_discount = 平台补贴 + 商家补贴，没有券，chk_discount_sources 对
// source = 1 放开）；promotions 为空数组（不是 keel 的活动）。
func (q *Queries) CreateChannelOrderDraft(ctx context.Context, arg CreateChannelOrderDraftParams) (CreateChannelOrderDraftRow, error) {
	row := q.db.QueryRow(ctx, createChannelOrderDraft,
		arg.OrderNo,
		arg.ChannelOrderID,
		arg.GoodsAmountCents,
		arg.FreightCents,
		arg.FreightDiscountCents,
		arg.DiscountCents,
		arg.PayableCents,
		arg.ReceiverSnapshot,
		arg.Remark,
		arg.ExpireAt,
		arg.StoreID,
	)
	var i CreateChannelOrderDraftRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.PromotionDiscountCents,
	)
	return i, err
}

const createOrderDraft = `-- name: CreateOrderDraft :one
INSERT INTO orders (order_no, user_id, store_id, region_id, store_snapshot,
                    status, goods_amount_cents, freight_cents, freight_discount_cents,
                    freight_snapshot,
                    discount_cents, payable_cents, receiver_snapshot, remark, expire_at,
                    user_coupon_id, coupon_name, promotion_discount_cents, promotions)
SELECT $1, $2, st.id, st.region_id,
       jsonb_build_object('store_name', st.name, 'region_name', r.name,
                          'address', st.address, 'phone', st.phone),
       0, $3, $4,
       $5, $6,
       $7, $8,
       $9, $10, $11,
       $12,
       (SELECT ct.name
          FROM user_coupons uc
          JOIN coupon_templates ct ON ct.id = uc.template_id
         WHERE uc.id = $12),
       $13, $14
  FROM stores st
  JOIN regions r ON r.id = st.region_id
 WHERE st.id = $15 AND st.deleted_at IS NULL
RETURNING id, order_no, store_id, region_id, status, goods_amount_cents, freight_cents,
          freight_discount_cents,
          discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
          expire_at, created_at, user_coupon_id, coupon_name, promotion_discount_cents,
          promotions
`

type CreateOrderDraftParams struct {
	OrderNo                string
	UserID                 *int64
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	FreightSnapshot        []byte
	DiscountCents          int64
	PayableCents           int64
	ReceiverSnapshot       []byte
	Remark                 *string
	ExpireAt               pgtype.Timestamptz
	UserCouponID           *int64
	PromotionDiscountCents int64
	Promotions             []byte
	StoreID                int64
}

type CreateOrderDraftRow struct {
	ID                     int64
	OrderNo                string
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
}

// 落一笔**创建中**的订单（status = 0），在提交 SAGA 之前。
//
// 顺序的理由写在 00013 的文件头：分支只拿到 (gid, branch_id, op) 三个字符串，
// 「扣哪些 SKU、各扣几件」推不出来，只能先落库。而 0 这个状态让「已落库」
// 不等于「已成交」—— 状态 0 的订单永远不会出现在任何响应里。
//
// 租户列不出现在这条语句里（00013 的 DEFAULT current_merchant()）。
//
// **store_id / region_id / store_snapshot 本轮（00020）一起落下来。**
// 三列都 NOT NULL，理由在数据模型 §4 末尾：SAGA 分支只拿到三个字符串，
// 它读回订单行拿到一个 NULL 的 store_id 时无路可走 —— 既不能猜默认店
// （会把单扣到另一家店去），也不能失败（订单已经落库了）。
//
// region_id 从 stores 现读一次，**存成订单自己的列，不靠 stores.region_id 推**：
// 门店可以被调到另一个大区去，而这一单的价格是按当时那个大区算的。
// 要能事后回答「这个价是怎么来的」，就不能让它取决于一张随后会变的表。
//
// store_snapshot 只放展示字段（门店名、大区名、地址、电话），**不放 id**——
// 放了就会有人去 GROUP BY 它，而聚合该走 store_id 那一列（真外键、有索引）。
//
// 写成 INSERT ... SELECT FROM stores 而不是让应用把这几个值传进来：
// 快照与外键必须来自**同一行**、同一个快照。应用先查一次门店再把字段拼进
// INSERT，两步之间那家店可以改名 —— 于是 store_id 指着 A，快照写着 A 的旧名字，
// 而两者都「看起来正常」。门店不存在或已软删时这条语句插 0 行，
// 由 :one 变成 pgx.ErrNoRows，调用方翻成 422。
//
// user_coupon_id（00026）也在这里落：SAGA 的券分支只拿到三个字符串，
// 「这一单用哪张券」只能从订单行上读回来。
//
// coupon_name（00029）是券名快照，**与 store_snapshot 同一条道理、同一个写法**：
// 从 user_coupons → coupon_templates 现读，和外键 user_coupon_id 落在同一条语句里。
// 应用先查一次券名再传进来的话，两步之间模板可以改名。没带券时子查询是 NULL；
// 带了券却匹配不上时 chk_coupon_name_with_coupon 与外键一起拒绝。
func (q *Queries) CreateOrderDraft(ctx context.Context, arg CreateOrderDraftParams) (CreateOrderDraftRow, error) {
	row := q.db.QueryRow(ctx, createOrderDraft,
		arg.OrderNo,
		arg.UserID,
		arg.GoodsAmountCents,
		arg.FreightCents,
		arg.FreightDiscountCents,
		arg.FreightSnapshot,
		arg.DiscountCents,
		arg.PayableCents,
		arg.ReceiverSnapshot,
		arg.Remark,
		arg.ExpireAt,
		arg.UserCouponID,
		arg.PromotionDiscountCents,
		arg.Promotions,
		arg.StoreID,
	)
	var i CreateOrderDraftRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UserCouponID,
		&i.CouponName,
		&i.PromotionDiscountCents,
		&i.Promotions,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (order_id, sku_id, product_id, title_snapshot, spec_snapshot,
                         image_snapshot, price_cents, quantity, amount_cents, discount_cents,
                         list_price_cents, price_promotion_id, promotion_discount_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateOrderItemParams struct {
	OrderID                int64
	SkuID                  int64
	ProductID              int64
	TitleSnapshot          string
	SpecSnapshot           []byte
	ImageSnapshot          *string
	PriceCents             int64
	Quantity               int32
	AmountCents            int64
	DiscountCents          int64
	ListPriceCents         int64
	PricePromotionID       *int64
	PromotionDiscountCents int64
}

// 订单项快照（数据模型 §5：下单即快照）。商品改价改名不影响历史订单。
//
// 00058 起多三列：list_price_cents（门店价快照）、price_promotion_id（改了单价的
// 限时折扣 / 秒杀）、promotion_discount_cents（满减满折分摊到这一行的那一份，
// 已含在 discount_cents 里）。
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderID,
		arg.SkuID,
		arg.ProductID,
		arg.TitleSnapshot,
		arg.SpecSnapshot,
		arg.ImageSnapshot,
		arg.PriceCents,
		arg.Quantity,
		arg.AmountCents,
		arg.DiscountCents,
		arg.ListPriceCents,
		arg.PricePromotionID,
		arg.PromotionDiscountCents,
	)
	return err
}

const finishIdempotencyKey = `-- name: FinishIdempotencyKey :exec
UPDATE idempotency_keys
   SET status = $5, response_code = $6, response_body = $7
 WHERE scope = $1 AND subject_kind = $2 AND subject_id = $3 AND idem_key = $4
`

type FinishIdempotencyKeyParams struct {
	Scope        string
	SubjectKind  int16
	SubjectID    int64
	IdemKey      string
	Status       int16
	ResponseCode *int32
	ResponseBody []byte
}

// 把存档写回去。status：1 成功 / 2 失败。
//
// 失败也存档并回放（§12 的边界选择：最保守，绝不会重复扣款）。
// 确需重试的场景让客户端换一个新键。
func (q *Queries) FinishIdempotencyKey(ctx context.Context, arg FinishIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, finishIdempotencyKey,
		arg.Scope,
		arg.SubjectKind,
		arg.SubjectID,
		arg.IdemKey,
		arg.Status,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, status, response_code, response_body, expire_at
  FROM idempotency_keys
 WHERE scope = $1 AND subject_kind = $2 AND subject_id = $3 AND idem_key = $4
`

type GetIdempotencyKeyParams struct {
	Scope       string
	SubjectKind int16
	SubjectID   int64
	IdemKey     string
}

type GetIdempotencyKeyRow struct {
	RequestHash  string
	Status       int16
	ResponseCode *int32
	ResponseBody []byte
	ExpireAt     pgtype.Timestamptz
}

// 读出已存在的那一行，用于判定重放 / 409 处理中 / 422 键被复用。
//
// expire_at 一起取出来：处理中那一档要靠它判断「真的有人在跑」还是
// 「一把没人管的过期钥匙」（2026-10-08，见ClaimIdempotencyKey 上那段）。
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.Scope,
		arg.SubjectKind,
		arg.SubjectID,
		arg.IdemKey,
	)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.ExpireAt,
	)
	return i, err
}

const getOrderByNo = `-- name: GetOrderByNo :one
SELECT id, order_no, user_id, store_id, region_id, status,
       goods_amount_cents, freight_cents, freight_discount_cents,
       discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
       expire_at, paid_at, shipped_at, finished_at, created_at, user_coupon_id,
       coupon_name, promotion_discount_cents, promotions,
       source, channel_order_id  -- 00320：来源与渠道单（渠道单 user_id 为空）
  FROM orders
 WHERE order_no = $1
`

type GetOrderByNoRow struct {
	ID                     int64
	OrderNo                string
	UserID                 *int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
	Source                 int16
	ChannelOrderID         *int64
}

// 按对外编号取订单。SAGA 的两个分支都靠它把「自己要处理哪一单」找回来 ——
// order_no 是从 gid 里解出来的，而 gid 是协调器重放时唯一还在的东西。
//
// 它在 RLS 之下：分支跑在 dtm.TenantContextFromGID 造出来的租户上下文里，
// 所以拿着 A 店的 gid 去查 B 店的订单，结果是查不到，而不是查到了别人的单。
//
// paid_at / shipped_at / finished_at 是买家侧读接口（GET /orders 与
// GET /orders/{order_no}）补上来的三列。契约的 Order 里它们都声明过，而在此之前
// 这条查询根本没 SELECT 它们 —— 于是「付款时间」在支付成功之后的响应里
// 依然缺席，客户端只能显示一个没有时间的「已支付」。
// 三列一起取而不是只取 paid_at：shipped_at 是「发货后 N 天自动确认收货」倒计时
// 的起点（契约里明写），finished_at 同理属于同一张时间线，分两次加意味着
// 这条查询与它的领域类型要被改两遍。
//
// user_coupon_id（00026）：SAGA 的券分支靠它知道这一单用的是哪张券。
func (q *Queries) GetOrderByNo(ctx context.Context, orderNo string) (GetOrderByNoRow, error) {
	row := q.db.QueryRow(ctx, getOrderByNo, orderNo)
	var i GetOrderByNoRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UserCouponID,
		&i.CouponName,
		&i.PromotionDiscountCents,
		&i.Promotions,
		&i.Source,
		&i.ChannelOrderID,
	)
	return i, err
}

const getOrderFreightSnapshot = `-- name: GetOrderFreightSnapshot :one
SELECT freight_snapshot
  FROM orders
 WHERE id = $1
`

// 下单那一刻的运费计算明细快照（契约的 OrderDetail.freight / AdminOrderDetail.freight，00056）。
//
// 与 GetOrderStoreSnapshot 同一个理由单独成条：一整块 JSONB，列表用不着。
// 00056 之前的订单是 NULL（那时不计运费），调用方让字段整个不出现。
func (q *Queries) GetOrderFreightSnapshot(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrderFreightSnapshot, id)
	var freight_snapshot []byte
	err := row.Scan(&freight_snapshot)
	return freight_snapshot, err
}

const getOrderReceiver = `-- name: GetOrderReceiver :one
SELECT receiver_snapshot
  FROM orders
 WHERE id = $1
`

// 下单时拍下的收货信息快照（契约的 OrderDetail.receiver）。
//
// 单独一条查询而不是并进 GetUserOrderByNo：receiver_snapshot 是一整块 JSONB，
// 而那条查询被订单列表**逐行**复用 —— 列表里没有任何地方要展示收货地址，
// 每页多搬 20 份快照是白搬的。
func (q *Queries) GetOrderReceiver(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrderReceiver, id)
	var receiver_snapshot []byte
	err := row.Scan(&receiver_snapshot)
	return receiver_snapshot, err
}

const getOrderStoreSnapshot = `-- name: GetOrderStoreSnapshot :one
SELECT store_snapshot
  FROM orders
 WHERE id = $1
`

// 下单时拍下的门店 / 大区展示快照（契约的 OrderDetail.store）。
//
// 与 GetOrderReceiver 分开、也与 GetUserOrderByNo 分开，理由一字不差：
// 它是一整块 JSONB，而订单列表逐行复用那条查询，列表里没有任何地方要展示
// 门店地址与电话。
//
// **读快照而不是 JOIN stores**：门店会改名、会搬家、会换大区，
// 三个月前那单的详情页要显示当时那个名字（数据模型 §5）。
// JOIN 出来的是今天的名字，而那正是快照存在要避免的东西。
func (q *Queries) GetOrderStoreSnapshot(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOrderStoreSnapshot, id)
	var store_snapshot []byte
	err := row.Scan(&store_snapshot)
	return store_snapshot, err
}

const getUserAddress = `-- name: GetUserAddress :one
SELECT id, receiver_name, phone, province, city, district, street, detail,
       region_code, postal_code, lat, lng
  FROM user_addresses
 WHERE id = $1
   AND user_id = $2
   AND deleted_at IS NULL
`

type GetUserAddressParams struct {
	ID     int64
	UserID int64
}

type GetUserAddressRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Lat          *float64
	Lng          *float64
}

// 取当前买家名下的一条收货地址，用于拍成 orders.receiver_snapshot。
//
// user_id 进 WHERE 是**越权过滤**，不是租户过滤：RLS 只保证这一行属于本店，
// 不保证它属于这个买家。契约里 address_id 用自增 id 对外，防越权靠的正是
// 服务端按 user_id 强制过滤（数据模型 §9 的约定 4）。
//
// lat / lng（00100）：下单与试算拿它判「地址在不在门店围栏内」，不进快照。
// deleted_at IS NULL：地址是软删的，删掉的地址不能再用来下单。
// 历史订单不受影响 —— 它存的是快照，不是外键。
func (q *Queries) GetUserAddress(ctx context.Context, arg GetUserAddressParams) (GetUserAddressRow, error) {
	row := q.db.QueryRow(ctx, getUserAddress, arg.ID, arg.UserID)
	var i GetUserAddressRow
	err := row.Scan(
		&i.ID,
		&i.ReceiverName,
		&i.Phone,
		&i.Province,
		&i.City,
		&i.District,
		&i.Street,
		&i.Detail,
		&i.RegionCode,
		&i.PostalCode,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getUserDefaultAddress = `-- name: GetUserDefaultAddress :one
SELECT id, receiver_name, phone, province, city, district, street, detail,
       region_code, postal_code, lat, lng
  FROM user_addresses
 WHERE user_id = $1
   AND is_default
   AND deleted_at IS NULL
`

type GetUserDefaultAddressRow struct {
	ID           int64
	ReceiverName string
	Phone        string
	Province     string
	City         string
	District     string
	Street       string
	Detail       string
	RegionCode   *string
	PostalCode   *string
	Lat          *float64
	Lng          *float64
}

// 当前买家的默认收货地址（至多一条，uk_user_addresses_default）。购物车没指名地址时
// 按它算运费（00056）。没有默认地址是合法状态（新用户零个地址），调用方当作「没有地址」。
func (q *Queries) GetUserDefaultAddress(ctx context.Context, userID int64) (GetUserDefaultAddressRow, error) {
	row := q.db.QueryRow(ctx, getUserDefaultAddress, userID)
	var i GetUserDefaultAddressRow
	err := row.Scan(
		&i.ID,
		&i.ReceiverName,
		&i.Phone,
		&i.Province,
		&i.City,
		&i.District,
		&i.Street,
		&i.Detail,
		&i.RegionCode,
		&i.PostalCode,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getUserOrderByNo = `-- name: GetUserOrderByNo :one
SELECT id, order_no, user_id, store_id, region_id, status,
       goods_amount_cents, freight_cents, freight_discount_cents,
       discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
       expire_at, paid_at, shipped_at, finished_at, created_at, user_coupon_id,
       coupon_name, promotion_discount_cents, promotions
  FROM orders
 WHERE order_no = $1
   AND user_id = $2
   AND status <> 0
`

type GetUserOrderByNoParams struct {
	OrderNo string
	UserID  *int64
}

type GetUserOrderByNoRow struct {
	ID                     int64
	OrderNo                string
	UserID                 *int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
}

// 订单详情 / 发起支付共用：按单号取**当前买家自己**的订单。
//
// 与上面那条 GetOrderByNo 分开而不是加个参数：那一条是 SAGA 分支与支付回调用的，
// 它们跑在没有买家身份的上下文里（协调器重放、渠道回调），给它加一个 user_id
// 参数只会逼那两处传一个假的。两条查询、两个调用面，谁也伪造不了对方的条件。
//
// 查不到与「不是你的」回同一个 404：order_no 是 72 bit 随机不可枚举的，
// 分开报会把它变成一个「这个单号存不存在」的判定器。
func (q *Queries) GetUserOrderByNo(ctx context.Context, arg GetUserOrderByNoParams) (GetUserOrderByNoRow, error) {
	row := q.db.QueryRow(ctx, getUserOrderByNo, arg.OrderNo, arg.UserID)
	var i GetUserOrderByNoRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UserCouponID,
		&i.CouponName,
		&i.PromotionDiscountCents,
		&i.Promotions,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (payment_no, order_id, channel, amount_cents, status,
                      channel_txn_id, notify_payload, paid_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, payment_no, status
`

type InsertPaymentParams struct {
	PaymentNo     string
	OrderID       int64
	Channel       int16
	AmountCents   int64
	Status        int16
	ChannelTxnID  *string
	NotifyPayload []byte
	PaidAt        pgtype.Timestamptz
}

type InsertPaymentRow struct {
	ID        int64
	PaymentNo string
	Status    int16
}

// 支付单落库。**一条光秃秃的 INSERT，刻意不带 ON CONFLICT**。
//
// 幂等由 uk_payments_channel_txn（00014）兜底：重复回调撞唯一冲突，
// 由 Go 侧按约束名把它挑成 repository.ErrDuplicateChannelTxn，其余 23505
// 原样上浮。写成 `ON CONFLICT DO NOTHING` 会顺带吞掉 payment_no 撞车 ——
// 那是熵源坏了，必须炸出来。完整论证在 00014 的文件头。
//
// 租户列不出现在这条语句里（00014 的 DEFAULT current_merchant()）。
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (InsertPaymentRow, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.PaymentNo,
		arg.OrderID,
		arg.Channel,
		arg.AmountCents,
		arg.Status,
		arg.ChannelTxnID,
		arg.NotifyPayload,
		arg.PaidAt,
	)
	var i InsertPaymentRow
	err := row.Scan(&i.ID, &i.PaymentNo, &i.Status)
	return i, err
}

const isOrderPlaced = `-- name: IsOrderPlaced :one
SELECT (placed_at IS NOT NULL)::boolean AS placed FROM orders WHERE id = $1
`

// 发起支付用：下单 SAGA 走完收尾分支了没有。
func (q *Queries) IsOrderPlaced(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isOrderPlaced, id)
	var placed bool
	err := row.Scan(&placed)
	return placed, err
}

const listExpiredDraftOrders = `-- name: ListExpiredDraftOrders :many
SELECT id, order_no, store_id, user_id
  FROM orders
 WHERE status = 0 AND expire_at < now()
 ORDER BY expire_at
 LIMIT $1
`

type ListExpiredDraftOrdersRow struct {
	ID      int64
	OrderNo string
	StoreID int64
	UserID  *int64
}

// 第二类：孤儿草稿（00013 文件头那笔明写的欠账）。它们**没进过 SAGA**，
// 一件库存都没扣，所以只关单、不回补。
//
// 走 idx_orders_draft_expire（00015，WHERE status = 0）。
// user_id 只是与上一条同形（两条共用 ExpiredOrder）；孤儿草稿不放回任何东西。
func (q *Queries) ListExpiredDraftOrders(ctx context.Context, limit int32) ([]ListExpiredDraftOrdersRow, error) {
	rows, err := q.db.Query(ctx, listExpiredDraftOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredDraftOrdersRow
	for rows.Next() {
		var i ListExpiredDraftOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.StoreID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many

SELECT id, order_no, store_id, user_id
  FROM orders
 WHERE status = 10 AND expire_at < now()
 ORDER BY expire_at
 LIMIT $1
`

type ListExpiredPendingOrdersRow struct {
	ID      int64
	OrderNo string
	StoreID int64
	UserID  *int64
}

// ---------------------------------------------------------------------------
// 超时补偿定时任务（Task 6）。
//
// 两类行、两条扫描、两种处置，逐条的理由写在 internal/service/sweep.go。
// 这里要说的只有一条形状上的：**扫描与处置是分开的两步，而处置那一步带着
// 与扫描完全相同的谓词**。扫出来的订单号在被处理之前可能已经被支付回调改掉了
// （那是一次真实的竞态，不是理论），所以真正决定「这一单归谁」的是处置那条
// UPDATE 的 rows_affected，不是扫描的结果。
// ---------------------------------------------------------------------------
// 第一类：正常的超时未支付。它们进过 SAGA，库存已经真实扣减，要回补。
//
// store_id 一起取：回补要回补到**当初扣减的那一家店**，而这条清扫路径跑在
// 任何请求之外（定时任务），它对那一单的记忆只有这几列。
//
// 走 idx_orders_status_expire（00006，WHERE status = 10）。
// 按 expire_at 升序：过期最久的先处理，否则一个持续入单的租户能让最老的那批
// 永远排在后面。
//
// user_id（00058）：按活动价成交的行关单时要放回每人限购，那个计数按买家记。
func (q *Queries) ListExpiredPendingOrders(ctx context.Context, limit int32) ([]ListExpiredPendingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredPendingOrdersRow
	for rows.Next() {
		var i ListExpiredPendingOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.StoreID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsForBranch = `-- name: ListOrderItemsForBranch :many
SELECT sku_id, quantity, price_promotion_id
  FROM order_items
 WHERE order_id = $1
 ORDER BY sku_id
`

type ListOrderItemsForBranchRow struct {
	SkuID            int64
	Quantity         int32
	PricePromotionID *int64
}

// 取一笔订单的全部行，供库存分支重建「扣减意图」。
//
// 这条查询就是硬约束二的落点：分支拿不到业务载荷，扣减意图只能从库里读回来。
// 按 sku_id 排序而不是 id：两个分支（正向与补偿）必须按同一个顺序拿行锁，
// 否则两笔互相交叉的订单在高并发下能互相死锁。
//
// price_promotion_id（00058）：这一行按限时折扣 / 秒杀价成交时，库存分支在同一个事务里
// 扣它的活动配额与每人限购，补偿与关单时放回 —— 与库存同进同出。
func (q *Queries) ListOrderItemsForBranch(ctx context.Context, orderID int64) ([]ListOrderItemsForBranchRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsForBranch, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsForBranchRow
	for rows.Next() {
		var i ListOrderItemsForBranchRow
		if err := rows.Scan(&i.SkuID, &i.Quantity, &i.PricePromotionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsForDetail = `-- name: ListOrderItemsForDetail :many
SELECT id, sku_id, product_id, title_snapshot, spec_snapshot, image_snapshot,
       price_cents, quantity, amount_cents, discount_cents, refunded_qty,
       list_price_cents, price_promotion_id, promotion_discount_cents
  FROM order_items
 WHERE order_id = $1
 ORDER BY id
`

type ListOrderItemsForDetailRow struct {
	ID                     int64
	SkuID                  int64
	ProductID              int64
	TitleSnapshot          string
	SpecSnapshot           []byte
	ImageSnapshot          *string
	PriceCents             int64
	Quantity               int32
	AmountCents            int64
	DiscountCents          int64
	RefundedQty            int32
	ListPriceCents         int64
	PricePromotionID       *int64
	PromotionDiscountCents int64
}

// 订单详情里的行。与 ListOrderItemsForBranch 分开：那一条只取 (sku_id, quantity)
// 并按 sku_id 排序，因为它是**库存分支拿行锁的顺序**（改了会死锁）。
// 这一条取的是展示用的全部快照列，按 id 排序 —— 两者的排序有完全不同的理由，
// 合成一条之后改其中一个会静默改掉另一个。
func (q *Queries) ListOrderItemsForDetail(ctx context.Context, orderID int64) ([]ListOrderItemsForDetailRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsForDetail, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsForDetailRow
	for rows.Next() {
		var i ListOrderItemsForDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.ProductID,
			&i.TitleSnapshot,
			&i.SpecSnapshot,
			&i.ImageSnapshot,
			&i.PriceCents,
			&i.Quantity,
			&i.AmountCents,
			&i.DiscountCents,
			&i.RefundedQty,
			&i.ListPriceCents,
			&i.PricePromotionID,
			&i.PromotionDiscountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForOrder = `-- name: ListPaymentsForOrder :many
SELECT payment_no, channel, amount_cents, status, paid_at
  FROM payments
 WHERE order_id = $1
 ORDER BY id
`

type ListPaymentsForOrderRow struct {
	PaymentNo   string
	Channel     int16
	AmountCents int64
	Status      int16
	PaidAt      pgtype.Timestamptz
}

// 这一单的全部支付尝试（契约的 OrderDetail.payments）。
//
// 走 idx_payments_order（00014）。按 id 升序：对账时人要看的是「先发生了什么」。
func (q *Queries) ListPaymentsForOrder(ctx context.Context, orderID int64) ([]ListPaymentsForOrderRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsForOrderRow
	for rows.Next() {
		var i ListPaymentsForOrderRow
		if err := rows.Scan(
			&i.PaymentNo,
			&i.Channel,
			&i.AmountCents,
			&i.Status,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUsForPricing = `-- name: ListSKUsForPricing :many

SELECT s.id, s.product_id, s.spec_values, v.price_cents, s.image_url,
       p.title, p.brand_id, c.path AS category_path,
       COALESCE(img.upload_id, 0)::bigint AS main_image_upload_id
  FROM skus s
  JOIN products p ON p.id = s.product_id
  JOIN sku_prices_by_store v ON v.sku_id = s.id AND v.store_id = $1
  LEFT JOIN LATERAL (
        SELECT pi.upload_id FROM product_images pi
         WHERE pi.product_id = p.id
         ORDER BY pi.sort_order, pi.id
         LIMIT 1
       ) img ON TRUE
  LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
 WHERE s.id = ANY($2::bigint[])
   AND s.status = 1
   AND s.deleted_at IS NULL
   AND p.status = 1
   AND p.deleted_at IS NULL
   AND NOT EXISTS (SELECT 1 FROM region_product_overrides ro
                    WHERE ro.region_id = $3
                      AND ro.product_id = p.id AND ro.status = 0)
   AND NOT EXISTS (SELECT 1 FROM store_product_overrides so
                    WHERE so.store_id = $1
                      AND so.product_id = p.id AND so.status = 0)
`

type ListSKUsForPricingParams struct {
	StoreID  int64
	SkuIds   []int64
	RegionID int64
}

type ListSKUsForPricingRow struct {
	ID                int64
	ProductID         int64
	SpecValues        []byte
	PriceCents        int64
	ImageUrl          *string
	Title             string
	BrandID           *int64
	CategoryPath      *string
	MainImageUploadID int64
}

// 下单主链路的查询：试算、建单、SAGA 两个分支各自要读写的东西。
//
// 全文没有一处 WHERE 写租户，也没有一处 INSERT 写 merchant_id：租户由 RLS 在
// 数据库层过滤，写入那一列由 DEFAULT current_merchant() 补（00013）。理由见
// db/queries/products.sql 与 scripts/check_query_tenancy.py 的文件头 ——
// 应用层再加一遍条件之后，「RLS 到底有没有生效」就再也测不出来了。
//
// 注释里一个反引号都不许有，理由见 db/queries/inventories.sql 的第三条说明。
// 按一批 sku_id 取定价与快照素材。**试算与真下单共用这一条**。
//
// 共用不是为了少写代码，是为了让「试算的钱」与「成交的钱」不可能不一样：
// 两条查询各写一份的话，哪天有人只给其中一条补上「下架商品不可售」，
// 用户会在试算里看到一个价，在订单里看到另一个价，而两边各自都是自洽的。
//
// 三个过滤条件决定了「什么叫可售」：
//
//	· s.status = 1     SKU 本身在售；
//	· s.deleted_at IS NULL  SKU 没被软删（M4 补，00018 给 skus 加了这一列）；
//	· p.status = 1     商品在架（草稿商品的 SKU 不可下单）；
//	· p.deleted_at IS NULL  商品没被软删。
//
// 少了 s.deleted_at 那一条的后果很具体：商家删掉一个规格之后它仍然下得了单，
// 而它已经不在任何一个后台视图里 —— 商家看不到这笔订单卖的是什么。
//
// 过滤掉的行不会出现在结果里，于是调用方拿到的行数少于请求的 sku 数 ——
// 服务层据此报「这些 SKU 不可售」，而不是悄悄少算一行钱。
//
// 不在这里 JOIN inventories：试算是**无副作用的金额试算**，不是可售性承诺。
// 把库存并进来会让试算看起来像一次预留，而 SAGA 的正向阶段才是真正的判定点
// （架构 §5：超卖为零、少卖存在，正是因为扣减发生在那里而不是这里）。
//
// ### 本轮（00020）取价口换成了 sku_prices_by_store 视图
//
// 这是「试算与下单共用同一份定价」那条纪律在三层定价下的兑现：视图是全仓库
// 唯一一处写 COALESCE(门店价, 大区价, 基准价) 的地方，而商品列表、详情、
// 检索结果也都经过它。取 skus.price_cents 的话，**列表显示的价与下单成交的价
// 会在「这家店定了自己的价」的那些商品上分叉** —— 而那正是最不可能被夹具
// 覆盖到的一种。
//
// 两条 NOT EXISTS 也一起进来：一件这家店（或它所在大区）不卖的商品
// 在这里就不该有价。少了它们，试算会给出一个金额，而 SAGA 的库存分支随后以
// ErrSKUNotSoldInStore 拒掉整单 —— 用户看到的是「试算成功、下单失败」，
// 而两次调用之间什么都没变。可售性的判定必须和金额在同一条查询里。
//
// JOIN 视图而不是 LEFT JOIN：视图对每一个 (未软删门店 × 未软删 SKU) 都恰好
// 有一行，缺行意味着门店或 SKU 已经不在了，而那时这一行本来就不该可售 ——
// 少掉的行会让调用方拿到「这些 SKU 不可售」，那正是对的答案。
//
// ### 00026 多取两列：brand_id 与所属分类的 path
//
// 券的适用范围按商品、分类（含子孙）、品牌挑行（数据模型 §7），挑行要的素材
// 从**这一条**取，而不是另开一条查询：券的计算与定价共用同一份输入，
// 试算与下单才不可能在「这一行算不算适用」上分叉。分类按 path 前缀判子孙，
// 与 GET /products?category_id= 同一个语义（products.sql 文件头）。
// LEFT JOIN 且只认未软删的分类：分类删了，category_path 为 NULL，
// 分类范围的规则就命中不了这一行 —— 与列表页「分类已删就是空列表」一致。
// main_image_upload_id：商品主图（product_images 的第一张）。SKU 自己没有图时，订单行快照用它 ——
// 否则种子商品这类「图挂在商品上」的订单行永远没有图（买家端订单 / 售后行只剩单字占位）。
func (q *Queries) ListSKUsForPricing(ctx context.Context, arg ListSKUsForPricingParams) ([]ListSKUsForPricingRow, error) {
	rows, err := q.db.Query(ctx, listSKUsForPricing, arg.StoreID, arg.SkuIds, arg.RegionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSKUsForPricingRow
	for rows.Next() {
		var i ListSKUsForPricingRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SpecValues,
			&i.PriceCents,
			&i.ImageUrl,
			&i.Title,
			&i.BrandID,
			&i.CategoryPath,
			&i.MainImageUploadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many

SELECT id, order_no, user_id, store_id, region_id, status,
       goods_amount_cents, freight_cents, freight_discount_cents,
       discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
       expire_at, paid_at, shipped_at, finished_at, created_at, user_coupon_id,
       coupon_name, promotion_discount_cents, promotions
  FROM orders
 WHERE user_id = $1
   AND status <> 0
   AND ($2::smallint IS NULL OR status = $2::smallint)
   AND ($3::smallint IS NULL
        OR refund_status = $3::smallint)
 ORDER BY created_at DESC, id DESC
 LIMIT $5 OFFSET $4
`

type ListUserOrdersParams struct {
	UserID       *int64
	Status       *int16
	RefundStatus *int16
	PageOffset   int32
	PageLimit    int32
}

type ListUserOrdersRow struct {
	ID                     int64
	OrderNo                string
	UserID                 *int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
}

// ---------------------------------------------------------------------------
// 买家侧读接口：GET /orders（我的订单）与 GET /orders/{order_no}（订单详情）。
//
// 这一段里每一条查询都带 user_id，而这**不是**租户过滤，别把它和
// check_query_tenancy.py 挡的那件事混起来：
//
//	· 租户过滤（merchant_id）由 RLS 做，应用层再加一遍会让 RLS 变得测不出来；
//	· 买家过滤（user_id）RLS 做不了 —— 策略只认 current_merchant()，
//	  它管不到「同一家店里 A 买家和 B 买家」这一层。
//
// 也就是说：去掉 user_id，跨租户仍然是安全的（RLS 还在），而**同一家店的任意
// 买家可以凭一个自增页码翻遍全店的订单**。这是本组接口唯一一处只能靠查询条件
// 守住的越权面，与 GetUserAddress 上那条注释说的是同一件事（数据模型 §9 约定 4）。
// ---------------------------------------------------------------------------
// 我的订单，一页。
//
// status <> 0 不是可选的：0 是「创建中」，是 SAGA 还没跑完的中间态
// （00013 与 service/order.go 的文件头）。它一旦出现在「我的订单」里，用户会看到
// 一笔既不能支付也不能取消的订单，而它可能在下一秒被补偿关掉。
//
// 两个筛选条件用 sqlc.narg 做成可空参数：传 NULL 就是不筛。写成两条查询
// （筛的和不筛的）的话，「total 与 items 用的是同一套谓词」这条性质要靠人维护，
// 而它一旦破掉的症状是客户端一直翻到一页空的。
//
// 排序 created_at DESC 之后再按 id DESC：同一毫秒内建的两笔订单在只按时间排序时
// 顺序是不确定的，而不确定的顺序会让同一页在两次请求之间变样 —— 分页最经典的
// 那种「第二页又看到了第一页的那一单」。
func (q *Queries) ListUserOrders(ctx context.Context, arg ListUserOrdersParams) ([]ListUserOrdersRow, error) {
	rows, err := q.db.Query(ctx, listUserOrders,
		arg.UserID,
		arg.Status,
		arg.RefundStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOrdersRow
	for rows.Next() {
		var i ListUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.StoreID,
			&i.RegionID,
			&i.Status,
			&i.GoodsAmountCents,
			&i.FreightCents,
			&i.FreightDiscountCents,
			&i.DiscountCents,
			&i.PayableCents,
			&i.PaidCents,
			&i.RefundedCents,
			&i.RefundStatus,
			&i.ExpireAt,
			&i.PaidAt,
			&i.ShippedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UserCouponID,
			&i.CouponName,
			&i.PromotionDiscountCents,
			&i.Promotions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderStatus = `-- name: LockOrderStatus :one
SELECT status FROM orders WHERE id = $1 FOR UPDATE
`

// 下单 SAGA 收尾分支（库存分支之后）开头用：锁住订单行再看它还是不是 10 待支付。
//
// 审查发现的窗口：建单分支先把订单推到 10，库存分支才扣。库存分支一次说不清的失败
// （死锁、断连、库存服务不在）会被协调器重试，而重试之前订单已经是 10、单号可能已经外泄
// （WaitFinal 超时回 409 in-flight）—— 买家这时取消、或超时任务关单。拆分前这把锁在库存分支里，
// 让「取消」与「扣减」串行；拆分后库存分支在另一个库里，看不见订单，守卫分成两半
// （service/order_saga.go 的文件头）：库存服务按流水拒绝「已经被关单释放过」的订单，
// 这里在扣减之后再看一眼订单 —— 已经关掉了就确定性失败，全局补偿按流水把刚扣的放回去。
func (q *Queries) LockOrderStatus(ctx context.Context, id int64) (int16, error) {
	row := q.db.QueryRow(ctx, lockOrderStatus, id)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const markIdempotencyInFlightOrder = `-- name: MarkIdempotencyInFlightOrder :execrows
UPDATE idempotency_keys
   SET response_body = $5::jsonb,
       updated_at   = now()
 WHERE scope = $1 AND subject_kind = $2 AND subject_id = $3 AND idem_key = $4
   AND status = 0
`

type MarkIdempotencyInFlightOrderParams struct {
	Scope       string
	SubjectKind int16
	SubjectID   int64
	IdemKey     string
	Column5     []byte
}

// 把「这笔逻辑请求对应哪个草稿单号」记进处理中那一行（2026-10-08 破坏性测试）。
//
// 它写的是 response_body，但 status 仍是 0：那一列在这里临时当**「还没最终」的
// 暂存位**用，与「存档」是两件事（存档只写 status 1/2）。读回方看到 status=0
// 却带着 order_no，就知道这一单已经落库、只是等 SAGA 的结果。
//
// 为什么要这一列：SAGA 等到 15 秒还没终态时，请求已经带着 409 返回了，
// 而 SAGA 之后**可能成功**。没有这一列，那个成功没人回填，这把钥匙在
// 24 小时里一直回 409 —— 客户端被迫换钥匙，于是重复下单。
// 记下单号之后，重试方能自己查库定论，不必依赖当时那个请求还活着
// （它也可能已经随进程崩了，这一条同样能治）。
//
// 只在 status 仍是 0 时动手：已经被写成成功/失败存档的行不再抢。
// 返回 0 行说明这一行已经不在处理中，调用方按「有人已经回填过」处理。
func (q *Queries) MarkIdempotencyInFlightOrder(ctx context.Context, arg MarkIdempotencyInFlightOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, markIdempotencyInFlightOrder,
		arg.Scope,
		arg.SubjectKind,
		arg.SubjectID,
		arg.IdemKey,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderPlaced = `-- name: MarkOrderPlaced :exec
UPDATE orders SET placed_at = now() WHERE id = $1 AND placed_at IS NULL
`

// 收尾分支在 LockOrderStatus 之后、同一个屏障事务里写：库存已扣成、订单仍在 10 —— 这一单下成了。
// 发起支付只认写过它的单（00085 的文件头）。IS NULL 让协调器重放时不改第一次的时刻。
func (q *Queries) MarkOrderPlaced(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOrderPlaced, id)
	return err
}

const promoteOrderDraft = `-- name: PromoteOrderDraft :execrows
UPDATE orders SET status = 10 WHERE order_no = $1 AND status = 0
`

// 建单分支的正向：0 创建中 → 10 待支付。
//
// WHERE 带上 status = 0 而不是无条件赋值：这条语句会被协调器重放，
// 而一笔已经被补偿关到 90 的订单不该被一次迟到的正向重新开成待支付。
// 屏障已经挡住重复执行，这一条是第二道 —— 两道的失效方式不一样。
//
// 返回受影响行数：0 行说明这一单不在本租户可见，或者状态已经不是 0，
// 两者都不该被当成成功。
func (q *Queries) PromoteOrderDraft(ctx context.Context, orderNo string) (int64, error) {
	result, err := q.db.Exec(ctx, promoteOrderDraft, orderNo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :execrows
DELETE FROM idempotency_keys
 WHERE scope = $1 AND subject_kind = $2 AND subject_id = $3 AND idem_key = $4 AND status = 0
`

type ReleaseIdempotencyKeyParams struct {
	Scope       string
	SubjectKind int16
	SubjectID   int64
	IdemKey     string
}

// 撤销一次幂等键抢占。**只撤处理中的那些**（status = 0）。
//
// 它只有一个调用点：SubmitSaga 失败时（service/order.go 第二段）。那一刻
// 抢占记录与订单草稿都已经提交了，而 SAGA 一个分支都没跑过 —— 不撤的话，
// 客户端拿同一把钥匙重试会一直撞 409 处理中，直到 24 小时后 expire_at 过期。
// 而 Idempotency-Key 的语义恰恰是「同一个逻辑请求的重试用同一把钥匙」，
// 所以那是把客户端**正确的**行为锁死了。
//
// 用 DELETE 而不是「写一条失败存档」：存档是给「业务真的执行过」的失败用的
// （§12），而这里业务一次都没执行。留一条失败存档会让重试拿到一个回放的错误，
// 那比 409 更糟 —— 客户端会以为下单真的失败过。
//
// `status = 0` 在谓词里不是冗余：撤销与「另一个并发请求刚刚把它推到成功」
// 之间有窗口（虽然同一把钥匙上不该有两个并发请求），而删掉一条已成功的存档
// 等于把一笔已经建成的订单的幂等证据抹掉，下一次重试会建出第二笔订单。
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseIdempotencyKey,
		arg.Scope,
		arg.SubjectKind,
		arg.SubjectID,
		arg.IdemKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleOrder = `-- name: SettleOrder :execrows

UPDATE orders SET status = 20, paid_cents = $2, paid_at = $3
 WHERE order_no = $1 AND status = 10
`

type SettleOrderParams struct {
	OrderNo   string
	PaidCents int64
	PaidAt    pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// 支付回调（Task 7）。
// ---------------------------------------------------------------------------
// 支付成功：10 待支付 → 20 已支付，记下实收与到账时间。
//
// `status = 10` 在谓词里，与上面那条关单互为对手：两者都是条件 UPDATE，
// 撞在同一行上时由行锁排队，**恰好一个返回 1**。这就是「超时任务与支付回调
// 撞车」那条竞态的全部处理 —— 不是在应用层加锁，是让数据库回答「谁赢了」。
//
// 返回 0 行不是错误，是一种要**大声记下来**的事实：钱已经到账了，而这一单
// 已经不在待支付上（被超时关掉了，或者已经付过一次了）。处置见 service/payment.go。
//
// paid_cents 直接赋值而不是累加：本轮不支持部分支付（契约里也没有），
// 累加会让一笔重复到账把 chk_amount 的 `refunded_cents <= paid_cents` 撑出
// 一个不该有的空间。
func (q *Queries) SettleOrder(ctx context.Context, arg SettleOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleOrder, arg.OrderNo, arg.PaidCents, arg.PaidAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
