// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_returns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPaymentReturns = `-- name: CountPaymentReturns :one
SELECT count(*) FROM payment_returns r
 WHERE ($1::smallint IS NULL OR r.status = $1::smallint)
`

func (q *Queries) CountPaymentReturns(ctx context.Context, status *int16) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentReturns, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPaymentReturn = `-- name: InsertPaymentReturn :execrows

INSERT INTO payment_returns (return_no, payment_id, order_id, channel, amount_cents, reason)
SELECT $1, p.id, p.order_id, p.channel, p.amount_cents, $2
  FROM payments p
 WHERE p.id = $3
ON CONFLICT ON CONSTRAINT uk_payment_returns_payment DO NOTHING
`

type InsertPaymentReturnParams struct {
	ReturnNo  string
	Reason    int16
	PaymentID int64
}

// 多收款退回（00150，service/payment_return.go）。一个 merchant_id 都没有：租户由 RLS 过滤。
// 给一笔订单不认的到账开退回单。同一笔支付至多一张（uk_payment_returns_payment）：已有就不再开（0 行）。
func (q *Queries) InsertPaymentReturn(ctx context.Context, arg InsertPaymentReturnParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentReturn, arg.ReturnNo, arg.Reason, arg.PaymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPaymentReturns = `-- name: ListPaymentReturns :many
SELECT r.id, r.return_no, r.payment_id, r.order_id, r.channel, r.amount_cents, r.reason, r.status,
       r.channel_refund_id, r.attempts, r.last_error, r.created_at, r.updated_at, r.returned_at,
       o.order_no, p.channel_txn_id AS payment_txn_id
  FROM payment_returns r
  JOIN orders o   ON o.id = r.order_id
  JOIN payments p ON p.id = r.payment_id
 WHERE ($1::smallint IS NULL OR r.status = $1::smallint)
 ORDER BY r.created_at DESC, r.id DESC
 LIMIT $3 OFFSET $2
`

type ListPaymentReturnsParams struct {
	Status     *int16
	PageOffset int32
	PageLimit  int32
}

type ListPaymentReturnsRow struct {
	ID              int64
	ReturnNo        string
	PaymentID       int64
	OrderID         int64
	Channel         int16
	AmountCents     int64
	Reason          int16
	Status          int16
	ChannelRefundID *string
	Attempts        int32
	LastError       *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ReturnedAt      pgtype.Timestamptz
	OrderNo         string
	PaymentTxnID    *string
}

// 后台「多收款退回」列表：新的在前，可按状态筛。
func (q *Queries) ListPaymentReturns(ctx context.Context, arg ListPaymentReturnsParams) ([]ListPaymentReturnsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentReturns, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentReturnsRow
	for rows.Next() {
		var i ListPaymentReturnsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReturnNo,
			&i.PaymentID,
			&i.OrderID,
			&i.Channel,
			&i.AmountCents,
			&i.Reason,
			&i.Status,
			&i.ChannelRefundID,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnedAt,
			&i.OrderNo,
			&i.PaymentTxnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentReturnsForOrder = `-- name: ListPaymentReturnsForOrder :many
SELECT r.id, r.return_no, r.payment_id, r.order_id, r.channel, r.amount_cents, r.reason, r.status,
       r.channel_refund_id, r.attempts, r.last_error, r.created_at, r.updated_at, r.returned_at,
       o.order_no, p.channel_txn_id AS payment_txn_id
  FROM payment_returns r
  JOIN orders o   ON o.id = r.order_id
  JOIN payments p ON p.id = r.payment_id
 WHERE r.order_id = $1
 ORDER BY r.id
`

type ListPaymentReturnsForOrderRow struct {
	ID              int64
	ReturnNo        string
	PaymentID       int64
	OrderID         int64
	Channel         int16
	AmountCents     int64
	Reason          int16
	Status          int16
	ChannelRefundID *string
	Attempts        int32
	LastError       *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ReturnedAt      pgtype.Timestamptz
	OrderNo         string
	PaymentTxnID    *string
}

// 买家订单详情上的「多付的钱已退回」。
func (q *Queries) ListPaymentReturnsForOrder(ctx context.Context, orderID int64) ([]ListPaymentReturnsForOrderRow, error) {
	rows, err := q.db.Query(ctx, listPaymentReturnsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentReturnsForOrderRow
	for rows.Next() {
		var i ListPaymentReturnsForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.ReturnNo,
			&i.PaymentID,
			&i.OrderID,
			&i.Channel,
			&i.AmountCents,
			&i.Reason,
			&i.Status,
			&i.ChannelRefundID,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnedAt,
			&i.OrderNo,
			&i.PaymentTxnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentReturnsToSubmit = `-- name: ListPaymentReturnsToSubmit :many
SELECT id, return_no FROM payment_returns WHERE status = 10 ORDER BY id LIMIT $1
`

type ListPaymentReturnsToSubmitRow struct {
	ID       int64
	ReturnNo string
}

// 待提交（10）的退回单，最早的在前。
func (q *Queries) ListPaymentReturnsToSubmit(ctx context.Context, rowLimit int32) ([]ListPaymentReturnsToSubmitRow, error) {
	rows, err := q.db.Query(ctx, listPaymentReturnsToSubmit, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentReturnsToSubmitRow
	for rows.Next() {
		var i ListPaymentReturnsToSubmitRow
		if err := rows.Scan(&i.ID, &i.ReturnNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnacceptedPayments = `-- name: ListUnacceptedPayments :many
SELECT p.id AS payment_id, o.status AS order_status, (o.paid_at IS NOT NULL)::boolean AS order_paid,
       p.amount_cents, o.payable_cents
  FROM payments p
  JOIN orders o ON o.id = p.order_id
 WHERE p.status = 1
   AND NOT (o.paid_at IS NOT NULL AND p.amount_cents = o.paid_cents AND p.paid_at = o.paid_at)
   AND NOT EXISTS (SELECT 1 FROM payment_returns r WHERE r.payment_id = p.id)
 ORDER BY p.id
 LIMIT $1
`

type ListUnacceptedPaymentsRow struct {
	PaymentID    int64
	OrderStatus  int16
	OrderPaid    bool
	AmountCents  int64
	PayableCents int64
}

// 兜底扫描：渠道成功（status = 1）、但订单不认、也还没开退回单的到账。
// 「订单认的那一笔」与售后原路退回同一个判据（refunds.sql 的 FindSettledPayment）：金额与到账时间对得上
// orders.paid_cents / paid_at。订单还在待支付（paid_at 为空）时，任何到账都是不认的（只可能是金额不符）。
// 返回订单状态，调用方据此定原因。
func (q *Queries) ListUnacceptedPayments(ctx context.Context, rowLimit int32) ([]ListUnacceptedPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listUnacceptedPayments, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnacceptedPaymentsRow
	for rows.Next() {
		var i ListUnacceptedPaymentsRow
		if err := rows.Scan(
			&i.PaymentID,
			&i.OrderStatus,
			&i.OrderPaid,
			&i.AmountCents,
			&i.PayableCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentReturnByNo = `-- name: LockPaymentReturnByNo :one
SELECT r.id, r.return_no, r.payment_id, r.order_id, r.channel, r.amount_cents, r.reason, r.status,
       r.channel_refund_id, r.attempts, r.last_error, r.created_at, r.updated_at, r.returned_at,
       o.order_no, p.channel_txn_id AS payment_txn_id
  FROM payment_returns r
  JOIN orders o   ON o.id = r.order_id
  JOIN payments p ON p.id = r.payment_id
 WHERE r.return_no = $1
   FOR UPDATE OF r
`

type LockPaymentReturnByNoRow struct {
	ID              int64
	ReturnNo        string
	PaymentID       int64
	OrderID         int64
	Channel         int16
	AmountCents     int64
	Reason          int16
	Status          int16
	ChannelRefundID *string
	Attempts        int32
	LastError       *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ReturnedAt      pgtype.Timestamptz
	OrderNo         string
	PaymentTxnID    *string
}

func (q *Queries) LockPaymentReturnByNo(ctx context.Context, returnNo string) (LockPaymentReturnByNoRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentReturnByNo, returnNo)
	var i LockPaymentReturnByNoRow
	err := row.Scan(
		&i.ID,
		&i.ReturnNo,
		&i.PaymentID,
		&i.OrderID,
		&i.Channel,
		&i.AmountCents,
		&i.Reason,
		&i.Status,
		&i.ChannelRefundID,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnedAt,
		&i.OrderNo,
		&i.PaymentTxnID,
	)
	return i, err
}

const markPaymentReturnAttemptFailed = `-- name: MarkPaymentReturnAttemptFailed :exec
UPDATE payment_returns SET attempts = attempts + 1, last_error = $1 WHERE id = $2 AND status = 10
`

type MarkPaymentReturnAttemptFailedParams struct {
	LastError *string
	ID        int64
}

// 提交失败（渠道报错 / 没配密钥），留在 10 等下一轮重试，记下原因给后台看。
func (q *Queries) MarkPaymentReturnAttemptFailed(ctx context.Context, arg MarkPaymentReturnAttemptFailedParams) error {
	_, err := q.db.Exec(ctx, markPaymentReturnAttemptFailed, arg.LastError, arg.ID)
	return err
}

const markPaymentReturnSubmitted = `-- name: MarkPaymentReturnSubmitted :exec
UPDATE payment_returns SET status = 30, attempts = attempts + 1, last_error = NULL WHERE id = $1 AND status = 10
`

// 交给了渠道、等回调（真实渠道）。
func (q *Queries) MarkPaymentReturnSubmitted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPaymentReturnSubmitted, id)
	return err
}

const settlePaymentReturn = `-- name: SettlePaymentReturn :execrows
UPDATE payment_returns
   SET status = 40, returned_at = now(), channel_refund_id = $1,
       notify_payload = $2
 WHERE id = $3 AND status IN (10, 30)
`

type SettlePaymentReturnParams struct {
	ChannelRefundID *string
	NotifyPayload   []byte
	ID              int64
}

// 渠道回调：退回成功。10（沙箱当场）或 30 → 40。
func (q *Queries) SettlePaymentReturn(ctx context.Context, arg SettlePaymentReturnParams) (int64, error) {
	result, err := q.db.Exec(ctx, settlePaymentReturn, arg.ChannelRefundID, arg.NotifyPayload, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
