// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_intents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActivePaymentIntent = `-- name: FindActivePaymentIntent :one

SELECT id, order_id, channel, channel_txn_id, amount_cents, status, created_at
  FROM payment_intents
 WHERE order_id = $1 AND status = 1
`

type FindActivePaymentIntentRow struct {
	ID           int64
	OrderID      int64
	Channel      int16
	ChannelTxnID string
	AmountCents  int64
	Status       int16
	CreatedAt    pgtype.Timestamptz
}

// 支付意图（00150，service/payment_intent.go）。一个 merchant_id 都没有：租户由 RLS 过滤。
// 这一单此刻有效的那个支付意图（至多一行：uk_payment_intents_active）。调用方已锁住订单行。
func (q *Queries) FindActivePaymentIntent(ctx context.Context, orderID int64) (FindActivePaymentIntentRow, error) {
	row := q.db.QueryRow(ctx, findActivePaymentIntent, orderID)
	var i FindActivePaymentIntentRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Channel,
		&i.ChannelTxnID,
		&i.AmountCents,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentIntent = `-- name: InsertPaymentIntent :exec
INSERT INTO payment_intents (order_id, channel, channel_txn_id, amount_cents)
VALUES ($1, $2, $3, $4)
`

type InsertPaymentIntentParams struct {
	OrderID      int64
	Channel      int16
	ChannelTxnID string
	AmountCents  int64
}

func (q *Queries) InsertPaymentIntent(ctx context.Context, arg InsertPaymentIntentParams) error {
	_, err := q.db.Exec(ctx, insertPaymentIntent,
		arg.OrderID,
		arg.Channel,
		arg.ChannelTxnID,
		arg.AmountCents,
	)
	return err
}

const markPaymentIntentSettled = `-- name: MarkPaymentIntentSettled :exec
UPDATE payment_intents SET status = 3, closed_at = now()
 WHERE channel = $1 AND channel_txn_id = $2 AND status IN (1, 2)
`

type MarkPaymentIntentSettledParams struct {
	Channel      int16
	ChannelTxnID string
}

// 回调入账时认领的那一个：已入账。流水号不是我们发的（渠道侧直接推来的）时一行都不改，那也对。
func (q *Queries) MarkPaymentIntentSettled(ctx context.Context, arg MarkPaymentIntentSettledParams) error {
	_, err := q.db.Exec(ctx, markPaymentIntentSettled, arg.Channel, arg.ChannelTxnID)
	return err
}

const supersedePaymentIntent = `-- name: SupersedePaymentIntent :exec
UPDATE payment_intents SET status = 2, closed_at = now() WHERE id = $1 AND status = 1
`

// 换渠道：旧的作废（真实渠道要先调它的关单接口，沙箱不需要）。
func (q *Queries) SupersedePaymentIntent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, supersedePaymentIntent, id)
	return err
}
