// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_store_stock.sql

package db

import (
	"context"
)

const listOnSaleSKUsForStockFlags = `-- name: ListOnSaleSKUsForStockFlags :many
SELECT s.product_id, s.id
  FROM skus s
  JOIN products p ON p.id = s.product_id
 WHERE s.deleted_at IS NULL AND s.status = 1
   AND p.deleted_at IS NULL AND p.status = 1
 ORDER BY s.product_id, s.id
`

type ListOnSaleSKUsForStockFlagsRow struct {
	ProductID int64
	ID        int64
}

// 全部在架商品的在售 SKU（全量刷新用）。判据与 ListOnSaleSKUsOfProducts 相同，只是不按商品过滤。
func (q *Queries) ListOnSaleSKUsForStockFlags(ctx context.Context) ([]ListOnSaleSKUsForStockFlagsRow, error) {
	rows, err := q.db.Query(ctx, listOnSaleSKUsForStockFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOnSaleSKUsForStockFlagsRow
	for rows.Next() {
		var i ListOnSaleSKUsForStockFlagsRow
		if err := rows.Scan(&i.ProductID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreIDsForStockFlags = `-- name: ListStoreIDsForStockFlags :many
SELECT st.id FROM stores st WHERE st.deleted_at IS NULL ORDER BY st.id
`

// 要刷新的门店：未软删的都刷（停业的也刷 —— 重新营业那一刻排序就是对的）。
func (q *Queries) ListStoreIDsForStockFlags(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStoreIDsForStockFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productOfSKU = `-- name: ProductOfSKU :one
SELECT s.product_id FROM skus s WHERE s.id = $1
`

func (q *Queries) ProductOfSKU(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, productOfSKU, id)
	var product_id int64
	err := row.Scan(&product_id)
	return product_id, err
}

const upsertProductStoreStock = `-- name: UpsertProductStoreStock :exec

INSERT INTO product_store_stock (store_id, product_id, in_stock)
SELECT $1::bigint,
       unnest($2::bigint[]),
       unnest($3::boolean[])
ON CONFLICT (store_id, product_id) DO UPDATE
   SET in_stock = EXCLUDED.in_stock
 WHERE product_store_stock.in_stock IS DISTINCT FROM EXCLUDED.in_stock
`

type UpsertProductStoreStockParams struct {
	StoreID    int64
	ProductIds []int64
	InStocks   []bool
}

// 门店 × 商品有没有货的冗余标记（00087），只给商品列表排序用。刷新见 service/stock_flags.go。
//
// 和这个目录里别的文件一样，**一个 merchant_id 都没有** —— 租户由 RLS 在数据库层过滤。
// 一家店的一批商品整批写。只在值变了时 UPDATE：每分钟一轮全量刷新，没变的行不该每轮都写一次。
// 两个数组在 SELECT 列表里并排 unnest（PG10 起按位置配对）：sqlc 认不了 FROM unnest(a, b) 的多参形式。
func (q *Queries) UpsertProductStoreStock(ctx context.Context, arg UpsertProductStoreStockParams) error {
	_, err := q.db.Exec(ctx, upsertProductStoreStock, arg.StoreID, arg.ProductIds, arg.InStocks)
	return err
}
