// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
  FROM products
 WHERE deleted_at IS NULL
   AND status = 1
`

// 同样刻意不带 WHERE merchant_id —— 理由与 ListProducts 一模一样。
//
// 契约的 200 响应是 PageMeta + items，而 PageMeta 的 total 是必填字段。
// 没有这条查询，total 就只能靠 len(items) 现编，那在「还有下一页」时是错的，
// 而且错得很安静：客户端据此算出的总页数会少，最后几页谁也翻不到。
//
// 条件必须与 ListProducts 逐字一致：两边只要有一处不同，total 数的就不是
// 列表实际会分出来的那批行。
func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, title, subtitle, min_price_cents, max_price_cents,
       total_stock, sales_count, status
  FROM products
 WHERE deleted_at IS NULL
   AND status = 1
 ORDER BY published_at DESC NULLS LAST, id DESC
 LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	ID            int64
	Title         string
	Subtitle      *string
	MinPriceCents int64
	MaxPriceCents int64
	TotalStock    int32
	SalesCount    int32
	Status        int16
}

// 刻意不带 WHERE merchant_id —— 租户由 RLS 在数据库层过滤。
//
// 这不是偷懒：应用层再加一遍条件会让「RLS 是否真的生效」变得测不出来。
// 两层都在时，跨租户读不到数据既可能是 RLS 拦住了，也可能只是 WHERE 拦住了，
// 而 RLS 失效不报错、不变慢、不留痕迹 —— 唯一能发现它的测试恰好被 WHERE 挡住了。
//
// 进入这条查询的唯一入口是 repository.WithTenant，它保证事务里已经
// SET LOCAL app.merchant_id；没设的话 current_merchant() 会抛 42501。
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.TotalStock,
			&i.SalesCount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
