// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPromotionPurchase = `-- name: AddPromotionPurchase :execrows
INSERT INTO promotion_purchases (promotion_id, sku_id, user_id, qty)
SELECT $1, $2, $3, $4::int
 WHERE $4::int <= $5::int
    ON CONFLICT ON CONSTRAINT pk_promotion_purchases
    DO UPDATE SET qty = promotion_purchases.qty + EXCLUDED.qty
 WHERE promotion_purchases.qty + EXCLUDED.qty <= $5::int
`

type AddPromotionPurchaseParams struct {
	PromotionID  int64
	SkuID        int64
	UserID       int64
	Qty          int32
	PerUserLimit int32
}

// 每人限购：在 ReservePromotionSku 拿到的那把行锁之下累计。
// 首次（INSERT 分支）由 SELECT ... WHERE 判「这一单本身就超了没有」；
// 再次（冲突分支）由 DO UPDATE ... WHERE 判「累计超了没有」。受影响 0 行即超限。
func (q *Queries) AddPromotionPurchase(ctx context.Context, arg AddPromotionPurchaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, addPromotionPurchase,
		arg.PromotionID,
		arg.SkuID,
		arg.UserID,
		arg.Qty,
		arg.PerUserLimit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminCountPromotions = `-- name: AdminCountPromotions :one
SELECT count(*)
  FROM promotions
 WHERE ($1::smallint IS NULL OR status = $1::smallint)
   AND ($2::smallint IS NULL OR promo_type = $2::smallint)
`

type AdminCountPromotionsParams struct {
	Status    *int16
	PromoType *int16
}

func (q *Queries) AdminCountPromotions(ctx context.Context, arg AdminCountPromotionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountPromotions, arg.Status, arg.PromoType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCreatePromotion = `-- name: AdminCreatePromotion :one
INSERT INTO promotions (name, promo_type, threshold_unit, stack_with_coupon, gift_template_id,
                        starts_at, ends_at, status)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7, 0)
RETURNING id
`

type AdminCreatePromotionParams struct {
	Name            string
	PromoType       int16
	ThresholdUnit   int16
	StackWithCoupon bool
	GiftTemplateID  *int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
}

func (q *Queries) AdminCreatePromotion(ctx context.Context, arg AdminCreatePromotionParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCreatePromotion,
		arg.Name,
		arg.PromoType,
		arg.ThresholdUnit,
		arg.StackWithCoupon,
		arg.GiftTemplateID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const adminGetPromotion = `-- name: AdminGetPromotion :one
SELECT id, name, promo_type, threshold_unit, stack_with_coupon, gift_template_id,
       starts_at, ends_at, status, created_at, updated_at
  FROM promotions
 WHERE id = $1
`

type AdminGetPromotionRow struct {
	ID              int64
	Name            string
	PromoType       int16
	ThresholdUnit   int16
	StackWithCoupon bool
	GiftTemplateID  *int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          int16
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) AdminGetPromotion(ctx context.Context, id int64) (AdminGetPromotionRow, error) {
	row := q.db.QueryRow(ctx, adminGetPromotion, id)
	var i AdminGetPromotionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PromoType,
		&i.ThresholdUnit,
		&i.StackWithCoupon,
		&i.GiftTemplateID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminListPromotions = `-- name: AdminListPromotions :many

SELECT id, name, promo_type, threshold_unit, stack_with_coupon, gift_template_id,
       starts_at, ends_at, status, created_at, updated_at
  FROM promotions
 WHERE ($1::smallint IS NULL OR status = $1::smallint)
   AND ($2::smallint IS NULL OR promo_type = $2::smallint)
 ORDER BY id DESC
 LIMIT $4 OFFSET $3
`

type AdminListPromotionsParams struct {
	Status     *int16
	PromoType  *int16
	PageOffset int32
	PageLimit  int32
}

type AdminListPromotionsRow struct {
	ID              int64
	Name            string
	PromoType       int16
	ThresholdUnit   int16
	StackWithCoupon bool
	GiftTemplateID  *int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          int16
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// 后台
// ---------------------------------------------------------------------------
func (q *Queries) AdminListPromotions(ctx context.Context, arg AdminListPromotionsParams) ([]AdminListPromotionsRow, error) {
	rows, err := q.db.Query(ctx, adminListPromotions,
		arg.Status,
		arg.PromoType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListPromotionsRow
	for rows.Next() {
		var i AdminListPromotionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PromoType,
			&i.ThresholdUnit,
			&i.StackWithCoupon,
			&i.GiftTemplateID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminLockPromotion = `-- name: AdminLockPromotion :one
SELECT id, status
  FROM promotions
 WHERE id = $1
   FOR UPDATE
`

type AdminLockPromotionRow struct {
	ID     int64
	Status int16
}

// 修改之前先锁住活动行：「上线中不许改规则」的判定与随后的整组替换必须看到同一个 status。
func (q *Queries) AdminLockPromotion(ctx context.Context, id int64) (AdminLockPromotionRow, error) {
	row := q.db.QueryRow(ctx, adminLockPromotion, id)
	var i AdminLockPromotionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const adminUpdatePromotion = `-- name: AdminUpdatePromotion :execrows
UPDATE promotions
   SET name = $1,
       threshold_unit = $2,
       stack_with_coupon = $3,
       gift_template_id = $4,
       starts_at = $5,
       ends_at = $6,
       status = $7
 WHERE id = $8
`

type AdminUpdatePromotionParams struct {
	Name            string
	ThresholdUnit   int16
	StackWithCoupon bool
	GiftTemplateID  *int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	Status          int16
	ID              int64
}

// 整行写回（service 已经合并过 PATCH）。promo_type 不在这里：类型建了就不改，
// 改类型等于换一个活动，而子表（阶梯 / 活动商品）的形状会跟着整个变掉。
func (q *Queries) AdminUpdatePromotion(ctx context.Context, arg AdminUpdatePromotionParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdatePromotion,
		arg.Name,
		arg.ThresholdUnit,
		arg.StackWithCoupon,
		arg.GiftTemplateID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGiftGrants = `-- name: CountGiftGrants :many
SELECT promotion_id, count(*)::int AS granted
  FROM promotion_gift_grants
 WHERE promotion_id = ANY($1::bigint[])
 GROUP BY promotion_id
`

type CountGiftGrantsRow struct {
	PromotionID int64
	Granted     int32
}

func (q *Queries) CountGiftGrants(ctx context.Context, promotionIds []int64) ([]CountGiftGrantsRow, error) {
	rows, err := q.db.Query(ctx, countGiftGrants, promotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGiftGrantsRow
	for rows.Next() {
		var i CountGiftGrantsRow
		if err := rows.Scan(&i.PromotionID, &i.Granted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePromotionScopes = `-- name: DeletePromotionScopes :exec
DELETE FROM promotion_scopes WHERE promotion_id = $1
`

func (q *Queries) DeletePromotionScopes(ctx context.Context, promotionID int64) error {
	_, err := q.db.Exec(ctx, deletePromotionScopes, promotionID)
	return err
}

const deletePromotionSkusExcept = `-- name: DeletePromotionSkusExcept :exec
DELETE FROM promotion_skus
 WHERE promotion_id = $1
   AND sku_id <> ALL($2::bigint[])
   AND sold_qty = 0
`

type DeletePromotionSkusExceptParams struct {
	PromotionID int64
	KeepSkuIds  []int64
}

// 删掉不在新名单里的 SKU。已售出过的（sold_qty > 0）不删：service 已经先拒过一次，
// 这里的条件是第二道 —— 两道的失效方式不一样。
func (q *Queries) DeletePromotionSkusExcept(ctx context.Context, arg DeletePromotionSkusExceptParams) error {
	_, err := q.db.Exec(ctx, deletePromotionSkusExcept, arg.PromotionID, arg.KeepSkuIds)
	return err
}

const deletePromotionTiers = `-- name: DeletePromotionTiers :exec
DELETE FROM promotion_tiers WHERE promotion_id = $1
`

func (q *Queries) DeletePromotionTiers(ctx context.Context, promotionID int64) error {
	_, err := q.db.Exec(ctx, deletePromotionTiers, promotionID)
	return err
}

const hasGiftGrant = `-- name: HasGiftGrant :one
SELECT EXISTS (
    SELECT 1 FROM promotion_gift_grants
     WHERE promotion_id = $1 AND user_id = $2
)
`

type HasGiftGrantParams struct {
	PromotionID int64
	UserID      int64
}

func (q *Queries) HasGiftGrant(ctx context.Context, arg HasGiftGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasGiftGrant, arg.PromotionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGiftGrant = `-- name: InsertGiftGrant :execrows
INSERT INTO promotion_gift_grants (promotion_id, user_id, user_coupon_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertGiftGrantParams struct {
	PromotionID  int64
	UserID       int64
	UserCouponID int64
}

// 主键（活动 × 买家）是「一人一张」的最终仲裁：两次并发登录都走到这里，只有一次插得进去，
// 另一次受影响 0 行，调用方回滚整个事务（连同它刚占的名额与刚落的券）。
func (q *Queries) InsertGiftGrant(ctx context.Context, arg InsertGiftGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGiftGrant, arg.PromotionID, arg.UserID, arg.UserCouponID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPromotionScope = `-- name: InsertPromotionScope :exec
INSERT INTO promotion_scopes (promotion_id, scope_type, target_id, include)
VALUES ($1, $2, $3, $4)
`

type InsertPromotionScopeParams struct {
	PromotionID int64
	ScopeType   int16
	TargetID    *int64
	Include     bool
}

func (q *Queries) InsertPromotionScope(ctx context.Context, arg InsertPromotionScopeParams) error {
	_, err := q.db.Exec(ctx, insertPromotionScope,
		arg.PromotionID,
		arg.ScopeType,
		arg.TargetID,
		arg.Include,
	)
	return err
}

const insertPromotionTier = `-- name: InsertPromotionTier :exec
INSERT INTO promotion_tiers (promotion_id, threshold, discount_cents, discount_rate)
VALUES ($1, $2, $3,
        $4)
`

type InsertPromotionTierParams struct {
	PromotionID   int64
	Threshold     int64
	DiscountCents int64
	DiscountRate  int16
}

func (q *Queries) InsertPromotionTier(ctx context.Context, arg InsertPromotionTierParams) error {
	_, err := q.db.Exec(ctx, insertPromotionTier,
		arg.PromotionID,
		arg.Threshold,
		arg.DiscountCents,
		arg.DiscountRate,
	)
	return err
}

const listLivePriceOffers = `-- name: ListLivePriceOffers :many
SELECT ps.promotion_id, ps.sku_id, ps.promo_price_cents, ps.discount_rate,
       ps.per_user_limit, ps.stock_qty, ps.sold_qty
  FROM promotion_skus ps
  JOIN promotions pr ON pr.id = ps.promotion_id
 WHERE ps.sku_id = ANY($1::bigint[])
   AND pr.status = 1
   AND pr.promo_type IN (3, 4)
   AND pr.starts_at <= $2
   AND pr.ends_at > $2
 ORDER BY ps.sku_id, ps.promotion_id
`

type ListLivePriceOffersParams struct {
	SkuIds []int64
	Now    pgtype.Timestamptz
}

type ListLivePriceOffersRow struct {
	PromotionID     int64
	SkuID           int64
	PromoPriceCents int64
	DiscountRate    int16
	PerUserLimit    int32
	StockQty        int32
	SoldQty         int32
}

// 一批 SKU 身上此刻生效的限时折扣 / 秒杀。一个 SKU 可以同时在几个活动里，
// 取哪一个（价低者）是 service 的事。
func (q *Queries) ListLivePriceOffers(ctx context.Context, arg ListLivePriceOffersParams) ([]ListLivePriceOffersRow, error) {
	rows, err := q.db.Query(ctx, listLivePriceOffers, arg.SkuIds, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLivePriceOffersRow
	for rows.Next() {
		var i ListLivePriceOffersRow
		if err := rows.Scan(
			&i.PromotionID,
			&i.SkuID,
			&i.PromoPriceCents,
			&i.DiscountRate,
			&i.PerUserLimit,
			&i.StockQty,
			&i.SoldQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePriceOffersForProducts = `-- name: ListLivePriceOffersForProducts :many
SELECT ps.promotion_id, ps.sku_id, s.product_id, v.price_cents AS store_price_cents,
       ps.promo_price_cents, ps.discount_rate, ps.per_user_limit, ps.stock_qty, ps.sold_qty
  FROM promotion_skus ps
  JOIN promotions pr ON pr.id = ps.promotion_id
  JOIN skus s ON s.id = ps.sku_id AND s.status = 1 AND s.deleted_at IS NULL
  JOIN sku_prices_by_store v ON v.sku_id = s.id AND v.store_id = $1
 WHERE s.product_id = ANY($2::bigint[])
   AND pr.status = 1
   AND pr.promo_type IN (3, 4)
   AND pr.starts_at <= $3
   AND pr.ends_at > $3
 ORDER BY s.product_id, ps.sku_id, ps.promotion_id
`

type ListLivePriceOffersForProductsParams struct {
	StoreID    int64
	ProductIds []int64
	Now        pgtype.Timestamptz
}

type ListLivePriceOffersForProductsRow struct {
	PromotionID     int64
	SkuID           int64
	ProductID       int64
	StorePriceCents int64
	PromoPriceCents int64
	DiscountRate    int16
	PerUserLimit    int32
	StockQty        int32
	SoldQty         int32
}

// 商品列表 / 详情的活动标签：一批商品的全部 SKU 身上此刻生效的单价类活动，
// 连同这家门店的生效价（活动价 = min(门店价, 特价)，折扣类的特价要按门店价算）。
// 门店价从 sku_prices_by_store 取 —— 三层定价只许经由视图读（check_query_tenancy.py 第二条）。
func (q *Queries) ListLivePriceOffersForProducts(ctx context.Context, arg ListLivePriceOffersForProductsParams) ([]ListLivePriceOffersForProductsRow, error) {
	rows, err := q.db.Query(ctx, listLivePriceOffersForProducts, arg.StoreID, arg.ProductIds, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLivePriceOffersForProductsRow
	for rows.Next() {
		var i ListLivePriceOffersForProductsRow
		if err := rows.Scan(
			&i.PromotionID,
			&i.SkuID,
			&i.ProductID,
			&i.StorePriceCents,
			&i.PromoPriceCents,
			&i.DiscountRate,
			&i.PerUserLimit,
			&i.StockQty,
			&i.SoldQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePromotions = `-- name: ListLivePromotions :many


SELECT id, name, promo_type, threshold_unit, stack_with_coupon, gift_template_id,
       starts_at, ends_at
  FROM promotions
 WHERE status = 1
   AND starts_at <= $1
   AND ends_at > $1
 ORDER BY id
`

type ListLivePromotionsRow struct {
	ID              int64
	Name            string
	PromoType       int16
	ThresholdUnit   int16
	StackWithCoupon bool
	GiftTemplateID  *int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
}

// 营销活动（数据模型 §7「营销活动」，迁移 00044）。
//
// 与 coupons.sql 同一个分工：这里**只取素材、只做条件更新**，不判定「这个活动在这一单上
// 减多少、哪几行参与」。那个判定只有一份实现（service/promotion_calc.go），
// 试算、下单、购物车、商品标签四处都经过它。
//
// 全文没有一处 WHERE 写租户，也没有一处 INSERT 写那一列（RLS 过滤，DEFAULT 补）。
// 注释里一个反引号都不许有（inventories.sql 第三条说明）。
// ---------------------------------------------------------------------------
// 计价的素材：此刻生效的活动
// ---------------------------------------------------------------------------
// 此刻生效（上线、且 starts_at <= now < ends_at）的活动，不含单价类的活动商品明细。
// 满减满折的阶梯、全部活动的范围另两条查询按 id 批量取。
// 「此刻」由调用方传入，不用 now()：试算与下单共用 service 那一侧的时钟来源，
// 测试也能构造「刚过期」的场景。
func (q *Queries) ListLivePromotions(ctx context.Context, now pgtype.Timestamptz) ([]ListLivePromotionsRow, error) {
	rows, err := q.db.Query(ctx, listLivePromotions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLivePromotionsRow
	for rows.Next() {
		var i ListLivePromotionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PromoType,
			&i.ThresholdUnit,
			&i.StackWithCoupon,
			&i.GiftTemplateID,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPromotionFacts = `-- name: ListProductPromotionFacts :many
SELECT p.id, p.brand_id, c.path AS category_path
  FROM products p
  LEFT JOIN categories c ON c.id = p.category_id AND c.deleted_at IS NULL
 WHERE p.id = ANY($1::bigint[])
`

type ListProductPromotionFactsRow struct {
	ID           int64
	BrandID      *int64
	CategoryPath *string
}

// 满减满折的范围按商品 / 分类（含子孙）/ 品牌挑行，标签也要按同一套规则判
// 「这件商品参不参与」—— 素材与 ListSKUsForPricing 取的那两列同源。
func (q *Queries) ListProductPromotionFacts(ctx context.Context, productIds []int64) ([]ListProductPromotionFactsRow, error) {
	rows, err := q.db.Query(ctx, listProductPromotionFacts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductPromotionFactsRow
	for rows.Next() {
		var i ListProductPromotionFactsRow
		if err := rows.Scan(&i.ID, &i.BrandID, &i.CategoryPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionScopes = `-- name: ListPromotionScopes :many
SELECT ps.promotion_id, ps.scope_type, ps.target_id, ps.include,
       c.path AS category_path,
       c.name AS category_name, p.title AS product_title, r.name AS region_name,
       st.name AS store_name
  FROM promotion_scopes ps
  LEFT JOIN categories c ON ps.scope_type = 2 AND c.id = ps.target_id AND c.deleted_at IS NULL
  LEFT JOIN products   p ON ps.scope_type = 3 AND p.id = ps.target_id AND p.deleted_at IS NULL
  LEFT JOIN regions    r ON ps.scope_type = 5 AND r.id = ps.target_id AND r.deleted_at IS NULL
  LEFT JOIN stores    st ON ps.scope_type = 6 AND st.id = ps.target_id AND st.deleted_at IS NULL
 WHERE ps.promotion_id = ANY($1::bigint[])
 ORDER BY ps.promotion_id, ps.id
`

type ListPromotionScopesRow struct {
	PromotionID  int64
	ScopeType    int16
	TargetID     *int64
	Include      bool
	CategoryPath *string
	CategoryName *string
	ProductTitle *string
	RegionName   *string
	StoreName    *string
}

// 与 coupons.sql 的 ListCouponScopes 同一个形状、同一段 LEFT JOIN：范围语义只有一套。
func (q *Queries) ListPromotionScopes(ctx context.Context, promotionIds []int64) ([]ListPromotionScopesRow, error) {
	rows, err := q.db.Query(ctx, listPromotionScopes, promotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromotionScopesRow
	for rows.Next() {
		var i ListPromotionScopesRow
		if err := rows.Scan(
			&i.PromotionID,
			&i.ScopeType,
			&i.TargetID,
			&i.Include,
			&i.CategoryPath,
			&i.CategoryName,
			&i.ProductTitle,
			&i.RegionName,
			&i.StoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionSkusAdmin = `-- name: ListPromotionSkusAdmin :many
SELECT ps.promotion_id, ps.sku_id, ps.promo_price_cents, ps.discount_rate,
       ps.per_user_limit, ps.stock_qty, ps.sold_qty, s.sku_code, p.title
  FROM promotion_skus ps
  JOIN skus s ON s.id = ps.sku_id
  JOIN products p ON p.id = s.product_id
 WHERE ps.promotion_id = ANY($1::bigint[])
 ORDER BY ps.promotion_id, ps.sku_id
`

type ListPromotionSkusAdminRow struct {
	PromotionID     int64
	SkuID           int64
	PromoPriceCents int64
	DiscountRate    int16
	PerUserLimit    int32
	StockQty        int32
	SoldQty         int32
	SkuCode         string
	Title           string
}

// 后台看活动商品：连同标题与 SKU 编码（展示用），以及已售件数。
func (q *Queries) ListPromotionSkusAdmin(ctx context.Context, promotionIds []int64) ([]ListPromotionSkusAdminRow, error) {
	rows, err := q.db.Query(ctx, listPromotionSkusAdmin, promotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromotionSkusAdminRow
	for rows.Next() {
		var i ListPromotionSkusAdminRow
		if err := rows.Scan(
			&i.PromotionID,
			&i.SkuID,
			&i.PromoPriceCents,
			&i.DiscountRate,
			&i.PerUserLimit,
			&i.StockQty,
			&i.SoldQty,
			&i.SkuCode,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionTiers = `-- name: ListPromotionTiers :many
SELECT promotion_id, threshold, discount_cents, discount_rate
  FROM promotion_tiers
 WHERE promotion_id = ANY($1::bigint[])
 ORDER BY promotion_id, threshold
`

type ListPromotionTiersRow struct {
	PromotionID   int64
	Threshold     int64
	DiscountCents int64
	DiscountRate  int16
}

func (q *Queries) ListPromotionTiers(ctx context.Context, promotionIds []int64) ([]ListPromotionTiersRow, error) {
	rows, err := q.db.Query(ctx, listPromotionTiers, promotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromotionTiersRow
	for rows.Next() {
		var i ListPromotionTiersRow
		if err := rows.Scan(
			&i.PromotionID,
			&i.Threshold,
			&i.DiscountCents,
			&i.DiscountRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPromotionPurchases = `-- name: ListUserPromotionPurchases :many
SELECT promotion_id, sku_id, qty
  FROM promotion_purchases
 WHERE user_id = $1
   AND promotion_id = ANY($2::bigint[])
`

type ListUserPromotionPurchasesParams struct {
	UserID       int64
	PromotionIds []int64
}

type ListUserPromotionPurchasesRow struct {
	PromotionID int64
	SkuID       int64
	Qty         int32
}

// 这个买家在这些活动里各 SKU 已经买了几件（每人限购的判据，只计未关闭的订单）。
func (q *Queries) ListUserPromotionPurchases(ctx context.Context, arg ListUserPromotionPurchasesParams) ([]ListUserPromotionPurchasesRow, error) {
	rows, err := q.db.Query(ctx, listUserPromotionPurchases, arg.UserID, arg.PromotionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPromotionPurchasesRow
	for rows.Next() {
		var i ListUserPromotionPurchasesRow
		if err := rows.Scan(&i.PromotionID, &i.SkuID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveCouponTemplateIDs = `-- name: LiveCouponTemplateIDs :many
SELECT id FROM coupon_templates WHERE id = ANY($1::bigint[])
`

// 新人礼的券模板归属校验。
func (q *Queries) LiveCouponTemplateIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, liveCouponTemplateIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSkuIDs = `-- name: LiveSkuIDs :many
SELECT id FROM skus WHERE id = ANY($1::bigint[]) AND deleted_at IS NULL
`

// 活动商品的归属校验：在本租户存在且未软删的 SKU（RLS 之下，别家的与不存在的同形）。
func (q *Queries) LiveSkuIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, liveSkuIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePromotionPurchase = `-- name: ReleasePromotionPurchase :execrows
UPDATE promotion_purchases
   SET qty = qty - $1::int
 WHERE promotion_id = $2
   AND sku_id = $3
   AND user_id = $4
   AND qty >= $1::int
`

type ReleasePromotionPurchaseParams struct {
	Qty         int32
	PromotionID int64
	SkuID       int64
	UserID      int64
}

func (q *Queries) ReleasePromotionPurchase(ctx context.Context, arg ReleasePromotionPurchaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releasePromotionPurchase,
		arg.Qty,
		arg.PromotionID,
		arg.SkuID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releasePromotionSku = `-- name: ReleasePromotionSku :execrows
UPDATE promotion_skus
   SET sold_qty = sold_qty - $1::int
 WHERE promotion_id = $2
   AND sku_id = $3
   AND sold_qty >= $1::int
`

type ReleasePromotionSkuParams struct {
	Qty         int32
	PromotionID int64
	SkuID       int64
}

// SAGA 补偿、超时关单、买家取消：把这一行占的配额放回去。
// 带 sold_qty >= qty：放回不该把计数放成负数；0 行由调用方记日志（SKU 已被移出活动之类）。
func (q *Queries) ReleasePromotionSku(ctx context.Context, arg ReleasePromotionSkuParams) (int64, error) {
	result, err := q.db.Exec(ctx, releasePromotionSku, arg.Qty, arg.PromotionID, arg.SkuID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reservePromotionSku = `-- name: ReservePromotionSku :one

UPDATE promotion_skus
   SET sold_qty = sold_qty + $1::int
 WHERE promotion_id = $2
   AND sku_id = $3
   AND (stock_qty = 0 OR sold_qty + $1::int <= stock_qty)
RETURNING per_user_limit
`

type ReservePromotionSkuParams struct {
	Qty         int32
	PromotionID int64
	SkuID       int64
}

// ---------------------------------------------------------------------------
// 下单 SAGA 的库存分支：活动配额与每人限购（与门店库存扣减同一个事务）
// ---------------------------------------------------------------------------
// 秒杀不超卖的那一条（00044 文件头）：条件 UPDATE，READ COMMITTED 下后到者在最新版本上
// 重评 WHERE。stock_qty = 0 表示不限配额（限时折扣），此时只是累计已售件数。
// 受影响 0 行即配额不够（或这个 SKU 已被移出活动）—— :one 变成 pgx.ErrNoRows。
//
// 不看活动的上下线与有效期：价格在建单那一刻已经定下、写进了订单行，
// 下单几百毫秒之后活动恰好下线，按已经报给买家的价成交才是对的。
func (q *Queries) ReservePromotionSku(ctx context.Context, arg ReservePromotionSkuParams) (int32, error) {
	row := q.db.QueryRow(ctx, reservePromotionSku, arg.Qty, arg.PromotionID, arg.SkuID)
	var per_user_limit int32
	err := row.Scan(&per_user_limit)
	return per_user_limit, err
}

const upsertPromotionSku = `-- name: UpsertPromotionSku :exec
INSERT INTO promotion_skus (promotion_id, sku_id, promo_price_cents, discount_rate,
                            per_user_limit, stock_qty)
VALUES ($1, $2, $3,
        $4, $5, $6)
    ON CONFLICT ON CONSTRAINT uk_promotion_skus
    DO UPDATE SET promo_price_cents = EXCLUDED.promo_price_cents,
                  discount_rate = EXCLUDED.discount_rate,
                  per_user_limit = EXCLUDED.per_user_limit,
                  stock_qty = EXCLUDED.stock_qty
`

type UpsertPromotionSkuParams struct {
	PromotionID     int64
	SkuID           int64
	PromoPriceCents int64
	DiscountRate    int16
	PerUserLimit    int32
	StockQty        int32
}

// 整组替换活动商品时逐条 upsert：保留下来的 SKU 保留它的 sold_qty（已兑现的配额不清零）。
// chk_promotion_sku_qty 兜底「配额改到低于已售数」。
func (q *Queries) UpsertPromotionSku(ctx context.Context, arg UpsertPromotionSkuParams) error {
	_, err := q.db.Exec(ctx, upsertPromotionSku,
		arg.PromotionID,
		arg.SkuID,
		arg.PromoPriceCents,
		arg.DiscountRate,
		arg.PerUserLimit,
		arg.StockQty,
	)
	return err
}

const userHasPlacedOrder = `-- name: UserHasPlacedOrder :one

SELECT EXISTS (
    SELECT 1 FROM orders WHERE user_id = $1 AND status NOT IN (0, 90)
)
`

// ---------------------------------------------------------------------------
// 新人礼
// ---------------------------------------------------------------------------
// 「首单前」的判据：这个买家有没有一笔进过 SAGA 且没被关掉的订单。
// 创建中（0）与已关闭（90）不算 —— 下单失败、超时没付的单子不让人失去新人资格。
func (q *Queries) UserHasPlacedOrder(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, userHasPlacedOrder, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
