// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refunds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelRefundedCents = `-- name: AddChannelRefundedCents :exec
UPDATE orders o
   SET refunded_cents = o.refunded_cents + $1::bigint,
       refund_status = CASE
         WHEN EXISTS (SELECT 1 FROM refunds r
                       WHERE r.order_id = o.id AND r.status IN (10, 20, 30)) THEN 1
         WHEN o.refunded_cents + $1::bigint = o.paid_cents THEN 3
         ELSE 2
       END
 WHERE o.id = $2
`

type AddChannelRefundedCentsParams struct {
	Amount int64
	ID     int64
}

// 渠道退款入账：累加已退金额并在**同一条语句**里对齐 refund_status。自营退款入账时订单已经在 1 退款中
// （申请那一刻 RecomputeOrderRefundStatus 推上去的），先累加再重算过得了 chk_refund_status；渠道退款单
// 直接落 40，没有「退款中」那一步，分两条写的话累加那一条就撞 chk_refund_status（0 却退过钱）。
// 规则与 RecomputeOrderRefundStatus 同一份（在途 → 1、退满实收 → 3、其余 → 2）。
func (q *Queries) AddChannelRefundedCents(ctx context.Context, arg AddChannelRefundedCentsParams) error {
	_, err := q.db.Exec(ctx, addChannelRefundedCents, arg.Amount, arg.ID)
	return err
}

const addOrderRefundedCents = `-- name: AddOrderRefundedCents :exec
UPDATE orders SET refunded_cents = refunded_cents + $2 WHERE id = $1
`

type AddOrderRefundedCentsParams struct {
	ID            int64
	RefundedCents int64
}

// 累加订单的已退金额。chk_amount 保证它不超过实收，chk_refund_status 随后由
// RecomputeOrderRefundStatus 对齐。
func (q *Queries) AddOrderRefundedCents(ctx context.Context, arg AddOrderRefundedCentsParams) error {
	_, err := q.db.Exec(ctx, addOrderRefundedCents, arg.ID, arg.RefundedCents)
	return err
}

const approveRefund = `-- name: ApproveRefund :execrows
UPDATE refunds
   SET status = $1, freight_cents = $2,
       amount_cents = goods_amount_cents + $2, audited_at = now(),
       audited_by = $3
 WHERE id = $4 AND status = 10
`

type ApproveRefundParams struct {
	NextStatus   int16
	FreightCents int64
	AuditedBy    *int64
	ID           int64
}

// 审核通过：10 → 20（退货退款）或 10 → 30（仅退款）。
// 运费由审核裁定（退货退款）或沿用申请时按规则算好的值（仅退款），
// 实退总额跟着重算 —— chk_refund_amount 要它恒等于货款 + 运费。
func (q *Queries) ApproveRefund(ctx context.Context, arg ApproveRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveRefund,
		arg.NextStatus,
		arg.FreightCents,
		arg.AuditedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelRefund = `-- name: CancelRefund :execrows
UPDATE refunds SET status = 60
 WHERE id = $1 AND user_id = $2::bigint AND status IN (10, 20)
`

type CancelRefundParams struct {
	ID     int64
	UserID int64
}

// 买家撤回：10 待审核 / 20 待买家退货 → 60 已取消。30 退款中撤不回来（钱在路上）。
func (q *Queries) CancelRefund(ctx context.Context, arg CancelRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRefund, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const channelRefundExists = `-- name: ChannelRefundExists :one
SELECT EXISTS (SELECT 1 FROM refunds WHERE channel = 10 AND channel_refund_id = $1::text)
`

// 这个幂等键的渠道退款单记过没有。
func (q *Queries) ChannelRefundExists(ctx context.Context, channelRefundID string) (bool, error) {
	row := q.db.QueryRow(ctx, channelRefundExists, channelRefundID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const completeRefund = `-- name: CompleteRefund :execrows
UPDATE refunds
   SET status = 40, channel_refund_id = $2, notify_payload = $3, refunded_at = $4
 WHERE id = $1 AND status = 30
`

type CompleteRefundParams struct {
	ID              int64
	ChannelRefundID *string
	NotifyPayload   []byte
	RefundedAt      pgtype.Timestamptz
}

// 渠道回调入账：30 退款中 → 40 已退款，写下渠道流水号、原始报文与到账时间。
//
// **这是 channel_refund_id 的唯一写入路径**（契约原话）。同一个流水号第二次到来
// 撞 uk_refunds_channel_txn，由 Go 侧按约束名挑成 ErrDuplicateChannelRefund ——
// 光秃秃的 UPDATE，不吞任何别的唯一冲突，与支付回调的 InsertPayment 同一条理由。
func (q *Queries) CompleteRefund(ctx context.Context, arg CompleteRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRefund,
		arg.ID,
		arg.ChannelRefundID,
		arg.NotifyPayload,
		arg.RefundedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOrderItemsNotFullyRefunded = `-- name: CountOrderItemsNotFullyRefunded :one
SELECT count(*) FROM order_items WHERE order_id = $1 AND refunded_qty < quantity
`

// 还有几行没退完。0 表示整单的货都退了 —— 券回补的判据（§11 末段）。
func (q *Queries) CountOrderItemsNotFullyRefunded(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItemsNotFullyRefunded, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserRefunds = `-- name: CountUserRefunds :one
SELECT count(*)
  FROM refunds r
 WHERE r.user_id = $1::bigint
   AND ($2::smallint IS NULL OR r.status = $2::smallint)
`

type CountUserRefundsParams struct {
	UserID int64
	Status *int16
}

func (q *Queries) CountUserRefunds(ctx context.Context, arg CountUserRefundsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRefunds, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireReturnRefund = `-- name: ExpireReturnRefund :execrows
UPDATE refunds SET status = 60
 WHERE id = $1 AND status = 20 AND refund_type = 2
   AND return_submitted_at IS NULL
   AND audited_at < $2::timestamptz
`

type ExpireReturnRefundParams struct {
	ID     int64
	Cutoff pgtype.Timestamptz
}

// 退货超时未寄回：20 待买家退货 → 60 已取消（状态机里画着的那条 20 → 60，00034）。
// 谓词把预筛的每一条都重判一遍：仍在 20、是退货退款、**没有填寄回物流**、审核时间早于截止。
// 买家在预筛之后、处置之前填了物流，这条影响 0 行 —— 已经寄出的货不能被关单。
// 调用方先锁订单再锁退款单（与填寄回物流、撤回同一个顺序），所以这里读到的是最新版本。
func (q *Queries) ExpireReturnRefund(ctx context.Context, arg ExpireReturnRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireReturnRefund, arg.ID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSettledPayment = `-- name: FindSettledPayment :one
SELECT p.id, p.payment_no, p.channel
  FROM payments p
  JOIN orders o ON o.id = p.order_id
 WHERE p.order_id = $1 AND p.status = 1
   AND p.amount_cents = o.paid_cents AND p.paid_at = o.paid_at
 ORDER BY p.id
 LIMIT 1
`

type FindSettledPaymentRow struct {
	ID        int64
	PaymentNo string
	Channel   int16
}

// 原路退回退到哪一笔：让这一单从 10 走到 20 的那笔支付。
//
// 一单可能有不止一行「渠道成功」的支付（status = 1 描述的是渠道那边成没成，不是我们认不认）：
// 金额不符的到账、订单已关之后才到的、重复付款，都落一行 status = 1 留痕、但订单不认。
// 认账的那一笔由 SettleOrder 与它同一个事务把金额与到账时间写进 orders.paid_cents / paid_at，
// 所以按这两列对上它，而不是取「最早的一笔」—— 2026-09-28 破坏性测试：先来一笔 1 分的
// 金额不符回调、再来正确的那笔，售后退款挂到了 1 分那笔上（真实渠道会超额退或退错交易）。
// 对不上任何一行时查不到（ErrNoRows），宁可售后申请失败，也不退到错的那笔。
func (q *Queries) FindSettledPayment(ctx context.Context, orderID int64) (FindSettledPaymentRow, error) {
	row := q.db.QueryRow(ctx, findSettledPayment, orderID)
	var i FindSettledPaymentRow
	err := row.Scan(&i.ID, &i.PaymentNo, &i.Channel)
	return i, err
}

const finishWholeOrderRefund = `-- name: FinishWholeOrderRefund :execrows
UPDATE orders SET status = 60 WHERE id = $1 AND status = 50
`

// 整单退款到账：订单 50 退款中 → 60 已退款（§5 的 (50,60)）。
func (q *Queries) FinishWholeOrderRefund(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, finishWholeOrderRefund, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefundByNo = `-- name: GetRefundByNo :one

SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, COALESCE(p.payment_no, '')::text AS payment_no, COALESCE(r.user_id, 0)::bigint AS user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  LEFT JOIN payments p ON p.id = r.payment_id
 WHERE r.refund_no = $1
`

type GetRefundByNoRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// 读
// ---------------------------------------------------------------------------
// 按对外编号取退款单（后台与入账用，没有买家过滤；租户由 RLS 管）。
// store_id 一起带出来：后台判权按订单的履约门店（与发货同一个判据）。
func (q *Queries) GetRefundByNo(ctx context.Context, refundNo string) (GetRefundByNoRow, error) {
	row := q.db.QueryRow(ctx, getRefundByNo, refundNo)
	var i GetRefundByNoRow
	err := row.Scan(
		&i.ID,
		&i.RefundNo,
		&i.OrderID,
		&i.OrderNo,
		&i.StoreID,
		&i.PaymentNo,
		&i.UserID,
		&i.RefundType,
		&i.ReasonCode,
		&i.ReasonText,
		&i.EvidenceUrls,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.AmountCents,
		&i.Status,
		&i.Channel,
		&i.ChannelRefundID,
		&i.RejectReason,
		&i.AuditedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCarrierCode,
		&i.ReturnTrackingNo,
		&i.ReturnSubmittedAt,
	)
	return i, err
}

const getUserRefundByNo = `-- name: GetUserRefundByNo :one
SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, COALESCE(p.payment_no, '')::text AS payment_no, COALESCE(r.user_id, 0)::bigint AS user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  LEFT JOIN payments p ON p.id = r.payment_id
 WHERE r.refund_no = $1
   AND r.user_id = $2::bigint
`

type GetUserRefundByNoParams struct {
	RefundNo string
	UserID   int64
}

type GetUserRefundByNoRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
}

// 买家读自己的退款单。查不到与「不是你的」回同一个 404（refund_no 不可枚举，
// 分开报会把它变成一个存在性判定器）。
func (q *Queries) GetUserRefundByNo(ctx context.Context, arg GetUserRefundByNoParams) (GetUserRefundByNoRow, error) {
	row := q.db.QueryRow(ctx, getUserRefundByNo, arg.RefundNo, arg.UserID)
	var i GetUserRefundByNoRow
	err := row.Scan(
		&i.ID,
		&i.RefundNo,
		&i.OrderID,
		&i.OrderNo,
		&i.StoreID,
		&i.PaymentNo,
		&i.UserID,
		&i.RefundType,
		&i.ReasonCode,
		&i.ReasonText,
		&i.EvidenceUrls,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.AmountCents,
		&i.Status,
		&i.Channel,
		&i.ChannelRefundID,
		&i.RejectReason,
		&i.AuditedAt,
		&i.RefundedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCarrierCode,
		&i.ReturnTrackingNo,
		&i.ReturnSubmittedAt,
	)
	return i, err
}

const insertChannelRefund = `-- name: InsertChannelRefund :one

INSERT INTO refunds (refund_no, order_id, refund_type, reason_code, reason_text,
                     goods_amount_cents, freight_cents, amount_cents, status, channel,
                     channel_refund_id, audited_at, refunded_at)
VALUES ($1, $2, 1, 5, $3,
        $4, $5,
        $4::bigint + $5::bigint, 40, 10,
        $6, now(), $7)
RETURNING id
`

type InsertChannelRefundParams struct {
	RefundNo         string
	OrderID          int64
	ReasonText       *string
	GoodsAmountCents int64
	FreightCents     int64
	ChannelRefundID  *string
	RefundedAt       pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// 渠道退款（00323）：平台上已经退了钱，keel 只记账
// ---------------------------------------------------------------------------
// 落一张**已成功**的渠道退款单（40，不经审核与支付渠道）：没有买家、没有 payments 行（chk_refund_payer）。
// channel_refund_id 是幂等键（uk_refunds_channel_txn），调用方先 ChannelRefundExists 再插，撞键原样上浮。
// 直接以 40 落行不过状态触发器（它只管 UPDATE），chk_refund_state 要的 audited_at / refunded_at 一并写上。
func (q *Queries) InsertChannelRefund(ctx context.Context, arg InsertChannelRefundParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChannelRefund,
		arg.RefundNo,
		arg.OrderID,
		arg.ReasonText,
		arg.GoodsAmountCents,
		arg.FreightCents,
		arg.ChannelRefundID,
		arg.RefundedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (refund_no, order_id, payment_id, user_id, refund_type, reason_code,
                     reason_text, evidence_urls, goods_amount_cents, freight_cents,
                     amount_cents, channel)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertRefundParams struct {
	RefundNo         string
	OrderID          int64
	PaymentID        *int64
	UserID           *int64
	RefundType       int16
	ReasonCode       int16
	ReasonText       *string
	EvidenceUrls     []string
	GoodsAmountCents int64
	FreightCents     int64
	AmountCents      int64
	Channel          int16
}

// 落一张 10 待审核的退款单。租户列不出现（00034 的 DEFAULT current_merchant()）。
func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.RefundNo,
		arg.OrderID,
		arg.PaymentID,
		arg.UserID,
		arg.RefundType,
		arg.ReasonCode,
		arg.ReasonText,
		arg.EvidenceUrls,
		arg.GoodsAmountCents,
		arg.FreightCents,
		arg.AmountCents,
		arg.Channel,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRefundItem = `-- name: InsertRefundItem :exec
INSERT INTO refund_items (refund_id, order_item_id, quantity, amount_cents)
VALUES ($1, $2, $3, $4)
`

type InsertRefundItemParams struct {
	RefundID    int64
	OrderItemID int64
	Quantity    int32
	AmountCents int64
}

func (q *Queries) InsertRefundItem(ctx context.Context, arg InsertRefundItemParams) error {
	_, err := q.db.Exec(ctx, insertRefundItem,
		arg.RefundID,
		arg.OrderItemID,
		arg.Quantity,
		arg.AmountCents,
	)
	return err
}

const listOrderItemsForRefund = `-- name: ListOrderItemsForRefund :many

SELECT id, sku_id, quantity, amount_cents, discount_cents, refunded_qty, refunded_cents
  FROM order_items
 WHERE order_id = $1
 ORDER BY id
`

type ListOrderItemsForRefundRow struct {
	ID            int64
	SkuID         int64
	Quantity      int32
	AmountCents   int64
	DiscountCents int64
	RefundedQty   int32
	RefundedCents int64
}

// ---------------------------------------------------------------------------
// 申请
// ---------------------------------------------------------------------------
// 算退款金额要的全部素材：购买件数、行金额、分摊优惠、已退件数与金额。
func (q *Queries) ListOrderItemsForRefund(ctx context.Context, orderID int64) ([]ListOrderItemsForRefundRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsForRefund, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsForRefundRow
	for rows.Next() {
		var i ListOrderItemsForRefundRow
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.Quantity,
			&i.AmountCents,
			&i.DiscountCents,
			&i.RefundedQty,
			&i.RefundedCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderRefunds = `-- name: ListOrderRefunds :many
SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, COALESCE(p.payment_no, '')::text AS payment_no, COALESCE(r.user_id, 0)::bigint AS user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  LEFT JOIN payments p ON p.id = r.payment_id
 WHERE r.order_id = $1
 ORDER BY r.created_at DESC, r.id DESC
`

type ListOrderRefundsRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
}

// 一个订单的全部退款单，按申请时间倒序（契约 GET /orders/{order_no}/refunds
// 与 OrderDetail.refunds）。同一毫秒的两张按 id 倒序，顺序才是确定的。
func (q *Queries) ListOrderRefunds(ctx context.Context, orderID int64) ([]ListOrderRefundsRow, error) {
	rows, err := q.db.Query(ctx, listOrderRefunds, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderRefundsRow
	for rows.Next() {
		var i ListOrderRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.RefundNo,
			&i.OrderID,
			&i.OrderNo,
			&i.StoreID,
			&i.PaymentNo,
			&i.UserID,
			&i.RefundType,
			&i.ReasonCode,
			&i.ReasonText,
			&i.EvidenceUrls,
			&i.GoodsAmountCents,
			&i.FreightCents,
			&i.AmountCents,
			&i.Status,
			&i.Channel,
			&i.ChannelRefundID,
			&i.RejectReason,
			&i.AuditedAt,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCarrierCode,
			&i.ReturnTrackingNo,
			&i.ReturnSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundItems = `-- name: ListRefundItems :many
SELECT ri.refund_id, ri.order_item_id, oi.sku_id, ri.quantity, ri.amount_cents,
       oi.title_snapshot, oi.image_snapshot
  FROM refund_items ri
  JOIN order_items oi ON oi.id = ri.order_item_id
 WHERE ri.refund_id = ANY($1::bigint[])
 ORDER BY ri.refund_id, ri.order_item_id
`

type ListRefundItemsRow struct {
	RefundID      int64
	OrderItemID   int64
	SkuID         int64
	Quantity      int32
	AmountCents   int64
	TitleSnapshot string
	ImageSnapshot *string
}

// 一批退款单的明细，带下单时的标题与图片快照（契约 RefundItem）。
func (q *Queries) ListRefundItems(ctx context.Context, refundIds []int64) ([]ListRefundItemsRow, error) {
	rows, err := q.db.Query(ctx, listRefundItems, refundIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefundItemsRow
	for rows.Next() {
		var i ListRefundItemsRow
		if err := rows.Scan(
			&i.RefundID,
			&i.OrderItemID,
			&i.SkuID,
			&i.Quantity,
			&i.AmountCents,
			&i.TitleSnapshot,
			&i.ImageSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnOverdueRefunds = `-- name: ListReturnOverdueRefunds :many
SELECT r.id, r.refund_no, r.order_id
  FROM refunds r
 WHERE r.status = 20 AND r.refund_type = 2 AND r.return_submitted_at IS NULL
   AND r.audited_at < $1::timestamptz
 ORDER BY r.audited_at, r.id
 LIMIT $2
`

type ListReturnOverdueRefundsParams struct {
	Cutoff    pgtype.Timestamptz
	PageLimit int32
}

type ListReturnOverdueRefundsRow struct {
	ID       int64
	RefundNo string
	OrderID  int64
}

// 退货超时未寄回的候选（service/return_timeout.go，00059）：退货退款、停在 20 待买家退货、
// 没填寄回物流、审核通过的时间早于截止（now() 减去这家店的 return_ship_days，由调用方算好）。
// 按审核时间从早到晚，最久的先关。部分索引 idx_refunds_return_due（00060）正好对上这条扫描。
// 这只是预筛；真正的判断在处置事务里、订单与退款单行锁之下由 ExpireReturnRefund 的谓词再做一次。
func (q *Queries) ListReturnOverdueRefunds(ctx context.Context, arg ListReturnOverdueRefundsParams) ([]ListReturnOverdueRefundsRow, error) {
	rows, err := q.db.Query(ctx, listReturnOverdueRefunds, arg.Cutoff, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturnOverdueRefundsRow
	for rows.Next() {
		var i ListReturnOverdueRefundsRow
		if err := rows.Scan(&i.ID, &i.RefundNo, &i.OrderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRefunds = `-- name: ListUserRefunds :many
SELECT r.id, r.refund_no, r.order_id, o.order_no, o.store_id, COALESCE(p.payment_no, '')::text AS payment_no, COALESCE(r.user_id, 0)::bigint AS user_id,
       r.refund_type, r.reason_code, r.reason_text, r.evidence_urls,
       r.goods_amount_cents, r.freight_cents, r.amount_cents, r.status, r.channel,
       r.channel_refund_id, r.reject_reason, r.audited_at, r.refunded_at,
       r.created_at, r.updated_at,
       r.return_carrier_code, r.return_tracking_no, r.return_submitted_at
  FROM refunds r
  JOIN orders o   ON o.id = r.order_id
  LEFT JOIN payments p ON p.id = r.payment_id
 WHERE r.user_id = $1::bigint
   AND ($2::smallint IS NULL OR r.status = $2::smallint)
 ORDER BY r.created_at DESC, r.id DESC
 LIMIT $4 OFFSET $3
`

type ListUserRefundsParams struct {
	UserID     int64
	Status     *int16
	PageOffset int32
	PageLimit  int32
}

type ListUserRefundsRow struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	OrderNo           string
	StoreID           int64
	PaymentNo         string
	UserID            int64
	RefundType        int16
	ReasonCode        int16
	ReasonText        *string
	EvidenceUrls      []string
	GoodsAmountCents  int64
	FreightCents      int64
	AmountCents       int64
	Status            int16
	Channel           int16
	ChannelRefundID   *string
	RejectReason      *string
	AuditedAt         pgtype.Timestamptz
	RefundedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ReturnCarrierCode *string
	ReturnTrackingNo  *string
	ReturnSubmittedAt pgtype.Timestamptz
}

// 我的退款单，一页。status 用可空参数：传 NULL 就是不筛，
// 与 CountUserRefunds 共用同一套谓词（理由同 ListUserOrders）。
func (q *Queries) ListUserRefunds(ctx context.Context, arg ListUserRefundsParams) ([]ListUserRefundsRow, error) {
	rows, err := q.db.Query(ctx, listUserRefunds,
		arg.UserID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRefundsRow
	for rows.Next() {
		var i ListUserRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.RefundNo,
			&i.OrderID,
			&i.OrderNo,
			&i.StoreID,
			&i.PaymentNo,
			&i.UserID,
			&i.RefundType,
			&i.ReasonCode,
			&i.ReasonText,
			&i.EvidenceUrls,
			&i.GoodsAmountCents,
			&i.FreightCents,
			&i.AmountCents,
			&i.Status,
			&i.Channel,
			&i.ChannelRefundID,
			&i.RejectReason,
			&i.AuditedAt,
			&i.RefundedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCarrierCode,
			&i.ReturnTrackingNo,
			&i.ReturnSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrderByID = `-- name: LockOrderByID :one
SELECT id, order_no, user_id, store_id, region_id, status,
       goods_amount_cents, freight_cents, freight_discount_cents,
       discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
       expire_at, paid_at, shipped_at, finished_at, created_at, user_coupon_id,
       coupon_name, promotion_discount_cents, promotions,
       source, channel_order_id  -- 00320
  FROM orders
 WHERE id = $1
   FOR UPDATE
`

type LockOrderByIDRow struct {
	ID                     int64
	OrderNo                string
	UserID                 *int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
	Source                 int16
	ChannelOrderID         *int64
}

// 审核、撤回、入账改订单之前先锁它（见文件头「锁的顺序」）。
func (q *Queries) LockOrderByID(ctx context.Context, id int64) (LockOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, lockOrderByID, id)
	var i LockOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UserCouponID,
		&i.CouponName,
		&i.PromotionDiscountCents,
		&i.Promotions,
		&i.Source,
		&i.ChannelOrderID,
	)
	return i, err
}

const lockRefundStatus = `-- name: LockRefundStatus :one
SELECT status FROM refunds WHERE id = $1 FOR UPDATE
`

// 在订单行锁之下锁住退款单并读回它**此刻**的状态（见文件头「锁的顺序」）。
func (q *Queries) LockRefundStatus(ctx context.Context, id int64) (int16, error) {
	row := q.db.QueryRow(ctx, lockRefundStatus, id)
	var status int16
	err := row.Scan(&status)
	return status, err
}

const lockUserOrderByNo = `-- name: LockUserOrderByNo :one


SELECT id, order_no, user_id, store_id, region_id, status,
       goods_amount_cents, freight_cents, freight_discount_cents,
       discount_cents, payable_cents, paid_cents, refunded_cents, refund_status,
       expire_at, paid_at, shipped_at, finished_at, created_at, user_coupon_id,
       coupon_name, promotion_discount_cents, promotions,
       source, channel_order_id  -- 00320
  FROM orders
 WHERE order_no = $1
   AND user_id = $2
   AND status <> 0
   FOR UPDATE
`

type LockUserOrderByNoParams struct {
	OrderNo string
	UserID  *int64
}

type LockUserOrderByNoRow struct {
	ID                     int64
	OrderNo                string
	UserID                 *int64
	StoreID                int64
	RegionID               int64
	Status                 int16
	GoodsAmountCents       int64
	FreightCents           int64
	FreightDiscountCents   int64
	DiscountCents          int64
	PayableCents           int64
	PaidCents              int64
	RefundedCents          int64
	RefundStatus           int16
	ExpireAt               pgtype.Timestamptz
	PaidAt                 pgtype.Timestamptz
	ShippedAt              pgtype.Timestamptz
	FinishedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UserCouponID           *int64
	CouponName             *string
	PromotionDiscountCents int64
	Promotions             []byte
	Source                 int16
	ChannelOrderID         *int64
}

// 退款与售后（数据模型 §11）：申请、撤回、审核、确认收到退货、渠道回调入账，
// 以及买家侧的读。
//
// 租户由 RLS 过滤，这里一处都不写（check_query_tenancy.py）；user_id 出现的地方
// 都是**越权过滤**（同一家店里 A 买家不能碰 B 买家的退款单），理由与
// db/queries/orders.sql 买家侧读接口那段一字不差。
//
// 注释里不许有反引号，理由见 db/queries/inventories.sql 的第三条说明。
//
// ### 锁的顺序：先订单，后退款单
//
// 申请退款要在订单行锁之下复算「在途件数」（§11：数据库拦不住在途超退），
// 而审核、撤回、入账都要改订单（refund_status、50 退款中的进出、refunded_cents）。
// 所有路径一律**先锁订单行、再锁退款单行**，两笔并发的售后动作因此不会交叉等待。
// ---------------------------------------------------------------------------
// 锁
// ---------------------------------------------------------------------------
// 申请退款的第一步：按单号取当前买家自己的订单并锁住这一行。
//
// FOR UPDATE 不是可选的：同一个订单上两次并发的退款申请必须串行，
// 否则两边各自读到「在途 0 件」，各自插一张退款单，合起来超退 ——
// 而那正是 chk_item_refund 拦不住的那一种（它只看已退，不看在途）。
func (q *Queries) LockUserOrderByNo(ctx context.Context, arg LockUserOrderByNoParams) (LockUserOrderByNoRow, error) {
	row := q.db.QueryRow(ctx, lockUserOrderByNo, arg.OrderNo, arg.UserID)
	var i LockUserOrderByNoRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.StoreID,
		&i.RegionID,
		&i.Status,
		&i.GoodsAmountCents,
		&i.FreightCents,
		&i.FreightDiscountCents,
		&i.DiscountCents,
		&i.PayableCents,
		&i.PaidCents,
		&i.RefundedCents,
		&i.RefundStatus,
		&i.ExpireAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UserCouponID,
		&i.CouponName,
		&i.PromotionDiscountCents,
		&i.Promotions,
		&i.Source,
		&i.ChannelOrderID,
	)
	return i, err
}

const otherRefundFreight = `-- name: OtherRefundFreight :one
SELECT COALESCE(SUM(freight_cents), 0)::bigint
  FROM refunds
 WHERE order_id = $1 AND id <> $2 AND status IN (10, 20, 30, 40)
`

type OtherRefundFreightParams struct {
	OrderID int64
	ID      int64
}

// 这一单**别的**退款单已经占掉（在途或已退）的运费，审核裁定退运费时的上限用。
func (q *Queries) OtherRefundFreight(ctx context.Context, arg OtherRefundFreightParams) (int64, error) {
	row := q.db.QueryRow(ctx, otherRefundFreight, arg.OrderID, arg.ID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const receiveRefundGoods = `-- name: ReceiveRefundGoods :execrows
UPDATE refunds SET status = 30, received_at = now(), received_by = $1
 WHERE id = $2 AND status = 20
`

type ReceiveRefundGoodsParams struct {
	ReceivedBy *int64
	ID         int64
}

// 商家确认收到退货：20 待买家退货 → 30 退款中。记下谁、什么时候收的（00035）。
func (q *Queries) ReceiveRefundGoods(ctx context.Context, arg ReceiveRefundGoodsParams) (int64, error) {
	result, err := q.db.Exec(ctx, receiveRefundGoods, arg.ReceivedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recomputeOrderRefundStatus = `-- name: RecomputeOrderRefundStatus :exec
UPDATE orders o
   SET refund_status = CASE
         WHEN EXISTS (SELECT 1 FROM refunds r
                       WHERE r.order_id = o.id AND r.status IN (10, 20, 30)) THEN 1
         WHEN o.refunded_cents = 0 THEN 0
         WHEN o.refunded_cents = o.paid_cents THEN 3
         ELSE 2
       END
 WHERE o.id = $1
`

// 按退款单的**当前事实**重算订单的资金维度（§5 refund_status）。
//
// 写成一条从 refunds 推出来的 UPDATE，而不是让每条路径各自赋一个值：
// 申请、撤回、驳回、到账四条路径都要改它，各写各的话，「退完一笔、另一笔还在途」
// 这种组合迟早有一条路径算错。规则只有一份：
//
//	有在途的退款单            → 1 退款中
//	没有在途、一分没退过       → 0 无退款
//	没有在途、退满了实收       → 3 全额退款完成
//	其余                      → 2 部分退款完成
//
// chk_refund_status 是它背后的兜底：算出来的值与 refunded_cents 对不上，写不进去。
func (q *Queries) RecomputeOrderRefundStatus(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recomputeOrderRefundStatus, id)
	return err
}

const recordRefundNotify = `-- name: RecordRefundNotify :exec
UPDATE refunds SET notify_payload = $2 WHERE id = $1
`

type RecordRefundNotifyParams struct {
	ID            int64
	NotifyPayload []byte
}

// 回调到了但我们不认这笔账（金额对不上）：只留下原始报文，状态不动。
// 钱的痕迹不能丢 —— 与支付回调「金额不符也落支付单」同一个态度。
func (q *Queries) RecordRefundNotify(ctx context.Context, arg RecordRefundNotifyParams) error {
	_, err := q.db.Exec(ctx, recordRefundNotify, arg.ID, arg.NotifyPayload)
	return err
}

const refundingQtyByItem = `-- name: RefundingQtyByItem :many
SELECT ri.order_item_id, SUM(ri.quantity)::int AS refunding_qty
  FROM refund_items ri
  JOIN refunds r ON r.id = ri.refund_id
 WHERE r.order_id = $1
   AND r.status IN (10, 20, 30)
 GROUP BY ri.order_item_id
`

type RefundingQtyByItemRow struct {
	OrderItemID  int64
	RefundingQty int32
}

// 这一单每一行的**在途**退款件数（契约 OrderItem.refunding_qty 的定义式，§11）。
// 在途 = 待审核 / 待买家退货 / 退款中。
func (q *Queries) RefundingQtyByItem(ctx context.Context, orderID int64) ([]RefundingQtyByItemRow, error) {
	rows, err := q.db.Query(ctx, refundingQtyByItem, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefundingQtyByItemRow
	for rows.Next() {
		var i RefundingQtyByItemRow
		if err := rows.Scan(&i.OrderItemID, &i.RefundingQty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRefund = `-- name: RejectRefund :execrows
UPDATE refunds SET status = 50, reject_reason = $1, audited_at = now(),
       audited_by = $2
 WHERE id = $3 AND status = 10
`

type RejectRefundParams struct {
	RejectReason *string
	AuditedBy    *int64
	ID           int64
}

// 审核驳回：10 → 50，必须带理由（chk_refund_state 也钉着这一条）。
// audited_by 记下是谁驳回的（00035 的审核记录）。
func (q *Queries) RejectRefund(ctx context.Context, arg RejectRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectRefund, arg.RejectReason, arg.AuditedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const returnCouponForOrder = `-- name: ReturnCouponForOrder :execrows
UPDATE user_coupons
   SET status = 1, order_id = NULL, locked_at = NULL, used_at = NULL
 WHERE order_id = $1 AND status = 3 AND valid_end_at > now()
`

// 整单退款到账时把券退回「未使用」（§11 末段）：3 已使用 → 1。
//
// 已过期的不退（valid_end_at 在谓词里）：退回一张已过期的券等于什么都没退，
// 还会让「我的券」里多出一张用不了的未使用券。那种情形由客服补发。
// chk_user_coupon_state 要求 1 未使用时 order_id / locked_at / used_at 全空，所以三列一起清。
func (q *Queries) ReturnCouponForOrder(ctx context.Context, orderID *int64) (int64, error) {
	result, err := q.db.Exec(ctx, returnCouponForOrder, orderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revertWholeOrderRefund = `-- name: RevertWholeOrderRefund :execrows
UPDATE orders SET status = 20 WHERE id = $1 AND status = 50
`

// 整单退款被驳回或撤回：订单 50 退款中 → 20 已支付（§5 的 (50,20)）。
func (q *Queries) RevertWholeOrderRefund(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revertWholeOrderRefund, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startWholeOrderRefund = `-- name: StartWholeOrderRefund :execrows
UPDATE orders SET status = 50 WHERE id = $1 AND status = 20
`

// 未发货的整单退款申请：订单 20 已支付 → 50 退款中（§5 两维度那张表的第一行）。
func (q *Queries) StartWholeOrderRefund(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, startWholeOrderRefund, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitReturnShipment = `-- name: SubmitReturnShipment :execrows

UPDATE refunds
   SET return_carrier_code = $1,
       return_tracking_no  = $2,
       return_submitted_at = now()
 WHERE id = $3 AND user_id = $4::bigint
   AND refund_type = 2 AND status = 20
`

type SubmitReturnShipmentParams struct {
	CarrierCode *string
	TrackingNo  *string
	ID          int64
	UserID      int64
}

// ---------------------------------------------------------------------------
// 状态推进。每一条都带预期的起点状态，失配影响 0 行；00034 的触发器是第二道。
// ---------------------------------------------------------------------------
// 买家填寄回物流（契约 POST /refunds/{refund_no}/return-shipment，00037）。
// **不改 status**：只有退货退款、只有停在 20 待买家退货时能填，20 期间可以覆盖
// （填错单号是常事）。user_id 是越权过滤，理由见文件头。
// 不经过状态机触发器（它挂在 UPDATE OF status 上），「只有 20 能填」由这里的谓词负责；
// chk_refund_return_shipment 兜住「三列同生同灭、只能在退货退款上」。
func (q *Queries) SubmitReturnShipment(ctx context.Context, arg SubmitReturnShipmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitReturnShipment,
		arg.CarrierCode,
		arg.TrackingNo,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const writeBackOrderItemRefund = `-- name: WriteBackOrderItemRefund :execrows

UPDATE order_items
   SET refunded_qty   = refunded_qty + $1,
       refunded_cents = refunded_cents + $2
 WHERE id = $3
   AND refunded_qty + $1 <= quantity
   AND refunded_cents + $2 <= amount_cents - discount_cents
`

type WriteBackOrderItemRefundParams struct {
	Qty    int32
	Amount int64
	ID     int64
}

// ---------------------------------------------------------------------------
// 入账（§11「退款与订单状态的联动」）
// ---------------------------------------------------------------------------
// 回写一行订单项的已退件数与金额。条件更新，与库存扣减同构：
// 影响 0 行 ⇒ 超退，整个入账事务回滚（§11 原文）。chk_item_refund 是第二道。
func (q *Queries) WriteBackOrderItemRefund(ctx context.Context, arg WriteBackOrderItemRefundParams) (int64, error) {
	result, err := q.db.Exec(ctx, writeBackOrderItemRefund, arg.Qty, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
