// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restock.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const restockCandidates = `-- name: RestockCandidates :many

SELECT s.id AS sku_id, s.product_id, p.title AS product_title, s.sku_code,
       COALESCE(s.spec_values::text, '{}')::text AS spec_values, s.created_at
  FROM skus s
  JOIN products p ON p.id = s.product_id
 WHERE s.deleted_at IS NULL AND s.status = 1
   AND p.deleted_at IS NULL AND p.status = 1
 ORDER BY s.product_id, s.id
`

type RestockCandidatesRow struct {
	SkuID        int64
	ProductID    int64
	ProductTitle string
	SkuCode      string
	SpecValues   string
	CreatedAt    pgtype.Timestamptz
}

// 补货计算（AI 经营 M9 任务 3，service/restock.go）的 core 这一半：候选 SKU 与已付款销量。
// 水位与断货天数在库存服务那边（inventory.Service.StoreStock / StockoutDays）。
// 和这个目录里别的文件一样，一个 merchant_id 都没有：租户由 RLS 过滤。
// 全部在售 SKU（商品在架、SKU 在售、都没软删），带人读的标签与上架时间（有效样本天数不能早于它）。
func (q *Queries) RestockCandidates(ctx context.Context) ([]RestockCandidatesRow, error) {
	rows, err := q.db.Query(ctx, restockCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestockCandidatesRow
	for rows.Next() {
		var i RestockCandidatesRow
		if err := rows.Scan(
			&i.SkuID,
			&i.ProductID,
			&i.ProductTitle,
			&i.SkuCode,
			&i.SpecValues,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeSKUSales = `-- name: StoreSKUSales :many
SELECT oi.sku_id, sum(oi.quantity)::bigint AS qty
  FROM order_items oi
  JOIN orders o ON o.id = oi.order_id
 WHERE o.store_id = $1
   AND o.status IN (20, 30, 40, 50)
   AND o.paid_at >= $2
 GROUP BY oi.sku_id
`

type StoreSKUSalesParams struct {
	StoreID int64
	Since   pgtype.Timestamptz
}

type StoreSKUSalesRow struct {
	SkuID int64
	Qty   int64
}

// 一家门店自 since 以来已付款订单的件数，按 SKU。状态 20 已支付 / 30 已发货 / 40 已完成 / 50 售后中都算卖出；
// 10 待支付、90 已关闭不算；60 已退款的整单退了，也不算。部分退款不扣（件数口径，退款多在事后，补货看的是需求）。
func (q *Queries) StoreSKUSales(ctx context.Context, arg StoreSKUSalesParams) ([]StoreSKUSalesRow, error) {
	rows, err := q.db.Query(ctx, storeSKUSales, arg.StoreID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreSKUSalesRow
	for rows.Next() {
		var i StoreSKUSalesRow
		if err := rows.Scan(&i.SkuID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
