// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
)

const listOnSaleSKUsOfProducts = `-- name: ListOnSaleSKUsOfProducts :many
SELECT s.product_id, s.id
  FROM skus s
 WHERE s.product_id = ANY($1::bigint[])
   AND s.status = 1
   AND s.deleted_at IS NULL
`

type ListOnSaleSKUsOfProductsRow struct {
	ProductID int64
	ID        int64
}

// 一批商品的在售 SKU（未软删、status = 1）。检索算 in_stock 用：拿这批 sku_id 向库存服务
// 问一次这家店的水位，「任意一个在售 SKU 水位 > 0」即有货。条件与拆分前那条 EXISTS 里的
// s.status = 1 AND s.deleted_at IS NULL 逐字一致。
func (q *Queries) ListOnSaleSKUsOfProducts(ctx context.Context, productIds []int64) ([]ListOnSaleSKUsOfProductsRow, error) {
	rows, err := q.db.Query(ctx, listOnSaleSKUsOfProducts, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOnSaleSKUsOfProductsRow
	for rows.Next() {
		var i ListOnSaleSKUsOfProductsRow
		if err := rows.Scan(&i.ProductID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByKeyword = `-- name: SearchProductsByKeyword :many
WITH ranked AS (
    SELECT p.id,
           ts_rank_cd(p.search_vector, to_tsquery('simple', $5::text))::float8 AS rank
      FROM products p
     WHERE p.deleted_at IS NULL
       AND p.status = 1
       AND p.id IN (SELECT keyword_hit_products(to_tsquery('simple', $5::text))
                     LIMIT $6::int)
       AND ($7::bigint IS NULL
            OR p.category_id = $7::bigint)
       AND NOT EXISTS (SELECT 1 FROM region_product_overrides ro
                        WHERE ro.region_id = $8
                          AND ro.product_id = p.id AND ro.status = 0)
       AND NOT EXISTS (SELECT 1 FROM store_product_overrides so
                        WHERE so.store_id = $1
                          AND so.product_id = p.id AND so.status = 0)
     ORDER BY rank DESC, p.id
     LIMIT CASE WHEN $2::bigint IS NULL
                 AND $3::bigint IS NULL
                THEN $4::int END
)
SELECT p.id, p.title, p.subtitle,
       COALESCE(agg.min_price, 0)::bigint AS min_price_cents,
       COALESCE(agg.max_price, 0)::bigint AS max_price_cents,
       p.sales_count, p.status,
       COALESCE(img.upload_id, 0)::bigint AS main_image_upload_id,
       r.rank
  FROM ranked r
  JOIN products p ON p.id = r.id
  LEFT JOIN LATERAL (
        SELECT min(pv.price_cents) AS min_price, max(pv.price_cents) AS max_price
          FROM sku_prices_by_store pv
         WHERE pv.store_id = $1 AND pv.product_id = p.id
       ) agg ON TRUE
  LEFT JOIN LATERAL (
        SELECT pi.upload_id
          FROM product_images pi
         WHERE pi.product_id = p.id
         ORDER BY pi.sort_order, pi.id
         LIMIT 1
       ) img ON TRUE
 WHERE ($2::bigint IS NULL
        OR COALESCE(agg.max_price, 0) >= $2::bigint)
   AND ($3::bigint IS NULL
        OR COALESCE(agg.min_price, 0) <= $3::bigint)
 ORDER BY r.rank DESC, p.id
 LIMIT $4::int
`

type SearchProductsByKeywordParams struct {
	StoreID       int64
	MinPriceCents *int64
	MaxPriceCents *int64
	RowLimit      int32
	Tsquery       string
	HitCap        *int32
	CategoryID    *int64
	RegionID      int64
}

type SearchProductsByKeywordRow struct {
	ID                int64
	Title             string
	Subtitle          *string
	MinPriceCents     int64
	MaxPriceCents     int64
	SalesCount        int32
	Status            int16
	MainImageUploadID int64
	Rank              float64
}

// bigram 关键词召回（语义检索层 §3）。
//
// @tsquery 是**应用层**切出来的 tsquery 串，由 internal/search.Bigram 的输出
// 用竖线拼成（internal/search.TSQueryOr），或去重后用 & 拼成（TSQueryAnd：多词查询先要求
// 全部命中，不够一页再用 OR 那条补齐，见 service/search.go 的 recallByKeyword）。这里不做任何分词：
// to_tsquery('simple', '连衣裙') 会把整句
// 中文当成一个 token，那正是 §3 开头说的「完全不可用」。
//
// 为什么 tsquery 是拼出来的字符串而不是绑定参数拼接的隐患：Bigram 的输出
// 只含字母、数字与表意文字，用空格分隔（其余字符一律当分隔符丢掉），
// tsquery 的元字符（& | ! ( ) : * ' <->）一个都活不下来。
// internal/search 里有一条测试专门钉这条性质。
//
// 排序用 ts_rank_cd 而不是 ts_rank：cd 版按**覆盖密度**算，命中的二元组挨得近
// 的排前面 —— 「连衣 衣裙」连着出现的商品，比一个只在标题头、一个只在副标题尾
// 各命中一次的商品更像是真的在说那个词。
//
// 命中集合由 keyword_hit_products（00172）给出，不在这里直接写 search_vector @@ ...：
// @@ 的实现 ts_match_vq 不是 leakproof，RLS 下 GIN 进不了计划，只能全店逐行匹配
// （每店 4 万商品 6.7 ms，随商品数线性变慢）。那个函数只返回本店命中的 id，
// 回 products 这次 JOIN 仍在 RLS 之下 —— 租户隔离照旧只靠 RLS，理由写在那份迁移里。
//
// 过滤条件与上面那条逐字一致，理由写在文件头。
//
// ## 先排序截断、再补价格与图片（2026-10 性能压测，第六节 ③）
//
// 以前是一层：对**全部**命中先算价格区间与主图（两个 LATERAL），再 ORDER BY ... LIMIT。
// 长尾词 OR 召回 9980 件时价格 LATERAL 跑 9980 次（217 ms），而最后只要 @row_limit 件。
// 现在拆成两层：
//
//	· 内层 ranked：只用不涉及价格的条件（status / deleted_at / 命中集合 / 类目 / 两层可见性）
//	  筛，按 ts_rank_cd 排、截到 @row_limit 件，只出 id 与分数；
//	· 外层：对这 @row_limit 件补价格、主图，做价格过滤，再排一次（同一个键）。
//
// **结果与一层写法逐行相同**：不带价格过滤时，外层的过滤恒真，内层的排序键
// （rank DESC, id）是全序，截断前后的前 @row_limit 件是同一批、同一个顺序。
// **带价格过滤时内层不截断**（LIMIT NULL 即不限）：价格是外层才算出来的，先截再滤会把
// 「排在前 N 之外、但价格落在区间里」的那些漏掉，返回的就不是「区间内相关度最高的 N 件」了。
// 那条路的耗时与改之前相同 —— 价格区间筛选本身就要先知道每件的价格。
//
// ## 命中集合的上限 @hit_cap（2026-10 复压，第十节 ③）
//
// 截断砍掉了价格 LATERAL，但内层的 ts_rank_cd 仍要对**全部**命中逐件算：长尾词 OR 召回近万件时，
// 这一步在 32 并发下排队，搜索 p95 474 ms。@hit_cap 给命中集合封顶，只在 OR 补齐那一条上传
// （service/search.go 的 recallByKeyword）；NULL 不封顶（AND、单词查询都是 NULL）。
// 封顶取的是命中集合里**任意** N 件（keyword_hit_products 的物理顺序），不是相关度最高的 N 件：
// 能走到 OR 的只有「全部词都命中的不够一页、向量路也没跑成」那种查询，那时 OR 补进来的本来就只是
// 「沾上一个二元组」的候选，在里面精挑不值近万次打分。全部命中的那批由 AND 那条另取，不受影响。
//
// 过滤条件拆在两层，但**合起来**仍与向量那条逐字一致（TestBothRecallPathsFilterIdentically 在守）。
func (q *Queries) SearchProductsByKeyword(ctx context.Context, arg SearchProductsByKeywordParams) ([]SearchProductsByKeywordRow, error) {
	rows, err := q.db.Query(ctx, searchProductsByKeyword,
		arg.StoreID,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.RowLimit,
		arg.Tsquery,
		arg.HitCap,
		arg.CategoryID,
		arg.RegionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsByKeywordRow
	for rows.Next() {
		var i SearchProductsByKeywordRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.SalesCount,
			&i.Status,
			&i.MainImageUploadID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsByVector = `-- name: SearchProductsByVector :many

SELECT p.id, p.title, p.subtitle,
       COALESCE(agg.min_price, 0)::bigint AS min_price_cents,
       COALESCE(agg.max_price, 0)::bigint AS max_price_cents,
       p.sales_count, p.status,
       COALESCE(img.upload_id, 0)::bigint AS main_image_upload_id,
       (v.embedding <=> $1::vector)::float8 AS distance
  FROM product_text_vectors v
  JOIN products p ON p.id = v.product_id
  LEFT JOIN LATERAL (
        SELECT min(pv.price_cents) AS min_price, max(pv.price_cents) AS max_price
          FROM sku_prices_by_store pv
         WHERE pv.store_id = $2 AND pv.product_id = p.id
       ) agg ON TRUE
  LEFT JOIN LATERAL (
        SELECT pi.upload_id
          FROM product_images pi
         WHERE pi.product_id = p.id
         ORDER BY pi.sort_order, pi.id
         LIMIT 1
       ) img ON TRUE
 WHERE p.deleted_at IS NULL
   AND p.status = 1
   AND ($3::bigint IS NULL
        OR p.category_id = $3::bigint)
   AND ($4::bigint IS NULL
        OR COALESCE(agg.max_price, 0) >= $4::bigint)
   AND ($5::bigint IS NULL
        OR COALESCE(agg.min_price, 0) <= $5::bigint)
   AND NOT EXISTS (SELECT 1 FROM region_product_overrides ro
                    WHERE ro.region_id = $6
                      AND ro.product_id = p.id AND ro.status = 0)
   AND NOT EXISTS (SELECT 1 FROM store_product_overrides so
                    WHERE so.store_id = $2
                      AND so.product_id = p.id AND so.status = 0)
 ORDER BY v.embedding <=> $1::vector
 LIMIT $7
`

type SearchProductsByVectorParams struct {
	QueryEmbedding string
	StoreID        int64
	CategoryID     *int64
	MinPriceCents  *int64
	MaxPriceCents  *int64
	RegionID       int64
	RowLimit       int32
}

type SearchProductsByVectorRow struct {
	ID                int64
	Title             string
	Subtitle          *string
	MinPriceCents     int64
	MaxPriceCents     int64
	SalesCount        int32
	Status            int16
	MainImageUploadID int64
	Distance          float64
}

// 混合检索的两路召回（M3 Task 4）。向量一路、bigram 关键词一路，
// RRF 融合在应用层（语义检索层 §4），不在 SQL 里。
//
// 和这个目录里别的文件一样，**一个 merchant_id 都没有** —— 租户由 RLS 在
// 数据库层过滤。理由见 scripts/check_query_tenancy.py 的文件头。
//
// 两条查询的**过滤条件必须逐字一致**（deleted_at / status / 三个 filters）。
// 不一致的后果不是报错，是一件商品在一路里可见、在另一路里不可见 ——
// 而 RRF 只看名次，它拿到的是两份对「哪些商品存在」意见不同的列表，
// 融合出来的排序没有意义，且没有任何东西会红。
//
// **M4 Task 3 起价格区间是现算的**（00019 删掉了 products 上那两列冗余价格），
// **本轮（00020）它又跟着门店走了**：取价口从 skus.price_cents 换成
// sku_prices_by_store 视图，检索结果里的价格区间从此是「按当前门店算出来的」。
// 这条纪律因此多了一项：那个 LEFT JOIN LATERAL 与两处 COALESCE 也必须逐字
// 一致 —— 价格过滤现在读的是它算出来的值，两边的公式写岔一个字，
// 同一件商品就会在一路里落进价格区间、在另一路里落在外面。
//
// 逐字一致这条纪律本轮又多了一项：两层可见性排除（region / store 各一条
// NOT EXISTS）。
//
// **in_stock 与 in_stock_only 不在这两条里了**（微服务拆分阶段 1a）：inventories 归库存
// 服务，召回查询不再 JOIN 它。service/search.go 在两路召回之后，用 ListOnSaleSKUsOfProducts
// 取候选商品的在售 SKU、向库存服务按**这家门店**批量问一次水位，在 Go 里算 in_stock
// （任意一个在售 SKU 水位 > 0，判据不变）；in_stock_only 从 SQL 里的过滤变成召回之后的
// 过滤 —— 代价是一次检索返回的条数可能少于 size（召回窗口里缺货的多时），写在那个文件里。
//
// COALESCE 到 0 不是随手写的：旧列 min/max_price_cents 的 DEFAULT 是 0，
// 于是「一个 SKU 都没有」的商品在旧的过滤里表现为 max=0（被 min_price 筛掉）
// 与 min=0（**通过** max_price 筛选）。裸的 max()/min() 在那种情况下是 NULL，
// 而 NULL 两个方向都不通过 —— 那就不是「换了个算法」，是悄悄改了一条筛选规则。
// 留着 COALESCE，现算与旧列在全部取值上逐点相同。
//
// 两条都带同一个取主图的 LEFT JOIN LATERAL（main_image_upload_id，可空），
// 写法与 products.sql 的 ListProducts 逐字一致：sort_order 最小、id 次之的那一张。
// 没有图时是 0 而不是 NULL（sqlc 推不出那一侧可空，理由写在 ListProducts 上）。
// 它不参与任何过滤，写岔了不会让结果集变样，但会让同一件商品在列表与检索里
// 顶着两张不同的封面；更隐蔽的是检索内部：两路都命中时 service 合并留的是
// 关键词路那一行，只命中向量路时留的是向量路那一行（service/search.go 的 byID）
// —— 两路写岔，同一件商品的封面就取决于这次是哪一路捞到了它。
// 向量召回。余弦距离，配 idx_ptv_hnsw（vector_cosine_ops）。
//
// ## 这条查询就是语义检索层 §2.4 里那个「❌ 危险写法」，一字不差
//
// 它 JOIN products、带类目与价格过滤、ORDER BY 距离 LIMIT N。文档说规划器
// 可能先取向量最近的 N 条再过滤，类目稀疏时返回远少于 N 条甚至为空；
// 而在这个仓库里过滤条件还多一条**看不见的** RLS 谓词
// 「按商家过滤」那一条（00016 文件头第三节）。
//
// **不在这里躲它。** 躲的写法是先在 product_text_vectors 上单独召回一批
// product_id、再在应用层过滤 —— 那样 filters 就变成了纯粹的 post-filter，
// 用户一加价格区间结果就会少一大截，而且少多少应用自己也不知道。
// 把条件推进来、让规划器自己决定是先过滤还是先走索引，是**更好**的形状：
// 小租户它会选精确的顺序扫描（实测 300 件时 13 ms、100% 准），
// 大租户它会选 HNSW，而 HNSW 被选中时的正确性由
// repository.withTenantTx 设的那三个 hnsw.* GUC 兜住。完整实测见那里。
//
// in_stock 在 service 里算（见文件头），判据是「任意一个在售 SKU 水位 > 0」，与
// ProductDetail.InStock 同一个（service/product.go）—— 不读汇总列：曾经的
// products.total_stock 没有任何一处在维护（已停用，见 00062）。
func (q *Queries) SearchProductsByVector(ctx context.Context, arg SearchProductsByVectorParams) ([]SearchProductsByVectorRow, error) {
	rows, err := q.db.Query(ctx, searchProductsByVector,
		arg.QueryEmbedding,
		arg.StoreID,
		arg.CategoryID,
		arg.MinPriceCents,
		arg.MaxPriceCents,
		arg.RegionID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsByVectorRow
	for rows.Next() {
		var i SearchProductsByVectorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.SalesCount,
			&i.Status,
			&i.MainImageUploadID,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
