#!/usr/bin/env python3
"""生成 internal/understanding/homophone_gen.go：违禁词变体兜底用的同音字表。

===========================================================================
一、这张表是什么
===========================================================================

表长这样：

    '醉': '最',     // 醉 → 最
    '嘴': '最',
    '罪': '最',
    '冣': '最',

文本扫过一遍把左边的字换成右边的，之后**复用原有的精确词表匹配**。
「这款嘴便宜」→「这款最便宜」→ 命中「最便宜」。

===========================================================================
二、为什么值的范围被限定成「多字词条的首字」
===========================================================================

一开始的做法是对整张词表做拼音归一化，实测（用演示库 42 个标题 + search_logs
1102 条真实搜索词 + 项目刹车测试那几条反例跑的）**当场撞出误拒**：

  · 「蕞」是词表里唯一一条单字条目。拼音空间里它就是一个 zui 音节，
    于是「最近」「最后」「最初」「最多」全被当成「蕞」拦下 ——
    TestCommonChineseWordsAreNotFlagged 四条一起红。
  · 「神器」与「神奇」在拼音空间里是同一个串 shen|qi。放开整词拼音化，
    「神奇的清洁力」会被判违规，而那是再正常不过的一句商品文案。

根子是：**中文同音字太多，两个音节的词在拼音空间里碰撞是常态**。
所以值域收窄到一个很具体的位置 —— 只替换**多字词条的第一个字**。

这个收窄有依据：躲词表的人替换的是「最 / 第 / 绝 / 顶 / 国」这类**显眼**
的字，不是「好 / 佳 / 级」这种中性字。限到首字之后：

  · 「醉佳」「嘴便宜」「决对领先」「鼎级」照旧拦得住（都是首字被换）；
  · 「神奇」安全 —— 「奇」不是任何词条的首字，qi 这一组因此根本不进表；
  · 「一级品」安全 —— 「级」不是首字，ji 组的去向不是「极」。

===========================================================================
三、代价
===========================================================================

  · **纯拼音写法（zuihao）拦不住。** 汉字 → 汉字的表碰不到 ASCII 串。
    要挡它就得整词拼音化，而那正是上面撞出误拒的那条路。取舍是明确的：
    误拒会让**所有**商家发不了货，漏拦只放过一个故意躲的人。
  · **非首字的谐音拦不住。** 「遥遥领衔」不会匹配「遥遥领先」。
  · 多音字取默认读音，偏差的方向是漏拦而不是误拒。

===========================================================================
四、用法
===========================================================================

    python3 scripts/gen-homophone.py     # 直接写文件，不是打到 stdout

需要 pypinyin（生成期依赖，不进 Go 的 go.mod）。
"""
import io
import os
import re
import sys

from pypinyin import Style, lazy_pinyin

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORDLIST = os.path.join(ROOT, "internal/understanding/wordlist.go")
OUT = os.path.join(ROOT, "internal/understanding/homophone_gen.go")

CJK = lambda c: "\u4e00" <= c <= "\u9fff"


def gb2312_chars():
    """GB2312 一二级汉字（6763 个）当「常用字」的边界。

    不扫 CJK 全区间：那两万多字里绝大多数生僻字永远不会出现在商品标题里，
    把它们塞进表只会让一个本来能读的 Go map 变成一坨没人看得懂的数据。
    """
    out = []
    for hi in range(0xB0, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                out.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                continue
    return out


def main():
    src = io.open(WORDLIST, encoding="utf-8").read()
    terms = re.findall(r'\{"([^"]+)",\s*rule\w+\}', src)
    if not terms:
        sys.exit("没从 wordlist.go 里解析出任何词条，先看看正则和词表格式")

    # 多字词条的首字，按词表出现顺序去重。
    #
    # 取「第一个」而不是「排序最小的」：词表的顺序是人工维护的、能被 diff 看见的，
    # 而排序结果是拼音库的副产品。同一个读音有多个候选首字时，
    # 用哪个必须是一个能被评审看见的决定。
    heads = []
    for t in terms:
        if len(t) >= 2 and CJK(t[0]) and t[0] not in heads:
            heads.append(t[0])

    # 读音 → 首字（一个读音只留一个，按上面的顺序）
    want = {}
    for h in heads:
        py = lazy_pinyin([h], style=Style.NORMAL)[0]
        want.setdefault(py, h)

    gb = gb2312_chars()
    gpy = lazy_pinyin(gb, style=Style.NORMAL)
    canon = {}
    for ch, py in zip(gb, gpy):
        if py in want and ch != want[py]:
            canon[ch] = want[py]

    lines = [
        "// Code generated by scripts/gen-homophone.py. DO NOT EDIT.",
        "//",
        "// 同音字 → 规范字。文本扫过一遍把左边的字换成右边的，之后复用原有的",
        "// 精确词表匹配：「这款嘴便宜」→「这款最便宜」→ 命中「最便宜」。",
        "//",
        "// 右边那些字**只有词表里多字词条的首字**。为什么收这么窄，以及放开之后",
        "// 实测撞出来的两条误拒（单字条目「蕞」吃掉「最近/最后/最初/最多」、",
        "// 「神器」与「神奇」在拼音空间里是同一个串），写在生成脚本的文件头第二节。",
        "// 一句话：中文同音字太多，两音节的词在拼音空间里碰撞是常态，",
        "// 而躲词表的人换的是「最/第/绝/顶」这种显眼的字，不是「好/佳」这种中性字。",
        "//",
        "// 因此拦不住的两类，都知道：纯拼音写法（zuihao）与非首字的谐音",
        "// （「遥遥领衔」不配「遥遥领先」）。它们的代价是漏拦，",
        "// 而放开值域的代价是误拒 —— 误拒会让所有商家发不了货，方向不能选错。",
        "",
        "package understanding",
        "",
        "// homophoneCanonical 是那张字 → 规范字的表。%d 条。" % len(canon),
        "var homophoneCanonical = map[rune]rune{",
    ]
    for ch in sorted(canon):
        lines.append("\t%r: %r," % (ch, canon[ch]))
    lines.append("}")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("词条 %d；首字 %d 个：%s" % (len(terms), len(heads), "".join(heads)))
    print("同音归一 %d 条 -> %s" % (len(canon), OUT))
    for ch in ("醉", "嘴", "罪", "冣", "决", "鼎"):
        if ch in canon:
            print("  样例 %s → %s" % (ch, canon[ch]))


if __name__ == "__main__":
    main()
